### ISSUE TITLE
Limit how player exits compact machine

### ISSUE THREAD

**Issue by Soloist1twitch** [CompactMods/CompactMachines#148]
Compact Machines look like they could be used to great effect in puzzle maps.  But in order to be really useful, it would be nice to limit how the player can exit a machine.

It would help if the player needed to right click with the PSD on one of the compact machines walls, floor, or ceiling blocks to exit.  So you could design a compact machine that had all of the walls, floor, and ceiling blocks covered with some other block ( like Obsidian ) until some condition was met.  Then the map maker could provide access to a compact machine block where the player could right click with the PSD and exit the compact machine.

It appears that right now the player just needs to right click with the PSD, and will exit a compact machine.

Hope this makes sense.....

**Comment by thraaawn** [comment]
It does make sense and I will think about a solution I'm happy with. Thanks for the suggestion, I will keep you informed!

**Comment by NPException42** [comment]
If you don't mind, I'll grab the general idea and do something like that in DP as well. :)

**Comment by Soloist1twitch** [comment]
Thanks!  The other suggestion I had was a way to create one of these that did not allow the user to be able to enter it with their PSD.  A protected machine.  This would allow a map creator the ability to create a puzzle that required the user to figure out how to use the machine or machines, but not be able to go into the machine to figure out exactly how it worked.  I wanted them to be able to examine the interfaces, to know which were input and output, and see the buffers.  I realize that this is not something that one would normally do with these machines.....

**Comment by thraaawn** [comment]
But it's kinda genius :+1:

**Comment by Soloist1twitch** [comment]
Great!  I'll stop now.  I certainly won't mention that it would be really cool to have configurable sizes.  Not for normal play of course, and certainly not craftable.  But I could see larger machines that would almost appear as a mini-biome...  But I didn't mention it.....  ;)

**Comment by ghost** [comment]
There was a 1.7 modpack called [Incepticube](https://minecraft.curseforge.com/projects/incepticube?gameCategorySlug=modpacks&projectID=247269) based on Compact Machines.
