### ISSUE TITLE
Crash when running Optifine in a version newer than 1.7.10_HD_U_D4

### ISSUE THREAD

**Issue by TacoUpgrade** [CompactMods/CompactMachines#196]
i understand that the 1.7.10 is not supported but it was working yesterday morning but i tried it later that day and it crashed and i tried it just now no good but then it tried my modpack on a fresh client on the same pc works so can anyone tell me what is making it crash
[crash-2017-04-04_10.19.24-client.txt](https://github.com/thraaawn/CompactMachines/files/893442/crash-2017-04-04_10.19.24-client.txt)

**Comment by davenonymous** [comment]
Somebody else had the same issue with newer versions of optifine.
Reverting Optifine to version 1.7.10_HD_U_D4 fixed the problem for him.

**Comment by TacoUpgrade** [comment]
ok i will try that

**Comment by TacoUpgrade** [comment]
thanks it is working
