### ISSUE TITLE
Compatibility with mods changing the player model/size

### ISSUE THREAD

**Issue by davenonymous** [CompactMods/CompactMachines#198]
As report by @Drakkar666 in #191:
While I'm not sure if that's just my screen issue, which occurs whenever I boot my PC, as of now Compact Machines 2.0.0-b98 together with More Player Models for 1.10 causes weird flickering wave on my screen, this occurs only when you make your player model taller or shorter. It works fine with normal player height.

**Comment by brisingraerowing** [comment]
I notice this as well with More Player Models and this mod, so it's not just @Drakkar666. Something seems messed up. I will try removing More Player Models (I actually am not using it all that much) to see if the flickering goes away.

**Comment by mzx987** [comment]
I know this issue is a bit old, but I can confirm that before I added Compact Machines 2 (along side with More Player Models), I did not experience this flickering.

**Comment by davenonymous** [comment]
The feature will be removed in CM3 completely :( Going to refocus on the machines.
