### ISSUE TITLE
CM2 b100 Crash on game startup

### ISSUE THREAD

**Issue by brisingraerowing** [CompactMods/CompactMachines#200]
[Crash Log](https://gist.github.com/BrisingrAerowing/90b66f7aea866044d5099a2315ff99d8)

I get this crash on game startup each and every time.

Mod Version: b100
Forge Version: 12.18.3.2281

**Comment by The-Scout** [comment]
Having the same problem here
[Heres my log](https://github.com/thraaawn/CompactMachines/files/931722/crash-2017-04-18_22.59.07-client.txt)

**Comment by davenonymous** [comment]
Sorry about that. Uploading a fixed version to curse now. Should be available soonish.
