### ISSUE TITLE
I'm having issues undrestanding use of "Tunnel" and getting it to output?

### ISSUE THREAD

**Issue by DarkyAlan** [CompactMods/CompactMachines#201]
I'm not really grasping how the tunnel works, I can get it to say it's outputting somewhere and I can get conduits (EnderIO) to visibly connect from both ends but nothing seems to output from the compact machine.

Any documentation regarding the use of the tunnel would be appreciated.

**Comment by davenonymous** [comment]
From the ingame documentation:
Tunnels are using the Forge Capability system to "connect" the two blocks. Other mods need to use this system for tunnels to work properly. This is the case for most storage, but rarely for multiblock systems, so expect some pipes etc to not work as expected.

In your case one of the tunnel ends must not be a conduit, but a chest, omnibuffer or something like that.
