### ISSUE TITLE
Two Features (Naming Machines and Rebinding Lost Machines)

### ISSUE THREAD

**Issue by brisingraerowing** [CompactMods/CompactMachines#202]
How about adding the ability to name a machine and have that name show on it's tooltip. That would allow players who have multiple machines to be able to differentiate them without having to put up signs or label them in some other way.

Also, what happens if a player somehow looses a machine (e.g. being destroyed somehow)? If the room is basically lost, how about adding the ability to unbind and rebind machines to rooms using the personal shrinking device (the room and machine must be of the same size, of course). This would also help if a player's machines are stolen by another player. The affected player can use the personal shrinking device to unbind the stolen machines remotely and later rebind the rooms to new machines.

Otherwise, this is a great mod and I look forward to seeing where it goes.

**Comment by davenonymous** [comment]
Thanks for the feedback!
You can already rename machines using an anvil. It should work as you've described.

I don't think I will add a way to recover lost machines besides op commands. You also can't recover your refined storage disk drives for example. Poof, all gone. Do you have good reasons why it should be different with Compact Machines?

**Comment by Ristellise** [comment]
I feel that allowing th rebind is more realistic and friendly towards the player... for example.. any player can just be an absolute (beep) when they take people's compact machine. they may hold it at ransom for real money which the player may not afford. So theres the risk of that. having it unbound from OP's makes moderation lesser of a hassle.

**Comment by davenonymous** [comment]
The same question remains unanswered: I can just take all of your AE/RS storage disks. There's nothing preventing me from doing that either. Not sure why CMs should be different.

Currently the cleanest solution to both these problems seems to be some sort of chunk protection mechanism like FTB Utilities has, if I remember correctly.
