### ISSUE TITLE
Crashing on windows server

### ISSUE THREAD

**Issue by beamer91** [CompactMods/CompactMachines#203]
I'm trying to start a new server for all the mods and I am getting a crash stating

[11:55:03] [Server thread/ERROR] [FML/]: Caught exception from Compact Machines 2 (cm2)
java.lang.RuntimeException: Could not list recipes from path: "assets/cm2/config/recipes"

Here is a log to the full log. [https://paste.ee/p/zbhsw](https://paste.ee/p/zbhsw)

**Comment by davenonymous** [comment]
Weird, I'll look into it over the weekend.

**Comment by davenonymous** [comment]
Really weird, I can not reproduce this. How are you starting the server?
Can you retry with build 105? You can get it here: https://www.dropbox.com/sh/7yyd9dgii1epibu/AADARWLwgjOBu9wU-zZVHp-ra?dl=0
