### ISSUE TITLE
[1.10.2] Crashing after server restart

### ISSUE THREAD

**Issue by YOYOK9** [CompactMods/CompactMachines#204]
Started a new server world and after switching from a batch file start to using amp to start it I get this crash on startup:
https://pastebin.com/whiLLq7X

cm2: 2.0.0-b104
Forge: 1.10.2-12.18.3.2297-universal
Sponge: 1.10.2-2281-5.2.0-BETA-2341
mc: 1.10.2

**Comment by davenonymous** [comment]
Duplicate of #203
