### ISSUE TITLE
CM2 oddities appearing in world gen

### ISSUE THREAD

**Issue by BrewingCoder** [CompactMods/CompactMachines#205]
this is MC version 1.11.2  on forge 13.20.0.2299

Mod version cm2-1.11.2-2.0.1-b106

I'm getting some really weird world gen (default generator) and have walls and fluid at random locations in the world.  I'm not sure what's causing it.  Let me know if you want a complete mod list but was curious if there was any light you could shed on it.

![2017-06-03_01 00 12](https://cloud.githubusercontent.com/assets/6723474/26750789/821ff8c8-47f8-11e7-94a6-daa13dd13a6f.png)

**Comment by davenonymous** [comment]
That's normal world gen. A feature, not a bug.
Unless: Is it just floating in the air? It should touch the ground in some way. If it isn't something is off with determining the height where it generates.

**Comment by BrewingCoder** [comment]
it is floating; I just don't remember it being so broken up.  Maybe the last world I played was just a fluke. You can ignore my ramblings.

**Comment by brisingraerowing** [comment]
I've seen them floating as well, but I think that is caused by it generating on some leaves or something and those leaves then decaying, as I caught a situation like that in one of my worlds.
