### ISSUE TITLE
connecting compact machine

### ISSUE THREAD

**Issue by GizmoTheAssassan** [CompactMods/CompactMachines#206]
could you make you could do some where if you put max sized compact machine in a 3x3x3 it could make a mega super compact machine

**Comment by davenonymous** [comment]
I do not understand.

**Comment by GizmoTheAssassan** [comment]
could you make so if you make  a 3x3x3 of max sized compact machines it makes an even bigger compact machine

**Comment by davenonymous** [comment]
No, sorry. 13x13x13 is the maximum size that fits inside of a single chunk.
