### ISSUE TITLE
[Suggestion] Shrinking Device

### ISSUE THREAD

**Issue by Ravin890** [CompactMods/CompactMachines#207]
I know there is config options dealing with the length of how long you stay small, but if you were able to stack the effects via an item it would be cool. So for example having eating the drop last 20 seconds, and being able to stack them to last you for a longer period of time. (Basically eliminating the need to eat them constantly to stay small without needing to change the configs)

**Comment by davenonymous** [comment]
Hold a charged PSD in your off-hand. That's a cheaper and easier way to shrink yourself.

**Comment by Ravin890** [comment]
Wait you can do that?

**Comment by GrumpNugget** [comment]
Wondering if you could make a config option for charge usage when holding the device. atm it drains fairly quickly and  i'd like to be able to set how quickly it drains when using it as a shrinking device

**Comment by orionSquared** [comment]
I would love the ability to change how long each % from the PSD lasts. I've been looking for a mod to allow me to shrink myself for easy C&B work, and using the PSD in the offhand is the PERFECT solution. Just wish it lasted longer.

**Comment by davenonymous** [comment]
I don't have the time to maintain older versions of the mod anymore, sorry :(
But 1.12 will get a beta release soon and that will be actually maintained!

But it does not have the player shrinking functionality, so :hankey: all I can say is: sorry for teasing you with an alpha version feature, that will not make it into beta/stable.
