### ISSUE TITLE
[Feature Request] TheOneProbe support

### ISSUE THREAD

**Issue by brisingraerowing** [CompactMods/CompactMachines#208]
Could support for TheOneProbe be added? I use that instead of WAILA/HWYLA as I like it better.

**Comment by davenonymous** [comment]
Yupp. Will be coming. I might actually be dropping the waila thing altogether.

**Comment by DeadSix27** [comment]
@thraaawn if its not too much work to keep the waila code in, i'd be for that, I only use hwyla(waila)
