### ISSUE TITLE
[1.11.2]Charging of Personal Shrinking Device cause duplication

### ISSUE THREAD

**Issue by maham** [CompactMods/CompactMachines#209]
When I put the PSD and a drop of Miniaturization Fluid in a crafting grid the uncharged PSD and the drop are not removed from the grid when I pick up the charged PSD. I'm using cm2-1.11.2-2.0.1-b106 from Twitch.

**Comment by davenonymous** [comment]
Confirmed, will look into it.

**Comment by davenonymous** [comment]
CM3 will not have miniaturization fluid drops in the first place and the PSD will not be chargeable (at least not with that fluid).
