### ISSUE TITLE
Just a few Questions

### ISSUE THREAD

**Issue by InflamedSebi** [CompactMods/CompactMachines#210]
1) Uhm are there op commands to list all existing cubes and rebind them yet? mentioned here: https://github.com/thraaawn/CompactMachines/issues/202
We have a few, that were lost ...

Also are you aware that getting out of the cube is a thing? f.e. The Staff of traveling (Ender I/O).
So people started making a 3x3, glitch out and start building there like in a void World.
Just a few questions regarding this:
2a) if the chunk was already generated (f.e. a player flying by) and a new machine will be created, will it spawn in an existing chunk or skip until it finds an empty one? Or will it even break something if the chunk already exists?
2b) can u point me to the spawning algorithm? (like how far apart from each other it will generate and in which pattern)
2c) any plans on adding protection for this issue? Maybe teleport escaping players back in? (Radom Things - Spectre Dimension has a fix for this)

3) any plans on adding a glass roof on cubes, so solar stuff will work in it?

4) AE2 seems to not work with CM2, is this an issue or just not implemented yet?

TY for your time.

**Comment by infogulch** [comment]
It also seems to not be working with Ender IO conduits or mekanism cables. In fact, I'm not seeing any interface blocks on the interior at all in 1.10.2...

**Comment by davenonymous** [comment]
- Yeah, I cared about people escaping from it in CM1, not so much in CM2. Maybe I'll add this back in in CM3 (the 1.12 version).
- The cube generator does not care whether there is air or a large base in the chunk it's generating the cube in. Blocks will get overwritten.
- Cubes have an incrementing ID that is used to determine their position. The algorithm to get that position is [here](https://github.com/thraaawn/CompactMachines/blob/1.10.2/src/main/java/org/dave/cm2/world/tools/StructureTools.java#L54), but to keep it simple: they all get generated in a row along the X axis, 1024 blocks apart from each other, i.e.: x=ID*1024, y=40, z=0, so the first cube is at 0,40,0, second cube 1024,40,0, third cube 2048,40,0 and so on.
- Glass roofs and other upgrades require lots of work. Not sure if/when I'll implement these things.
- I'll look into more mod integrations for CM3.
- Interface blocks have been replaced by Tunnels. Use the tunnel tool to place them freely on the walls how you'd like, i.e. you can now reposition them and even use them with different sides, i.e. a tunnel on the east wall can still map to the machines top side.

**Comment by infogulch** [comment]
Re: Tunnels: Oh that's awesome! I suppose I could have poked around a bit more to find that.

Which mod integrations does CM2 support now?
