### ISSUE TITLE
[1.12.1] Random crash when placing projectors

### ISSUE THREAD

**Issue by TheLimePixel** [CompactMods/CompactMachines#215]
So I was just placing projectors around, trying to figure out how they work and then I randomly got a crash:  https://pastebin.com/J9KqM3WQ

**Comment by davenonymous** [comment]
Weird. That shouldn't happen or at least i'm not sure why it is. Should be an easy workaround/fix though.

**Comment by davenonymous** [comment]
I can not reproduce this at all. Anyway, a workaround is incoming and i'll upload a new build to curse right away.
