### ISSUE TITLE
[1.12] Crash when putting multiple catalysts

### ISSUE THREAD

**Issue by TheLimePixel** [CompactMods/CompactMachines#217]
So, I wanted to test out the crafting system, I built the structure, I threw the catalyst and then nothing was happening. So just in case, I threw in a second catalyst and the world crashed: https://pastebin.com/RqXxaLxK

**Comment by davenonymous** [comment]
Oops, will fix asap.

**Comment by davenonymous** [comment]
Fixed build is on curse forge.
