### ISSUE TITLE
Stall on World Creation

### ISSUE THREAD

**Issue by cjm721** [CompactMods/CompactMachines#218]
Version: 1.12.1-3.0.0-b124

Server seems to be stalling when the world needs to be created (player login with TE in region)

Gist: https://gist.github.com/cjm721/c1e63a14245e8160af4367c888dd8a55

**Comment by davenonymous** [comment]
At work at the moment, will fix later today. Sorry for the inconvenience.

**Comment by cjm721** [comment]
I let watch dog generate a crash report (normally I auto kill it before it gets to that point) in case it is really from a conflict.

Gist: https://gist.github.com/cjm721/1398a75f35f89fc07f082660a09d9db1

**Comment by davenonymous** [comment]
Oops, that should fix it. Will upload to curse once travis finished the build.
Could you retest with that please? Edit: Builds are also available [here](https://www.dropbox.com/sh/7yyd9dgii1epibu/AADARWLwgjOBu9wU-zZVHp-ra?dl=0), uploaded directly by travis.

**Comment by cjm721** [comment]
Your change did fix it.
