### ISSUE TITLE
PCD Duplication Bug

### ISSUE THREAD

**Issue by orionSquared** [CompactMods/CompactMachines#219]
Hello,

I have your mod installed on one of my modpacks and it seems that when I craft a PCD with the miniature shrinking drop thingie, it duplicates the PCD and never uses up the droplet. So I'm able to pull the PCD out of the crafting table as a finished craft, but the recipe is never cleared.

This happens in both the 2x2 inventory crafting window and the 3x3 crafting table.

Thanks :)

**Comment by brisingraerowing** [comment]
I believe that this is a known issue.

**Comment by davenonymous** [comment]
It is a known issue. I also don't have the time to maintain older versions of the mod anymore, sorry :(
Thankfully, I never took the 1.10.2 nor the 1.11 out of alpha, so people are aware that these are as buggy as they can be.

But 1.12 will get a beta release soon and that will be actually maintained!
