### ISSUE TITLE
Mod Suggestion 1.12

### ISSUE THREAD

**Issue by orionSquared** [CompactMods/CompactMachines#220]
Good morning,

I have a suggestion. I know that in the new 1.12 version of the mod, you've removed the miniaturization liquid from the world gen and crafting mechanic. But this also removed the ability to shrink yourself down with the PSD in your offhand. It'd be great to have a config option to turn that ability on, or perhaps some other mechanic to allow semi-long term miniaturization of yourself. It was super handy when working with C&B and made your mod a must-have when C&B is installed.

**Comment by davenonymous** [comment]
I'll leave this to other mods to handle, see for example: [Lilliputian](https://minecraft.curseforge.com/projects/lilliputian), [[src]](https://github.com/the-realest-stu/Lilliputian)
