### ISSUE TITLE
Check top-field of multiblock for crafting catalysts

### ISSUE THREAD

**Issue by MrDj200** [CompactMods/CompactMachines#222]
Hey,
I don't get how to form a multiblock.
I build the Projectors and the walls and threw in Ender Pearls.
But nothing seemed to work.
Here are some Screenshots:
https://imgur.com/a/VsxeL

**Comment by davenonymous** [comment]
Hey, try throwing the pearl into one of the fields on the side of the multiblock.
The field on the top is not yet being checked ;)

**Comment by MrDj200** [comment]
.__.
I don't even...
How haven't I thought of this in 3 hours?!
Wow..

Thank you :/

**Comment by davenonymous** [comment]
Oww man, I'm sorry for wasting your time; that's on me. I should mention that issue somewhere until I fix it.

**Comment by MrDj200** [comment]
Nah. Just my Stupidity not thinking of such things :P
Thanks again :D
