### ISSUE TITLE
[1.12.1] FPS Decrease on CM Preview

### ISSUE THREAD

**Issue by UnPure** [CompactMods/CompactMachines#232]
While the Preview-GUI of a Compact Machine is open, the client FPS are starting to decrease.
If you look too long into a preview, the FPS will stay at a low level even after closing the preview.
The only way to solve this is to rejoin the world/server.

**Compact Machines:** 3.0.0-b134
**Forge:** 14.22.0.2485

**Comment by davenonymous** [comment]
I will investigate.
Edit: I can not reproduce this. Tested with a maximum size compact machine packed with about 50 enchantment tables and looked at it for about 10min. No change in FPS after time.
Any ideas how I could reproduce this issue?

**Comment by LeChuckXIV** [comment]
also experiencing this issue, normally get ~130-150 fps but when rendering this and exiting it it stays this low, i have a few TE cables and machines in here for ore processing.

https://i.imgur.com/i3uQKE0.png

version: 1.12.1-3.0.0-b135

**Comment by davenonymous** [comment]
Does the latest release on curseforge help with this issue?

**Comment by davenonymous** [comment]
I guess it does.
