### ISSUE TITLE
[1.12.1] Compact Machines are ignoring the World Border

### ISSUE THREAD

**Issue by UnPure** [CompactMods/CompactMachines#233]
On my server we have a worldborder 10.000x10.000.
A player created a new Compact Machine and spawned the room >5000 on X.
He is unable to place anything because he is outside the border.
Maybe the mod should check for worldborder and dont spawn a new box, or disable the worldborder for that dimension to solve this issue.

**Compact Machines:** 3.0.0-b134
**Forge:** 14.22.0.2485

**//edit:**
I just saw that the boxes are spawned with 1000 blocks distance between them.
Is there any reason for that? Why not 100 or less? That way even with a worldborder it should be hard to reach it.

Another way would be to circle them arround the start point.

**Comment by davenonymous** [comment]
I had it at 128 in CM1 and that was to little, so some things bled over to other machines, can't really remember what it was. So I went with 1024 to be on the safe side no matter what.

Also, changing the location machines generate their cubes would break existing worlds.
Preventing the world border from being changed in the CM dimension is a much cleaner fix.

**Comment by SizableShrimp** [comment]
While this issue is not completely fixed, pull request #439 adds 2-dimensional support to machine generation. For 10,000x10,000, this should be fine. However, I agree that the CM dimension should be updated to just remove world borders, although I don't know if this is feasible or not.
