### ISSUE TITLE
1.10.2 Crash Placing Machine Block with Lime Lib

### ISSUE THREAD

**Issue by scottosx** [CompactMods/CompactMachines#238]
An issue was discovered with CM3 which was apparently fixed according to this:
https://github.com/MrRiegel/LimeLib/issues/13

Could that fix be also applied to the 1.10.2 version? My world is crashing because of this (I think). I know you have moved on past this version but pretty please? I need both CM2 and Particle Spreader for my modpack.

Here is the log:
[crash-2017-10-21_14.16.18-server.txt](https://github.com/thraaawn/CompactMachines/files/1404401/crash-2017-10-21_14.16.18-server.txt)

**Comment by davenonymous** [comment]
Done. Build is ready to download on curse.
Enjoy.

**Comment by scottosx** [comment]
Thanks for the quick fix! Works now. You are an ace.

**Comment by davenonymous** [comment]
You are welcome. Glad that fixed it for you!
