### ISSUE TITLE
Config option for allowed worldgen dimensions

### ISSUE THREAD

**Issue by YOYOK9** [CompactMods/CompactMachines#239]
So just have a simple question, I am building a modpack and I am changing mods with "big"ish world gens to a world that will be reset often (mining world). So my question is, is there a way to tell CM3 to spawn cubes in a given dimension and not in dim0?

**Comment by davenonymous** [comment]
I will look into it and might add a config option listing allowed dimension ids.

**Comment by YOYOK9** [comment]
Sounds good
