### ISSUE TITLE
Advanced Tunnels

### ISSUE THREAD

**Issue by davenonymous** [CompactMods/CompactMachines#244]
Maybe allow 1:n connections instead of just 1:1 connections.
Not sure whether I want to support this yet.

**Comment by ruifung** [comment]
Wouldn't this be kind of difficult (and potentially confusing) when trying to map capability access from outside to inside?

**Comment by davenonymous** [comment]
Yes, we would need something that allows configuring the transfer mode, i.e. round-robin, distribute, priority based and so on.

**Comment by davenonymous** [comment]
I won't add this for now. Usually there are ways to handle this inside the machine using other blocks. Yes it would be nice, but it would also make all of this way more complicated and introduce a lot of corner cases, e.g. network-style capabilities (1 to all of them) would need to be handled differently than item-style capabilities (1 to one of them).
