### ISSUE TITLE
Allow ignoring meta-data in miniaturization recipes

### ISSUE THREAD

**Issue by Leftorius** [CompactMods/CompactMachines#246]
Hey I'm using that CompactMachine custom crafting recipe system to add a few new recipes (or at least, change some),

but If I use a block (for example Tech Reborn Computer Cube) it needs a specific position

https://imgur.com/a/1Y8Rx

is there an option to disable this or is this intended? Could it be added as optional?

**Comment by davenonymous** [comment]
I will add a way to disable metadata checking.

**Comment by davenonymous** [comment]
Here's an example on how this will work once released: [example-recipe.json](https://gist.github.com/thraaawn/8cd435d692467c6637ab4602443c2a30)
