### ISSUE TITLE
Add oredict support to crafting recipes

### ISSUE THREAD

**Issue by KAfable** [CompactMods/CompactMachines#247]
Would it be possible to have all types of metadata of a block or a ore dictionary of blocks be eligible for crafting? For example I'm planning on making custom recipes with Funky Locomotion Frames (to make it easier for the player to your in world crafting mechanic), but some frames have different orientations and metadata (eg if you don't want the frame to drag blocks along its west side). Is there a way to input that into the JSON?

**Comment by davenonymous** [comment]
If your want to ignore the metadata on a block you can add the "ignore-meta": true, flag to the corresponding input-type.
NBT is ignored by default. Oredict not supported atm.

edit: [example-recipe.json](https://gist.github.com/thraaawn/8cd435d692467c6637ab4602443c2a30)

**Comment by robotgryphon** [comment]
I am currently overhauling Compact Crafting (1.16+) to support more flexible block data in recipes. The repository is [here](CompactMods/CompactCrafting) if you want to keep an eye on progress.
