### ISSUE TITLE
Machines not staying linked.

### ISSUE THREAD

**Issue by SayntCigol** [CompactMods/CompactMachines#248]
Machines that are placed it dimensions other than the overworld are not staying linked with the correct "internal" locations.  Re-entering a machine not placed in the overworld will only link temporarily.

**Comment by davenonymous** [comment]
I can not reproduce this.
What I tried:
1. Place and enter a few CMs so we don't start at internal coords 0.
2. Place CM in the nether
3. Enter it, place a few blocks
4. Leave it and check with a right click that everything is fine
5. Stop the Server/World
6. Reconnect to the Server / Start the World
7. Check whether the machine is still bound to the proper location

That works fine for me. What do I need to do differently to reproduce this issue?

**Comment by robotgryphon** [comment]
Going to mark this as needing verification due to lack of user response and stale dating. Will evaluate in the CM3 branch if the issue can be reproduced in the latest build. If so, we can reopen.
