### ISSUE TITLE
[1.12.2] Can't seem to place tunnels

### ISSUE THREAD

**Issue by FnordMan** [CompactMods/CompactMachines#250]
I right click on the compact machine (maximum size in this case) and get a big spinning block, I try to right click again and nothing happens, the tunnel doesn't get used (have 8 in hand) and nothing on the big spinning cube changes.

**Comment by davenonymous** [comment]
The tunnels are meant to be used on the inside walls of the machine.

**Comment by FnordMan** [comment]
You may want to indicate that in the Personal Shrinking Device then..
