### ISSUE TITLE
Some way of Biome Control

### ISSUE THREAD

**Issue by davenonymous** [CompactMods/CompactMachines#251]
Maybe a way to lock the current biome?

**Comment by Saklad5** [comment]
Alternatively, you could make the biome change based on the current location of the Compact Machine, with a default biome while it isn’t placed. I know Extra Utilities 2 has a biome-changing mechanic, and it doesn’t seem to break anything.

Speaking of which, that’s my current solution to biomes in Compact Machines. You could just make a Compact Machine biome and leave the rest to mods like that.

**Comment by NateKDavis** [comment]
Should the biome of your compact machines be changing everytime you move the compact machine?

**Comment by robotgryphon** [comment]
Going to close this as biomes have changed heavily in 1.16+, and the generation now uses a single biome. Biome changing commands and upgrades are being drafted for 1.18.
