### ISSUE TITLE
Unable to consistantly break machine walls

### ISSUE THREAD

**Issue by RacerDelux** [CompactMods/CompactMachines#258]
In ATM3 3v5.1 the walls do not break consistently.

**Comment by RacerDelux** [comment]
nevermind, you just need to use shrinking device,.

**Comment by davenonymous** [comment]
Why do you even want to break them? What reasoning do you have?
I might remove the possibility of breaking the walls completely, since I don't want any issues like this one regarding that.

**Comment by RacerDelux** [comment]
@thraaawn Please don't do that! I had to break them to destroy portals from the portal gun mod. They were glitching out on the compact machine wall blocks and causing fps drops. In addition, they were not removing themselves on creation of a new portal. Only way to fix that is to destroy the block they are under to remove them.

I just could not find any information on how to break the blocks, finally figured it out after a while. If the blocks had indeed been unbreakable, I would have had to abandon that compact machine.
