### ISSUE TITLE
ATM3 with portal gun - portal dupe issue

### ISSUE THREAD

**Issue by RacerDelux** [CompactMods/CompactMachines#259]
Using a portal gun on the compact machine walls causes the portal to dupe and bug out.

**Comment by davenonymous** [comment]
What does "causes the portal to dupe" mean?
What kind of walls are you talking about? The solid ones or the craftable ones?

**Comment by RacerDelux** [comment]
It is the compact machine walls inside the compact machine. I am honestly not 100% sure which mod is at fault, but I can say with certainty that when a portal was on the machine walls (the unbreakable walls), it bugged out like no other, but if I put some dirt and then the portal on the dirt, it was fine.

**Comment by davenonymous** [comment]
This seems to have nothing to do with Compact Machines.
Using the Portal Gun in the Nether has the same effect.

![2017-11-26_13 54 02](https://user-images.githubusercontent.com/205210/33240125-4b48345c-d2b1-11e7-8d7c-92d93a8e9f68.png)

Please open an issue in the [Portal Gun issue tracker](https://github.com/iChun/IssueTracker-PortalGun/issues).
