### ISSUE TITLE
duping glitch with portal gun

### ISSUE THREAD

**Issue by juryjr** [CompactMods/CompactMachines#260]
if your  compact macheen are picked up with a portal gun it drops a block version and u  also keep the original

**Comment by davenonymous** [comment]
I will look into this. The way I'm dropping machines on break is a bit weird and I can't fully remember why I did it the way I did back then - that code is a relic from the 1.7.10 times. 🐛

**Comment by davenonymous** [comment]
I can not reproduce this, the portal gun is blocking me from picking up the machine in the first place.
