### ISSUE TITLE
AE2 cables not connecting

### ISSUE THREAD

**Issue by jp-bennett** [CompactMods/CompactMachines#264]
In the latest version of the Modern Skyblock 2 pack, which is using Compact Machines 3.0.3, AE2 cables aren't connecting into a compact machine correctly.  I have the tunnel configured to face the correct side, and the tooltip even indicates that it is working as an ae2 bus/cable.  I've tried fluix cables as well as smart buses.  They don't visually connect or show up on the network.

**Comment by davenonymous** [comment]
AE2 does not work directly with Compact Machines. But you can use the [ME Capability Adapter](https://minecraft.curseforge.com/projects/capability-adapter) to bridge the tunnels. Just place on one both ends. It is included in the pack if I remember correctly.

Have fun!

**Comment by jp-bennett** [comment]
Thanks for the info!  That seems to be working.
