### ISSUE TITLE
Compact machine | Crash on enter + unusable + AE2 incompatible? |

### ISSUE THREAD

**Issue by RealLith** [CompactMods/CompactMachines#267]
running modpack: awakening 1.16.4
mod version: compactmachines-1.7.10-1.21

When i tryed to enter a compact machine (max size) i crashed. When i logged back into that server (multiplayer), i Had 2 stacks of weird blocks out of no were. they were 'Matrix frame' from AE2. those blocks suppost to be impossible to get. ALSO then I was there, i was unable to move, i was stuck in the 1x1x2 space. 
I exited the machine, replaced it and after i entered - crashed once again. But this time I cant log back in. Every time i try to log into the server, i get CTD (Crash to destop).

Crash report:
https://pastebin.com/Q7NikQqe

**Comment by davenonymous** [comment]
Sorry, I ain't got the time to support the 1.7.10 version anymore.
