### ISSUE TITLE
[feature request] Integrated dynamics support with tunnels

### ISSUE THREAD

**Issue by masonpinder** [CompactMods/CompactMachines#268]
Could integrated dynamics cables be added into the functionality of the tunnels?

Integrated dynamics already has a way to send the cables through dimensions, like Applied Energistics 2 has, so would it be feasible to add in piping integrated dynamics pipes through the compact machines and out? Thank you in advance! If power and item transport can be put through tunnels, why not allow redstone using integrated dynamics?

I am pretty sure that integrated dynamics has a modding API, so it wouldn't be too impossible to just get what the omni-directional connector and make a tunnel do the same tile ticking, with just connecting it only through the sides

**Comment by davenonymous** [comment]
See https://github.com/CyclopsMC/IntegratedDynamics/pull/419
