### ISSUE TITLE
[1.12] Metadata for catalyst

### ISSUE THREAD

**Issue by Jomik** [CompactMods/CompactMachines#269]
I can't seem to find a way to specify the metadata for a catalyst item...

I've tried a few:
`"catalyst": "appliedenergistics2:material:23"`
`"catalyst": { "id": "appliedenergistics2:material", "meta": 23 }`

**Comment by Jomik** [comment]
Oh, but digging in the code I found that there's a key called "catalyst-meta" 👍

**Comment by davenonymous** [comment]
Jupp, sorry, I should document this better.
