### ISSUE TITLE
[Bug] Making wall breakable: Invalid block Air

### ISSUE THREAD

**Issue by smithnc07** [CompactMods/CompactMachines#271]
MC Version: 1.12.2
Forge version: 1.12.2-14.23.1.2560

When I try to craft the breakable wall parts I have what I believe is the correct setup: 4 projectors facing each other with a 3x3 open space in the middle. when placed, I see a orange overly of one block in the center. 
I placed an iron block with redstone on top, and as far as I understand thats the correct layout, however, it gives me the error message: Invalid block Air (As seen below)

![breakablewall](https://user-images.githubusercontent.com/1372154/33667110-8ad348b6-da61-11e7-904d-c2dc3797b0eb.png)

As far as the other recipes using the projectors, if I cheat in the wall blocks, then Im able to make the machines just fine. Its just this first one thats giving me trouble.

**Comment by davenonymous** [comment]
You can not craft a 1x2x1 recipe in a 1x1x1 area. There are currently no 1x1x1 recipes.
Increase your crafting area size and you are good to go.

**Comment by smithnc07** [comment]
And I'm a dork. Yup, Sorry about that. I feel silly..
