### ISSUE TITLE
Direwolf20 1.12 v1.2.0 Crash When TE Tank Placed On Up Face of Compact Machine

### ISSUE THREAD

**Issue by XVicarious** [CompactMods/CompactMachines#273]
When I placed a Thermal Expansion tank on top of a compact machine the game crashes. When I log back in the tank is there with no issues (it outputs to the tank properly).

[crash.txt](https://github.com/thraaawn/CompactMachines/files/1536917/crash.txt)

The mod version is 3.0.3-b169

**Comment by davenonymous** [comment]
I can not reproduce this. What was on the other side of the tunnel?

**Comment by XVicarious** [comment]
A fluidduct. I have since updated the dw20 pack so I'll test this out again
when I get home.

**Comment by XVicarious** [comment]
I reproduced it again with DW20 1.4 (CompactMachines 3 version 3.0.3-b169).  This time it was an itemduct inside the machine.  This was on the up face, and I did it again on the west face.

**Comment by kevintok** [comment]
Happens to me on all face. I haven't placed any tunnel yet.

**Comment by davenonymous** [comment]
This has probably been fixed in 3.0.5
