### ISSUE TITLE
Feature Request: Chunkloading and Performance improvement

### ISSUE THREAD

**Issue by Xiaminou** [CompactMods/CompactMachines#275]
I intend to use Compact Machines to optimize my world in order to reduce both TPS and FPS lag, in order to get the best out of it I would require a way to decide which Compact Machine is chunkloaded and which isn't that can be changed at the flick of a switch.
As I understand it you can transmit redstone signals from outside a Compact Machine to inside so applying a redstone signal directly to the Compact Machine Block is not an option.
My suggestion is to add a block, a functionality or even a config option that changes what chunkloads the machines, for example you could add a block that when placed adjacent to a machine and powered on by a redstone signal chunkloads the machine, when the redstone signal is turned off the machine is no longer chunkloaded.
You could even imagine adding a cost to keeping that machine chunkloaded such as Energy, Items or Fluids.

**Comment by davenonymous** [comment]
No, sorry. Chunk loading will stay the way it is. Don't want to overcomplicate this more for a very specific and rare usecase.
