### ISSUE TITLE
Tunnels refuse to let items pass in either direction

### ISSUE THREAD

**Issue by uehlbran** [CompactMods/CompactMachines#276]
I'm playing direwolf20 1.12.2 pack and have tried  multiple mods ranging from Refined Storage (I know it doesn't work), and Extra Utilities 2 and I can't send items in or out of the compact machine. What modes work with compact machines? How the hell do you get items in and out? EU2 cables do connect but don't work.

**Comment by davenonymous** [comment]
Refined Storage should work actually.
Things you might have missed:
- Configure the proper side on the tunnel block
- Be sure there is something on the other side of the tunnel that can accept items, e.g. a chest.
- Use Hoppers, Itemducts, EU2 pipes, Export Buses, whatever is able to insert items into chests. They should all work.

**Comment by uehlbran** [comment]
I got it kind-of working. I was connecting pipes to the  compact machine block and that wasn't working, but setting a chest next to it did. Cables connected to it don't work though for some reason?

I can't get RS to work though. The cables wont connect to the compact machine block or tunnel.

**Comment by davenonymous** [comment]
That fully depends on how the cables are implemented. It's basically like this: If it's a cable you can not Hopper into, it won't work through tunnels.

Update the pack or the mod to the latest version to visually see the RS connection working, i.e. see RS cables connecting to the block. Besides that it fully works - if you use full size blocks at the tunnel and the machine you won't know the difference.
