### ISSUE TITLE
Using RS inside of compact machines corrupts your world

### ISSUE THREAD

**Issue by uehlbran** [CompactMods/CompactMachines#277]
After creating an a compact machine, putting a refined storage cable inside connected to a tunnel (it didn't look connected), and teleporting out compact machines has caused my game to crash every time it loads the world. Error message just says an game crashed while tesselating block in world.

Tried removing compact machines and issue still occurs. Not sure if this is just a coincidence but I'd say compact machines and rs are not compatible and should be avoided.

**Comment by davenonymous** [comment]
Upload the full crashlog to pastebin, please.

**Comment by davenonymous** [comment]
I've been using RS together with CM3 for a while now without any issues.
Closing.
