### ISSUE TITLE
unable to make maximum machine. max recipe returns Giant machine

### ISSUE THREAD

**Issue by BrewingCoder** [CompactMods/CompactMachines#278]
98 casings, 1 diamond block, projectors report = giant machine. results = giant machine
98 casings, 1 emerald block, projectors report = giant machine. results = giant machine

config and JEI show that the emerald block should allow one to build a max machine.

Version:  3.0.3-b169

**Comment by davenonymous** [comment]
weird. will look into this!

**Comment by davenonymous** [comment]
Even weirder, I can not reproduce this:
![2017-12-17_10 36 47](https://user-images.githubusercontent.com/205210/34078221-3fdcbb68-e316-11e7-86e2-08e60f5731b0.png)

The projectors report "maximum machine" and it's also the result i'm getting when i start the crafting.
What modpack is this? This issue has been mentioned several times, but I've never seen it myself. Any additional info you can provide would be helpful 👍

**Comment by JojoIdiot** [comment]
Can confirm. Using DW20 1.12 1.40 pack containing CM3 3.03-b169.jar. Not sure about earlier versions of pack, as I just started messing with your mod.

Both diamond block and emerald block produce Giant Compact Machine.

**Comment by BrewingCoder** [comment]
I'm using a custom pack, but it's on Curse.  Called BrewTech12.    I can upload a video of the process if you want to see it.

**Comment by BrewingCoder** [comment]
I was able to determine exactly what circumstances cause this issue.

recipe:  

![image](https://user-images.githubusercontent.com/6723474/34176066-9abfcc0c-e4cc-11e7-8331-2246d5143733.png)

nowhere does the JEI recipe explain that your code expects the emerald block on Y axis 3 of the multiblock.  I've always put it on the inside floor (Y axis 2) of the hollow multiblock.  

When I looked at the recipe.json for the max machine I noticed that the emerald block was expected in the center.

If you  place the emerald block on the floor, or off by 1 position in any direction, you get a large, not a maximum.

I just successfully made a maximum machine by suspending the emerald in the center of the hollow multiblock.

**Comment by BrewAndCode** [comment]
I just successfully made a maximum machine by suspending the emerald in the center of the hollow multiblock.

**Comment by davenonymous** [comment]
Ah, I see. You can press "shift" to see a wireframe of the recipe.
I'll add a tooltip or something to explain this on the JEI page. Would that work for you?

Edit: The wireframe is still a bit hard to read I think. Maybe I can find a better way.

**Comment by BrewingCoder** [comment]
sure, but that doesn't correct the bug that a giant machine is returned.  I mean -- I don't have a diamond block in there; and when I do I place it on Y axis 2 just like I was attempting to do with the Maximum.

**Comment by davenonymous** [comment]
Fixed in 4e0b1d0
