### ISSUE TITLE
Chunk Loading Stopped Working

### ISSUE THREAD

**Issue by scotty9090** [CompactMods/CompactMachines#281]
Minecraft: 1.12.2
Forge: 14.23.1.2566
Compact Machines: 1.12.2-3.0.3-b169
Chicken Chunks: 1.12.2-4.0.70-universal

My mob farm in a giant compact machine has been working fine the whole game then suddenly stopped chunk loading (nothing coming out until I enter the machine and then things start working, then stops again when exiting machine.)  The compact machine itself is chunkloaded in my base using Chicken Chunks.  The configs are set to the default (forceLoadChunks=false).

Two things I did prior to this happening:  1) added more spawners / grinders to the existing giant compact machine.  2) built a second compact machine to handle XP drops and placed it in the overworld.  Not sure if either of these had anything to do with this but thought I'd mention since they were in close proximity.

I manually chunkloaded the machine by placing a chicken chunk spot loader in the machine and that seems to resolve the problem.

**Comment by davenonymous** [comment]
Have you tried completely un-chunkloading the actual machine, i.e. remove all chunk loaders, leave the area and let the game run for a small while until your base is not chunkloaded anymore.
Then come back. Is the chunkloading working then?

**Comment by scotty9090** [comment]
Sorry for the delay, didn't want to un-chunkload my old base.  I've started a new game and just had the issue re-occur - i.e. initially working fine then suddenly stopped producing mob drops - and tested as above.  Here's what I did step-by-step:

1. Observed no drops exiting the mob farm machine as before (okay when I was inside, stopped as soon as I exited.) 
2. Removed my only chicken chunk loader in my base.
3.  Visited the mining dimension and the deep dark for a good amount of time.
4.  Returned to my base - mob farm machine still not producing drops.
5.  Entered machine, then exited - no drops exiting machine once I left.
6.  Re-entered and placed a chicken chunk spot loader and everything is good when I exit.

As before, this happened sometime after placing additional compact machines, but I forgot to immediately check so I don't know if this is coincidental or correlated.  Please let me know if there's anything else I can test or information I can provide.

**Comment by Leosky** [comment]
I've the same issue in the Forever Stranded Lost Souls modpack. The compact machine unload almost instantly when i leave it what ever i try.

**Comment by ktole1999** [comment]
if you build it outside of compact machines does it still stop or does it continue?

**Comment by Zaazu** [comment]
Hi,

Also having the same issue, compact machines used to work fine but have since became unloaded.

I've got a few compact machines with mob spawners in, getting no drops when I leave the machine, but drops will continue while I'm inside. Placing down a chunkloader in the machine itself will keep it chunkloaded when I'm not inside the machine.

Does anyone know any other workaround?

Thanks

**Comment by robotgryphon** [comment]
Multiple versions released since the last comment; closing as stale until verified on b278.
