### ISSUE TITLE
Question re: Redstone Tunnels

### ISSUE THREAD

**Issue by scotty9090** [CompactMods/CompactMachines#283]
Are Redstone Tunnels intended to be input (into the compact machine) only?  Or is do they permit a signal to be transmitted from within the machine to the outside?  

I'm trying to use one of these to contain a vanilla redstone circuit and can transmit a signal into the machine fine, but don't seem to be able to read the output (on a different face).  I have tunnels set on both the input and output walls.  Am I doing something wrong or is this not supported?

**Comment by davenonymous** [comment]
Did you set the Redstone Tunnel to "Output" mode (which is a green square in the top right corner, instead of a red square)?

From the Readme:
> They (Redstone Tunnels) are also not bidirectional, i.e. you have to specify whether it is an input or an output tunnel. You can change their mode by hitting the colored indicator square in the top right corner.

**Comment by SimulatorSia** [comment]
I can't get raw redstone to work through the tunnels at all, neither in or out. 1.12.2

**Comment by scotty9090** [comment]
I totally missed the input / output mode.  However, I still can't get it to work even when (properly I think) setting it to output mode.  Here's what I have:

Inside the machine:
Redstone Tunnel attached to one wall, set to output (green symbol, shows "Output" in WAILA), set to North face.
Lever -> redstone dust -> redstone tunnel (set as above).

Outside the machine:
Redstone dust on the floor adjacent to the North face (I tried it on all of the faces just to make sure.)  Nothing lights up.

Input mode continues to work fine.  I appreciate the help.

**Comment by scotty9090** [comment]
Pulled the latest update, works perfectly now.  Thank you.  These are a great way to shrink down ugly vanilla redstone contraptions.

**Comment by davenonymous** [comment]
You are welcome. Happy it works for you now!

**Comment by mindbound** [comment]
Sorry for necroposting! It seems that 1.12.2 latest isn't able to transmit redstone signals through the tunnels using Project Red wires. Is this a known issue?
