### ISSUE TITLE
can't get Redstone Tunnels to work

### ISSUE THREAD

**Issue by SimulatorSia** [CompactMods/CompactMachines#284]
Do they work with regular redstone? I can't get a lever or any redstone signal to enter the machine from any angle. Input and output.

**Comment by davenonymous** [comment]
Yes, they should. Please try to provide more information, can't really help you with "it does not work".

**Comment by SimulatorSia** [comment]
Nvm, I got it to work, it was just a block updating issue but after I updated to the latest forge, it fixed itself. Thank you
