### ISSUE TITLE
RF bouncing between two ducts connected via Tunnel

### ISSUE THREAD

**Issue by mrlamb** [CompactMods/CompactMachines#285]
Was tracking down power usage throughout my base when I discovered an oddity. The Thermal Expansion multimeter when used on a fluxduct headed into your compact machine was reporting a usage of around 600rf/t with nothing connected inside. that should be drawing power.

Screenshot: https://www.dropbox.com/s/7te3gj6zrjk7135/Screenshot%202017-12-30%2000.15.09.png?dl=0

With a fluxduct on each side of the tunnel there's a constant draw of 617rf/t and as the screenshot shows, the cell on the inside is full with nothing connected to it.

Edit: some further information. The 617rf/t number is indicative of the difference on the line going into the machine and what's used elsewhere on that line (our Refined storage system sucking up 383 rf/t). A leadstone fluxduct feeds this line at 1krf/t which sends some to each. Now on the inside of the machine if I hook up a battery cell directly to the tunnel the extra draw does not happen. Whatever seems to be making this happen might be strictly related to having a fluxduct on each side. Perhaps the fluxduct's inherent capacitance is involved somehow?

**Comment by davenonymous** [comment]
I assume the unused energy is bouncing between the two ducts.
It is generally recommended to have a buffer block (energy cell, chest, tank...) on either the in or the outside of the machine, but it should not be necessary.
You are not actually losing power, are you?

**Comment by mrlamb** [comment]
That's a great question and bears more investigation. I had isolated that power segment by itself with a one way like into the machine and it read as a constant draw. I'll test in creative a bit with a finite energy source and get back to you on that.

**Comment by mrlamb** [comment]
Great news. There's no energy loss. So this is merely an informational misrepresentation and nothing to worry about. If anyone else notices this problem a simple solution is to partition any power network going into your compact machines so as to prevent your overall power network from reporting more usage then it actually is. 

Of course I may be the only one who actually bothers to pay close attention to the numbers like this anyway!

Thanks for commenting and pointing me towards further investigation.

**Comment by robotgryphon** [comment]
Closing this as stale due to the issue seeming to be resolved; please reopen if this is an issue in b278.

**Comment by SizableShrimp** [comment]
I can almost 100% confirm that this issue would still be present on b278 without testing. This is a simple side effect of the way forge capabilities work and how Thermal's fluxducts work with these capabilities. A similar issue appeared with EnderIO's energy conduits which tried to traverse the entire network and caused a `StackOverflowException`, given enough time. Without major refactoring and phasing out capabilities (which is already a bad idea), this is something that mindful mod developers must account for, or maybe it might be possible for CM3 to detect this? Not sure right now. Here's the relevant commit in the EnderIO repository: https://github.com/SleepyTrousers/EnderIO/commit/d8f465656aed384318277323d57efeccd20f1323
