### ISSUE TITLE
invalid block in field area

### ISSUE THREAD

**Issue by Brandon85c** [CompactMods/CompactMachines#287]
set up a set of projectors to put 1 iron block and a redstone ontop and it says invalid block in field area like it's not the right redstone iv'e already tried to use a block of redstone

the field goes away the moment i put the redstone ontop of it and when i throw the redstone at it it does nothing i don't get the error msg till i click a projector
http://prntscr.com/husu16

on ftb revolation

**Comment by davenonymous** [comment]
You are trying to craft a 1x2x1 recipe in a 1x1x1 crafting area.
