### ISSUE TITLE
Placing TileEntities near a CM with a Tunnel crashes the game

### ISSUE THREAD

**Issue by soleluke** [CompactMods/CompactMachines#288]
When placing both the Chemical Injecting Factory and Purification factory (possibly more, those are the only two I have tested) from Mekanism next to a compact machine face that is outputting gas, client crashes. Tested with two tiers of factory as well as non-factory version of the Mekanism blocks, also tested with two sizes of compact machine.

The block is still placed (at least when playing SMP)

Modpack: All The Mods 3 version 5.6

Replication process: place Chemical Injecting Factory on the face of any compact machine which is outputting hydrogen chloride. Does not occur if the compact machine is placed after the Mekanism block

Crash report: https://pastebin.com/tyVZax9s

**Comment by npgx** [comment]
actually, this happens whenever a machine (or some tileEntities like energy cells) is positioned near a compact machine and that side of the machine is connected on the indside with a type of conduit or tileEntity that is compatible with the machine itself
for example: if you place an energy cell the game will crash if on the other side is connected a fluxduct, a chemical dissolution chamber will crash if on the other side there is a fluid/item/energy conduit, at least as i saw, prease rename the issue to be accurate

this does not happen if the face of the compact machine doen not have a tunnel connected to it

**Comment by davenonymous** [comment]
I can not reproduce this and need more information.

Here's how I tried to reproduce this:
![2018-01-04_16 21 30](https://user-images.githubusercontent.com/205210/34570241-643f9968-f16b-11e7-8b2c-6a754085eaec.png)

Placing down an energy cell on the "up" side of the machine does not crash the game, but instead it receives power from the energy cell on the inside through the fluxduct.

**Comment by davenonymous** [comment]
Aha! This only happens on Server worlds and then just crashes the client.
Fix was easy enough.

Thanks for the report!
I'm releasing a hotfix version 3.0.5 as I'm typing this.
