### ISSUE TITLE
Game crash when looking inside (right clicking) Botania only Compact Machine

### ISSUE THREAD

**Issue by ockerspock** [CompactMods/CompactMachines#289]
It only happens on the compact machine containing Botania, the report seems to suggest something to do with the mana pool.
So basically I have had this occur a number of times, now its accidentally right clicking as I've stopped using the function intentionally. It occurs every time and only on the one machine, I have 7. The crash report is ************
The game crashed whilst ticking block entity
The game crashed whilst ticking block entity
Error: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class vazkii.botania.api.state.enums.PoolVariant, values=[DEFAULT, CREATIVE, DILUTED, FABULOUS]} as it does not exist in BlockStateContainer{block=minecraft:stone, properties=[variant]}

**Comment by davenonymous** [comment]
Hey, thanks for the report.
You can disable the TileEntity rendering clientside in your compact machines 3 config until I've fixed this, so you won't crash anymore.

**Comment by davenonymous** [comment]
I can not reproduce this - pools are being rendered, spreaders are not, but no crashes at all:
![2018-01-06_10 06 09](https://user-images.githubusercontent.com/205210/34638322-737658d6-f2c9-11e7-98d4-db695d90c09b.png)

Please read [this](https://vazkii.us/br101/) and provide me screenshots of your setup, i.e. at least the inside of the compact machine that's crashing you.

**Comment by ockerspock** [comment]
Playing DW20 modpack v1.4
Compact Machines v 1.12.2-3.0.3-b169 (btw just started the game to take the screenshot and accidentally clicked and crashed) 
Forge v 14.23.1.2566
There's a vanilla forge?
No Optifine

Maximum Machine & 9 mana pools, generation by 10 or so endoflames
I don't know if the image is added by dropping, trying selecting sorry if you get 2 copies
When you tested did you have mana in the mana pools? 

Thanks for looking at this and thanks for the mod, I am enjoying it. Also wondering what will happen when I put my 10 compact machines inside an ELEVENTH compact machine?

![2018-01-07_02 26 34](https://user-images.githubusercontent.com/9971064/34641135-4b29cd24-f353-11e7-8155-1856ff73f24d.png)
![Uploading 2018-01-07_02.26.34.png…]()

**Comment by davenonymous** [comment]
Could you try upgrading the mod to the latest version? I've changed quite a bit regarding the machine view.

**Comment by ockerspock** [comment]
That fixed it, thank you

**Comment by davenonymous** [comment]
You are welcome!
