### ISSUE TITLE
Coloured connectors

### ISSUE THREAD

**Issue by duncanwebb** [CompactMods/CompactMachines#290]
Would it be possible to have the faces of the machine cube colour coded so for example the connector on the west face is red and blue on the east face, etc. 

Awesome mod!

**Comment by davenonymous** [comment]
TOP/Waila shows which face you are looking at.
You'd then also need a legend that tells you which color is which face. It wouldn't help much.

**Comment by duncanwebb** [comment]
May be I didn't explain this properly, I can remember colours much better than names and I'm sure the same applies to non native English speakers. This is what I was thing about:
![coloured connectors out](https://user-images.githubusercontent.com/4198031/34649250-720610d0-f3ab-11e7-94e1-a831fd3c0c5b.png)
![coloured connectors in](https://user-images.githubusercontent.com/4198031/34649251-721c4a4e-f3ab-11e7-824d-3b64b2c7efeb.png)
