### ISSUE TITLE
Tool to move the machines

### ISSUE THREAD

**Issue by duncanwebb** [CompactMods/CompactMachines#291]
It can be a big mess if a completed machine is broken. It would be nice to either move the machine with a tool or keep the contents when it is picked up.

**Comment by davenonymous** [comment]
1.7.10? Upgrade it with a nether star (or whatever is configured in your world to act as upgrade item) so you can move it.
1.10.2 or newer? You should be able to move it without issues.

**Comment by duncanwebb** [comment]
Thanks that's great, didn't know this.
