### ISSUE TITLE
Quantum Entangler gone? 1.12.2 3.0.4

### ISSUE THREAD

**Issue by loveliss** [CompactMods/CompactMachines#293]
I know in earlier versions of Compact Machines we had an item called a Quantum Entangler. It allow us to link same size compact machines with each other so you can basically teleport into multiple same size machines but it would be the same "world" inside each. Is there something like this or will there be for this newer version?

**Comment by davenonymous** [comment]
No, sorry, won't be coming back.

**Comment by landpointpro** [comment]
is there a way to make bigger from 13x13x13?

**Comment by SizableShrimp** [comment]
No, this is not possible and probably won't ever be as I described in the other thread you asked this in. If you really want this, just go into creative, pull out a Personal Shrinking Device (PSD), and break all the blocks around you in creative with the PSD in hand to break them. Then, you can break the barrier blocks. This is the only way I see it being possible currently as the mod creator is inactive.
