### ISSUE TITLE
Build machine before compacting

### ISSUE THREAD

**Issue by tod** [CompactMods/CompactMachines#294]
It would be cool if there was an option to require someone to build the machine *before* compacting it. Then also have a config option that doesn't allow a person to enter the machine while it's compacted. If you need to "fix" something inside, you would need to un-compact it first, edit it, then re-compact it.

**Comment by davenonymous** [comment]
Hmm. That would require me to rewrite lots of the mod. And it would deter many people from actually using one as shrinking/enlarging would be a major nuisance.
It might be interesting for expert modpacks, but the effort required to implement this AND the original way is just to much.

-> Sorry, won't be happening.
