### ISSUE TITLE
[1.12.2] JEI Rendering

### ISSUE THREAD

**Issue by KAfable** [CompactMods/CompactMachines#295]
**JSON**: https://hastebin.com/icabeloyol.json

**Issue:** Using Iron Chests doesn't render in JEI display, despite the recipe being recognized and working correctly ingame. 

![image](https://user-images.githubusercontent.com/26587049/35169490-b642c0ee-fd2a-11e7-9ec8-627b8c3d156f.png)

**Comment by davenonymous** [comment]
This is on my Todo list. TileEntities in recipes don't render yet.
Will prioritize higher. 👍

**Comment by davenonymous** [comment]
Progress:
![2018-01-20_17 35 10](https://user-images.githubusercontent.com/205210/35185664-56f83824-fe08-11e7-8dde-455c7709e374.png)

Not quite there yet and the code needs cleanup.
