### ISSUE TITLE
Crash to desktop when attempting to view a Compact Machine that contains a Draconic Evolution grinder and a Flux Networks Flux Point

### ISSUE THREAD

**Issue by Maxwell-lt** [CompactMods/CompactMachines#298]
## Base information
* Minecraft version: 1.12.2
* Mod version: 3.0.6-b192
* Minecraft Forge version: 14.23.1.2604

### Mod List
| Mod | Version |
|--|--|
| BrandonsCore | 2.3.7.140 |
| CodeChickenLib | 3.1.5.331 |
| compactmachines | 3.0.6-b192 |
| Draconic-Evolution | 2.3.8.279 |
| flux-networks | 3.0.3 |
| RedstoneFlux | 2.0.1.2 |
| sonarcore | 5.0.5 |

## Crash report

https://paste.ee/p/0lOuj

## Steps to reproduce
1. Place a Compact Machine
2. Enter the Compact Machine with a Personal Shrinking Device
3. Place a Draconic Evolution Mob Grinder
4. Place a Flux Networks Flux Point against the Grinder
5. Exit the Compact Machine
6. Right-click the Compact Machine to view the interior

### What is expected to happen
The interior of the Compact Machine appears as a window on the screen, letting you see what it contains.
### What actually happens
The client crashes to desktop, though the server is unaffected if not in SP.

**Comment by davenonymous** [comment]
Thanks for the detailed report. That helped a lot tracking down the bug!
This will be fixed in the next release!
