### ISSUE TITLE
Field Projectors caused client crash in FTB Revelation 1.2.0

### ISSUE THREAD

**Issue by GeneralDisorder** [CompactMods/CompactMachines#299]
I repeatedly experienced a crash today after trying out Compact Machines 3. I used the field projectors to craft one of the compact machines, entered it, and left it. As soon as I left my client crashed, and on every login thereafter I crashed with the same message. By using the crash report to get coordinates, an op was able to remove each offending field projector, and each projector kept crashing my client even though another had been removed.
When all the projectors were removed, I was finally able to log in without crashing.

Crash log attached
[compactmachinescrash.txt](https://github.com/thraaawn/CompactMachines/files/1692318/compactmachinescrash.txt)

**Comment by davenonymous** [comment]
Please always test with the latest version of the mod.
This has probably already been fixed with the 3.0.5 update.

**Comment by GeneralDisorder** [comment]
I can't recreate the problem in the latest version, so you're probably right. Thanks.

**Comment by davenonymous** [comment]
Awesome!
