### ISSUE TITLE
More detailed description for miniaturization setup

### ISSUE THREAD

**Issue by blockbreaker1361** [CompactMods/CompactMachines#300]
It would be really nice if the manual in the shrinking device had a detailed description of how to setup the field projectors. All you need to do is say how far apart the blocks need to be. The arrows never seem to stay on long enough to help out and it gets frustrating.

**Comment by davenonymous** [comment]
You are absolutely right, the current in game documentation about this is just horrible. Sorry!
Improvements on this are planned for the next release.
