### ISSUE TITLE
Can't make new worlds with compact machines and a Cubic chunks world type.

### ISSUE THREAD

**Issue by border999** [CompactMods/CompactMachines#301]
compactmachines3-1.12.2-3.0.6-b192
1.12.2-forge1.12.2-14.23.1.2610
I am not using Optifine
http://jenkins.daporkchop.net/job/CubicChunks/
**Steps to reproduce:**
1. Have both Compact Machines and Cubic Chunks installed.
2. Load up and attempt to generate a world on normal with cubic chunks option set to yes.
3. Look at log and watch it stall out at some percentage of world gen completion.

**Comment by davenonymous** [comment]
Try disabling Compact Machines world gen in its config. Does that help?

**Comment by border999** [comment]
Compact Machines and Cubic Chunks as the only mods, with the suggested alteration to the config. World generated fine. I will still suggest that you look into why that occurs.

**Comment by davenonymous** [comment]
I will. My WorldGen code needs some cleanup anyway :)
Thanks for the report.

**Comment by border999** [comment]
not sure why you reopened if this has been in some manner resolved.

**Comment by davenonymous** [comment]
> > I will still suggest that you look into why that occurs.

> I will. My WorldGen code needs some cleanup anyway

**Comment by border999** [comment]
Fair enough, I understand the need for a reminder.

**Comment by robotgryphon** [comment]
Need to verify on latest version. Closing for now as the last version tested is at least 7 versions behind latest.

**Comment by border999** [comment]
seems to be fixed
