### ISSUE TITLE
Itemducts between two compact machines don't work

### ISSUE THREAD

**Issue by UncleOwen** [CompactMods/CompactMachines#304]
Hi,

I'm using

Minecraft 1.12.2
Forge 14.23.2.2615
compactmachines3-1.12.2-3.0.7-b197.jar
ThermalDynamics-1.12.2-2.3.10.4-universal.jar
ThermalFoundation-1.12.2-2.3.10.6-universal.jar
CoFHWorld-1.12.2-1.1.1.12-universal.jar
CoFHCore-1.12.2-4.3.10.5-universal.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
CodeChickenLib-1.12.2-3.1.5.331-universal.jar

No Optifine installed, no other mods.

I have two Normal Compact Machines. The two are connected with Impulse Itemducts. Inside each CM is a chest, connected to the outside world via a Tunnel and more Impulse Itemducts. One of the chests has a Resonant Servo attached. I would expect that items placed in this chest are moved to the other chest - but they are not.

Some ASCII-Art in place of a screenshot:

```
+-------+     +-------+
|       |     |       |
|       |     |       |
|       |     |       |
|   CIIITIIIIITIIIC   |
|       |     |       |
|       |     |       |
|       |     |       |
+-------+     +-------+
```
C Chest
I Impulse Itemduct
T Tunnel
-+| Normal Compact Machine

**Comment by davenonymous** [comment]
Thanks for the detailed report. I will look into it.
I suspect there is not much I can do on my end because of the way that Thermal Dynamics ducts work.
You could try putting a receiver on the outside of the left machine, like this:

```
+-------+     +-------+
|       |     |       |
|       |     |       |
|       |     |       |
|   CIIITRIIIITIIIC   |
|       |     |       |
|       |     |       |
|       |     |       |
+-------+     +-------+
```
Where R is the Receiver. Not sure whether this works or not.

What usually helps are buffer chests next to the tunnels with additional servos. But I agree, it would be nice if those weren't necessary.

**Comment by UncleOwen** [comment]
Thanks for your quick reply. That would be unfortunate, but if there's nothing you can do, there's nothing you can do. Do you think it would be worth it do raise this issue with the cofh team?

Thanks for an awesome mod!

**Comment by BreadtheRipper** [comment]
Hey, not sure if this is still a problem that exists for you, but I'm able to get item ducts to work between compact machines..
