### ISSUE TITLE
Chunkload machines when they are in a players inventory

### ISSUE THREAD

**Issue by davenonymous** [CompactMods/CompactMachines#305]
This would allow machines to act as "active" backpacks.
They could e.g. process ores while the player continues his mining run.

**Comment by ktole1999** [comment]
why not just add a chunkloader to your base.

**Comment by davenonymous** [comment]
By that logic I'd have to remove all chunkloading in the first place since you could just place chunk loaders in each machine.

**Comment by Saklad5** [comment]
I keep all my Compact Machines for automation nested (hierarchically) inside a single Compact Machine that I have at my base. If you want to, you could just use a similar tactic to chunkload hundreds of Compact Machines at once.

Just put all the Compact Machines you want to keep inside the one you carry with you, then place a chunk loader in that root machine.

**Comment by Saklad5** [comment]
My base, by the way, consists almost entirely of that one block. I design every Compact Machine to only need a Refined Storage cable on the North face, so I can organize them quite easily.

I’m not really big on the whole “building” thing.

**Comment by drstorm81** [comment]
Maybe it can be done like this:
You can craft a Compact Backpack.
Machine inside that backpack is loaded only if it is in player inventory/hotbar (configurable)
Backpack can be upgraded (but internal machine size cannot be changed) with things like:
- item buffer upgrade - backpack can be opened and provides simple chest-like interface with eg. 3x3 capacity, buffer can be accessed via a block from inside of the machine (with chest-like interface)
- magnet upgrade - requires item buffer upgrade, pulls dropped items into buffer
- filter upgrade - limits items that can be put in buffer, applies to magnet
- recharging upgrade - if power is supplied to a block/tunnel inside it charges fe/rf items/armor
- maybe other, like feeding and so on
Backpack can have only a limited number of upgrades (configurable). Machines in backpack cannot be nested (configurable).
