### ISSUE TITLE
[Question] Meta Data In Custom Recipes

### ISSUE THREAD

**Issue by TheLimePixel** [CompactMods/CompactMachines#307]
So I just wanted to ask how do you set the meta data for the blocks and catalyst in custom recipes?

**Comment by davenonymous** [comment]
Catalyst meta data can be set via "catalyst-meta",
Input types use "meta" as key (see the [energy cell example](https://github.com/thraaawn/CompactMachines/blob/1.12.1/src/main/resources/assets/compactmachines3/config/recipes/example.energycell.json)),
but I'd recommend using the ```/compactmachines3 recipe copy-shape``` command to get the json for the types and shape.

**Comment by TheLimePixel** [comment]
Ok, thanks for clearing that up. :)
