### ISSUE TITLE
Compact Machines with Larger Vertical Space

### ISSUE THREAD

**Issue by Saklad5** [CompactMods/CompactMachines#308]
While I understand that the current size of the Maximum Compact Machine is meant to fit inside a single chunk, I think it would be quite useful to have Compact Machines with larger vertical space as well. This would allow players to fit more into a single chunk, and be situationally useful for multiblocks from mods like Extreme Reactors.

As for the recipe, you could require three blocks inside 5x5x5 recipes instead of one. In the case of the Maximum Compact Machine, you’d add an additional Emerald block above and below the one in the current recipe to designate that you want it to be taller.

I recognize that this is probably not going to be implemented in Compact Machines 3, but it is worth considering for Compact Machines 4 when 1.13 comes out. It shouldn’t require much in the way of changes to implement.

And yes, I’m mainly asking because I want to build an Extreme Reactors Turbine.

**Comment by davenonymous** [comment]
No, the more people ask for this the less likely it gets that I implement it. It would also require a major rewrite of some of the internal mechanics. The recipe would be the least of the problems caused by this.
