### ISSUE TITLE
Compact Machines in The End

### ISSUE THREAD

**Issue by SuperCreativeUserName** [CompactMods/CompactMachines#310]
Compact Machine Version is 1.12.2-3.0.5-b184:
Forge Version is 8.0.99.99:
I am not using Optifine:
There is no crashlog

When a compact machine is moved into The End, none of the machinery inside is usable.  Nothing outside of the compact machine can see anything within the compact machine through the tunnels and if I attempt to break anything within the compact machine, it breaks but is immediately replaced.  I was able to move storage drawers in and out with a Moving Wand and I was able to use a Crescent Hammer to collect machines.  However, the item entities on the ground were not visible, and xp orbs were also invisible.  When I made a new compact machine and only used it in The End, internal machines were able to communicate with external machines, but it seemed not to be working properly (items were being moved in weird bursts) and while I was able to place machines and cables, I still was not able to break them except under the above circumstances.

This was discovered in Direwolf20 1.12.2 v1.8.0 if it matters.

Steps to reproduce:
1) Create a compact machine in The Overworld with machines set to transfer items in/out
2) Move the compact machine into The End

or

1)Make a compact machine in The End with machines set to transfer items in/out

**Comment by davenonymous** [comment]
Thanks for the report! I will look into it soon!

**Comment by davenonymous** [comment]
I can not reproduce this in either of the ways you described. No issues with machines transferring power over tunnels. No issues breaking blocks inside the machines.

Please be more precise in your description.

E.g. I'm not sure what you mean by "moving" a compact machine. Are you breaking and placing it? Or are you using a moving wand?

**Comment by SuperCreativeUserName** [comment]
From what I remember, the problem occurred both when I used a moving wand,
and when I broke and replaced the machine. Unfortunately, the server on
which I experienced this has since moved on to a new modpack, so I no
longer have access to the world and it's not a problem I've experienced in
any other worlds/packs so... It may just be one of those wierd things.

**Comment by WilliamBlaze** [comment]
if i had to guess; could it have had something to do in the mod pack that altered the user's UUID? not sure what effects this would have on compact machines but i know such a changes; when they have occurred in world, have caused mods like "Ice and fire" and "lycanite's mobs" mods to stop recognizing the player as the owner of their tamed creatures/entities. i'd imagine if ownership of the compact machines are handled in a similar manner; IE the player's UUID confirms the ownership and thus the controls of the compact machine in question, then any alteration to the player's original UUID would essentially break the recognized ownership feature.  Mods such as the "Vampirism" mod change the player's UUID when they become a vampire or a vampire hunter. 
but if ownership/permissions of the compact machine don't use the UUID as a means of checking to see if the player actually owns said compact machine, then i don't think i've the slightest clue how you could reproduce this issue described above and it probably is just a one off bug.
