### ISSUE TITLE
suggestion for function

### ISSUE THREAD

**Issue by kain184** [CompactMods/CompactMachines#312]
I don't have an issue per say as an idea. I noticed when building a machine inside the compact machine that I could not use computercraft cables through the tunnels. I would think this would be a cool interaction now that computercraft is open source. if at all possible I would love to see this feature added

**Comment by davenonymous** [comment]
It would be computercrafts job to add support. As long as they are not using capabilities to propagate their networks this won't work.

Btw OpenComputers is supported.
