### ISSUE TITLE
Game crash when looking inside - RFTools Simple Powercell

### ISSUE THREAD

**Issue by Keltas** [CompactMods/CompactMachines#313]
Compact Machines version: 1.12.2-3.0.7-b197
Forge version: 14.23.2.2613
I am using Optifine.
Link to Crashlog: https://pastebin.com/Mh61S4hC

The game crashes when right clicking on a compact machine without Personal Shrinking Device in hand, when a Simple Powercell is present inside. I didn't check it with other blocks from RFTools but it is possible that there are others that can cause this crash. 

Steps to reproduce:
1. Place the Simple Powercell inside a compact machine.
2. Get out of the Compact machine.
3. Right click on the compact machine with empty hand.

**Comment by davenonymous** [comment]
I can not reproduce this. Any more ideas on how to reproduce this crash?
![2018-04-21_08 45 08](https://user-images.githubusercontent.com/205210/39081362-617dc74e-4540-11e8-8914-a512862ac080.png)

**Comment by Keltas** [comment]
Ok. I can no longer reproduce this crash. It was consistent in a heavily modded instance, which after updating all the mods to up-to-date versions no longer occurs.
