### ISSUE TITLE
Crash with Thermal Ducts

### ISSUE THREAD

**Issue by phit** [CompactMods/CompactMachines#314]
**Compact Machines version**: 3.0.7  
**Forge version**: 14.23.2.2627  
**Link to Crashlog**: https://gist.github.com/phit/c27574487f819df02d54f0895431b281

We seem to be getting a lot of server crashes from people using TE ducts with CompactMachines, see crashlog above.
Not sure how to trigger it, but it happens very frequently probably when a chunk with the mentioned setup is loaded. Only solution I have found is to remove the ducts with MCEdit.

Sorry, that I have nothing more helpful than that, if you have anything I could provide let me know.

**Comment by davenonymous** [comment]
This should probably help. Since I could not reproduce this, would you mind retesting that for me with the latest version 3.0.8 once it's released?

**Comment by phit** [comment]
That should do, I had this patch running serverside since I've reported this. I did a trycatch mainly to see where the issue is even coming from.

```java
        try {
            if(!WorldSavedDataMachines.INSTANCE.tunnels.containsKey(this.coords)) {
                return null;
            }
        } catch (NullPointerException e) {
            Logz.error("Error getting tunnel for: " + this.coords + " " + side, e);
            return null;
        }
```

I shall test again, when the modpack updates.
