### ISSUE TITLE
Lag when entering compact machine

### ISSUE THREAD

**Issue by kevincook** [CompactMods/CompactMachines#319]
**Read then remove this section**:

**Compact Machines version**:3.0.7-b197
**Forge version**: 14.23.2.2654
**I am not using Optifine**: I am using optifine
**Link to Crashlog**: [here](url)
**Screenshot (if possible)**: [here](url)

**Description of the problem including expected versus actual behavior:**
When I enter a compact machine (even an empty machine) I get crazy lag for about 30 seconds, and it ultimately subsides.  The only thing in the logs that occurs when I enter the machine that looks abnormal is this:

[11:15:07] [JM-task-7/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.

**Steps to reproduce:**

**Comment by Saklad5** [comment]
Hmm. Does that appear before or after the lag? It could be that it spends 30 seconds trying to render it before giving up.

**Comment by kevincook** [comment]
It happens immediately when entering the machine.   There really is nothing else in the logs (unless there's a log I'm not aware of) that shows anything unusual.

**Comment by davenonymous** [comment]
Are we talking about the usual lag when changing dimensions or is this something different?
If so: Any ideas on how to reproduce this? What is the simplest case which causes this to happen?

**Comment by litjohn50** [comment]
I'm having the same issue. 

Mod Version. 3.0.8b200

Forge14.23.3.2673

Latest Log of the issue that I've Seen from server console.

https://gist.github.com/litjohn50/1d860cf919f570b49d4d90871316780d

Issue pops up near line 10088. or

[04:30:37] [Server thread/INFO] [journeymap]: litjohn1 joining dimension 144
[04:30:37] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught

ect..

**Comment by robotgryphon** [comment]
Needs verified on b278; reopen if still an issue with latest build.
