### ISSUE TITLE
Crash when trying to exit machine

### ISSUE THREAD

**Issue by Stephenator0316** [CompactMods/CompactMachines#320]
**Compact Machines version**: 3.0.7 B197
**Forge version**: 14.23.2.2654
**I am not using Optifine**: False, but still
**Link to Crashlog**: [here](pastebin.xyz/p?q=N1d0dmg)

**Description of the problem including expected versus actual behavior:** Logged out in a compact machine. Logged back in, and when I tried to leave I crashed

I know that I have optifine installed, BUT, I still report these bugs just in case OptiFine isn't involved and you see something in the code you may have missed.

**Comment by davenonymous** [comment]
I'm not able to reproduce this. Please try this without OptiFine and see whether the issue persists.

**Comment by Stephenator0316** [comment]
It stopped happening after I restarted the game. I guess it's just another mystery that will never be solved in this wonderful game we call Minceraft
