### ISSUE TITLE
[Request] Config to disable worldgen in CompactMachines

### ISSUE THREAD

**Issue by NielsPilgaard** [CompactMods/CompactMachines#322]
**Compact Machines version**:  1.12.2-3.0.8-b200
**Forge version**: 1.12.2-14.23.3.2673
**I am not using Optifine**: I am not using Optifine
**Link to Crashlog**: [here](url) Null
**Screenshot (if possible)**: [here](url) Null

Hey! I would like to request a config option to disable worldgen in the Compact Machines dimension. This would "fix" the issue with Ice & Fire, where Ice & Fire never stops generation inside the Compact Machines dimension. In addition to this, it'd speed up the transport to the dimension a tiny bit, which isn't half bad.

What do you think? :)

**Comment by davenonymous** [comment]
Worldgen in the compact machines dimension is already disabled.
I'm not aware of any more ways to prevent mods from generating stuff. If you are aware how this could work, please tell and I'll implement it.

**Comment by NielsPilgaard** [comment]
Oh I see, my bad :)

**Comment by davenonymous** [comment]
No worries at all! I'll continue looking into this. Maybe there is a way I don't know about yet!

**Comment by NielsPilgaard** [comment]
Sounds good :D

**Comment by davenonymous** [comment]
Found a way. The updated version 3.0.9 containing the fix is waiting for approval on curse.
I did not add a config option however. Can't think of any situation where world gen would be wanted in the Compact Machines dimension.

Cheers!

**Comment by NielsPilgaard** [comment]
Sweet, well done!

**Comment by davenonymous** [comment]
Sadly, this didn't work and caused more issues (1x) than it solved (0x).
I've reverted the changes and created a Pull Request for the Ice and Fire mod.

**Comment by NielsPilgaard** [comment]
Well damn, it was worth a shot though :)
