### ISSUE TITLE
Exception in server tick loop: Can not get property PropertyEnum{} on Air

### ISSUE THREAD

**Issue by Myriadtail** [CompactMods/CompactMachines#323]
**Compact Machines version**: 3.0.8-b200 (ATM3 5.9.4b)
**Forge version**: 14.23.3.2674
**I am not using Optifine**: Not installed.
**Link to Crashlog**: [here](https://pastebin.com/m1ZXbmUB)
**Screenshot (if possible)**: N/A

Seems this bug has reared its head before, within [Botania](https://github.com/Vazkii/Botania/issues/1955).  Appears to be just poor code cleanup within Forge, with a [band-aid fix at the mod level](https://github.com/Vazkii/Botania/commit/0085bc2415b379b76a2e264ac797ea35edbea298) having to be done.  Exceedingly obscure, but does seem to be an odd problem.

**Comment by robotgryphon** [comment]
Closed as working, per comments in #328
