### ISSUE TITLE
Crash to desktop on entering machine

### ISSUE THREAD

**Issue by SHEERSPECTOR** [CompactMods/CompactMachines#325]
**Compact Machines version**: 3.0.10
**Forge version**: 2678
**I am not using Optifine**:  Compact machines is the only mod installed
**Link to Crashlog**: [here](https://pastebin.com/c8tV6GVE)
**Screenshot (if possible)**: N/A

**Description of the problem including expected versus actual behavior:**
This error first occurred in a modpack, but it also occurs when compact machines is the only mod in a fresh instance of Forge.
Attempting to enter a new compact machine using the tool causes the game to crash while between dimensions.  This leaves player stuck in undefined state that causes further crashes upon opening world.  Stuck player can be fixed by editing their dimension data in NBTExplorer.  

First click on machine with tool appears to initialize it, but second click causes crash during player transport to machine.

Rolling back to 3.0.8 of compact machines fixed it in my testing pack.  Reverting back also fixes player being stuck between dimensions and crashing on world start.

**Comment by davenonymous** [comment]
Oops, my bad. Hotfix incoming.

**Comment by davenonymous** [comment]
Thanks for the excellent bug report by the way!
👍 

You can grab a fixed version from curse now.
