### ISSUE TITLE
Pneumaticcraft in a compact machine preview crash.

### ISSUE THREAD

**Issue by HyWhoHuntsBugs** [CompactMods/CompactMachines#328]
**Compact Machines version**: 3.0.8-b200 [Modern Skyblock 3, will check back on this when the pack updates the Compact Machines version]
**Forge version**: 14.23.3.2670
**I am not using Optifine**: True
**Link to Crashlog**: https://pastebin.com/XMEk87s0
**Screenshot (if possible)**: N/A

**Description of the problem including expected versus actual behavior:**
This is a preview crash while having pneumaticcraft machines inside a compact machine.

**Steps to reproduce:**
Since I see both Liquid Compressor and Pressure Tube in the logfile it may be an edge case with my particular setup having an Advanced Liquid Compressor attached to an advanced tube with a gauge module on it.

This might be a duplicate of or related to [/issues/323](https://github.com/thraaawn/CompactMachines/issues/323)

**Comment by davenonymous** [comment]
Could you try with the latest build from [here](https://www.dropbox.com/sh/7yyd9dgii1epibu/AADARWLwgjOBu9wU-zZVHp-ra?dl=0)?
This is probably fixed with 54fb0cc10c73ae9267dd293de87bfe773278d018

If so, I'll release a new build later today.

**Comment by HyWhoHuntsBugs** [comment]
Doesn't crash under 3.0.11-b213. The render is...off, but it doesn't crash. I call that a success.

![itmostlyworks](https://user-images.githubusercontent.com/33169096/40263085-8609de12-5adb-11e8-81c1-febe4be44ab9.png)

(The Jukeboxes are actually Advanced Pressure Pipes, and the Brewing Stands are Advanced Liquid Compressors, both of which would be ticking when this was taken.)

**Comment by davenonymous** [comment]
Weird, they render fine for me:

![2018-05-19_08 35 19](https://user-images.githubusercontent.com/205210/40265810-a470ad18-5b3f-11e8-958b-700630790ebd.png)
