### ISSUE TITLE
[Suggestion] Add compatibility with void miners and solar panels.

### ISSUE THREAD

**Issue by Lodran** [CompactMods/CompactMachines#329]
By changing the wall block so that it is considered to be transparent to light, and by giving the dimension that compact machines are placed in a day/night cycle, it would then be possible machines such as Environmental Tech's Void Miners and Solar Panel Arrays to function within a Compact Machine.

I've tested this as far as I can, as follows:

1) Transparent blocks (such as Thermal Expansion's Energy cell) do not obstruct a void miner which otherwise has a downward view of either bedrock or void.
1) Transparent blocks (such as Thermal Expansion's Energy cell) do not obstruct a Solar panel array which otherwise has an upward view of sky.

**Comment by Lodran** [comment]
I've experimented a bit further, by breaking the floor and ceiling of a Compact Machine in a creative world.  It all works, except that I suspect there's a limit to how much RF/Tick I can put through a tunnel.

**Comment by dustinmemoli** [comment]
This would be a very cool feature.
I've had to relocate my solar panels like 3 times, each time i decide to add another 'floor' or story to my base. This would allow me to hide them in a box :)

**Comment by githubuser1256** [comment]
RE: Void Miners: Perhaps add a similar block to a tunnel in order to access bedrock. I can put the machine in a hole that goes down to bedrock but the void miner just can't "see" through the tunnel.
