### ISSUE TITLE
Server crash when entering compact machine

### ISSUE THREAD

**Issue by davqvist** [CompactMods/CompactMachines#330]
**Compact Machines version**: 3.0.11-b207
**Forge version**: 2688
**I am not using Optifine**: No

See https://github.com/davqvist/Exoria/issues/201 for the original report with crash log.
Happens whenever he is entering a Compact Machine.
Let me know if you need more information

**Comment by AaronOziel** [comment]
I am having this issue too, will update with log if I can get them. Using davqvist's Exoria mod pack version 1.0.2

**Comment by robotgryphon** [comment]
Judging by the other reports, this was an issue with drone spawning and an older version of the mod. Going to close to clean up issues, reopen if still an issue with b278.

**Comment by MiJlenium** [comment]
Hi, I have the same problem - when exiting the maximum mechanism, the game just freeze. Version b278

**Comment by robotgryphon** [comment]
Sorry, as this is for a long unsupported Forge version and given the age of the last release, 1.12 is out of support now. I will not be addressing this.
