### ISSUE TITLE
Gaming stopped

### ISSUE THREAD

**Issue by Knito58** [CompactMods/CompactMachines#332]
I didn't know where to put my croparia coal farm. I finally made my first CM project and put four levels into the biggest thing. Self sustaining with xnet and rftools and actually additions.
The surplus coals go via hopper under the bottom of the CM into a chest.

Now everything has stopped because I do nothing more than sitting before the block, right clicking it and watch the magic inside. From time to time I click the chest: It really fills up with coal!

How can I continue with my other projects? Will there ever be any? The chest fills up.
Its so cute....

**Comment by davenonymous** [comment]
Thanks for making my day!
I'll keep this issue open for a while 👍

**Comment by robotgryphon** [comment]
This one stays open. And pinned. ❤️
