### ISSUE TITLE
Crash on load after placing items within a Compact Machine

### ISSUE THREAD

**Issue by Mystborn0828** [CompactMods/CompactMachines#333]
**Compact Machines version**: 1.12.2-3.0.11-b207
**Forge version**:  1.12.2 - 14.23.4.2705
I am not using optifine
Crash Log: https://pastebin.com/eehDsKcX
FML Log: https://gist.github.com/Mystborn0828/8546d1627ce6c7e7300a53efd9bcf3dd

Description:
Whenever I place any machines or items inside a compact machine, the next time I save and log out I will no longer be able to enter the world without crashing.  The only way to get back is to load a backup from before putting anything in the compact machine.  The issue occurs with all machine sizes.  I believe it occurs with any block type, although so far I have only tested it with a tree farm using a mix of machines and with advanced rocketry machines, so I'm not positive if there are items I can place inside a machine and not have the crash occur. The crash occurs right after beginning to load terrain.  

**Steps to reproduce:** 
Place any items within a compact machine and then save and exit the world.  Crashes upon attempting to load in.

**Comment by davenonymous** [comment]
Not Compact Machines fault, this is TATW crashing, see [this issue](https://bitbucket.org/Aroma1997/tatw/issues/2/server-startup-crash).
