### ISSUE TITLE
Right clicking for preview causes fatal error on a specific compact machine. Minecraft 1.12.2, Forge 14.23.4.2703, Compact machines 1.12.2-3.0.11-b207

### ISSUE THREAD

**Issue by drats666** [CompactMods/CompactMachines#334]
**Compact Machines version**:  1.12.2-3.0.11-b207
**Forge version**: 14.23.4.2703
**I am not using Optifine**: using optifine
**Link to Crashlog**: Have none
**Screenshot (if possible)**: https://media.discordapp.net/attachments/443884062541611008/452224997075976202/unknown.png?width=1088&height=651

**Description of the problem including expected versus actual behavior:**
After moving all my compact machines to one room in my base, when i right click on a specific machine to see its contents (with an empty hand or otherwise) instead of showing the preview of the inside, it crashes to the fatal error, however it isnt an actual crash. the client remains open, it just essentially disconnects me with the error. I can get the others to work properly however this one seems to not want to cooperate. 
I can enter it using the shrinking device, just not preview it. The contents of the machine is several garden cloches, EnderIO conduits, a flux point, 5 blocks worth of reserviours from enderio, 1 enderchest, several small storage crates, some cobblestone for block placing support and 1 ender tank.
This issue only arouse after I moved it from its original location, and the other machine blocks are working fine.

**Steps to reproduce:**
right click on the compact machine to attempt to preview the inside. Get presented with the screen shot.
![image](https://user-images.githubusercontent.com/24499415/40865165-072707a6-65c5-11e8-8220-6b22ef1d9107.png) This is my machines from the outside.

![image](https://user-images.githubusercontent.com/24499415/40865191-21be2b76-65c5-11e8-9374-0fdb97bbf12d.png) The contents of the machine.

![image](https://user-images.githubusercontent.com/24499415/40865221-4772e514-65c5-11e8-89c8-46b5707d0d0d.png)
 The error when i right click on outside with an empty hand or anything in my hand.

**Comment by davenonymous** [comment]
Please try again with the latest version.

**Comment by davenonymous** [comment]
I assume that fixed it.

**Comment by ClassyH** [comment]
I have this same problem with 
compactmachines3-1.12.2-3.0.15-b249
1.12.2-forge1.12.2-14.23.5.2781 
There is no optifine installed, I can enter the machine perfectly but if I want to edit the whitelist for the machine, I need to get past the preview.
![Naamloos](https://user-images.githubusercontent.com/37928757/58827364-2567c800-8643-11e9-9527-6896e7a58372.png)
![Naamloos2](https://user-images.githubusercontent.com/37928757/58827365-26005e80-8643-11e9-9937-2e2892cf2f8e.png)
![Knipsel](https://user-images.githubusercontent.com/37928757/58827366-26005e80-8643-11e9-81ba-8d2527a040a4.PNG)

**Comment by davenonymous** [comment]
You are using a > 3 month old version.

**Comment by ClassyH** [comment]
Oké, thnx for info, ill let the server owner know!

Op 3 jun. 2019 22:31 schreef thraaawn <notifications@github.com>:

You are using a > 3 month old version.
