### ISSUE TITLE
Unable to light nether portal in compact machine, Compact Machines version: 1.12.2-3.0.11-b207 

### ISSUE THREAD

**Issue by drats666** [CompactMods/CompactMachines#335]
Compact Machines version: 1.12.2-3.0.11-b207
Forge version: 14.23.4.2703
I am not using Optifine: using optifine
Link to Crashlog: Have none

Screenshot (if possible): 
![image](https://user-images.githubusercontent.com/24499415/40945230-d8372b3e-6825-11e8-8f6f-b1200d283b48.png)

Description of the problem including expected versus actual behavior: Building a nether portal inside of a compact machine, lighting the portal to start it fails to start the portal.

Steps to reproduce:
build portal in a compact machine (mine is againist compact machine wall), pull flint and steel out, light portal. become disappointed.

**Comment by davenonymous** [comment]
Sorry, this isn't supported at the moment and I'm not sure it ever will be. Portals in the Nether always lead to the Overworld I think.
