### ISSUE TITLE
No Mob spawns, but bats spawn Compact Machines version: 1.12.2-3.0.11-b207

### ISSUE THREAD

**Issue by drats666** [CompactMods/CompactMachines#336]
Compact Machines version: 1.12.2-3.0.11-b207
Forge version: 14.23.4.2703
I am not using Optifine: using optifine
Link to Crashlog: Have none
Screenshot (if possible): 

Description of the problem including expected versus actual behavior:
Mobs fail to spawn in compact machines. Placing dirt then pure evil on the dirt to create cursed earth for a mob farm, but the mobs never spawn. 

Steps to reproduce:
Place dirt down inside a compact machine. use pure evil on dirt to turn it into cursed earth. leave the machine but keep it loaded. return later to find no mobs. same happens if you stay in the same machine.

**Comment by davenonymous** [comment]
Did you darken the room? The walls are quite bright.

**Comment by drats666** [comment]
that worked, thank you.
