### ISSUE TITLE
Roots 2 sprouts appearing inside compact machines.

### ISSUE THREAD

**Issue by Lodran** [CompactMods/CompactMachines#339]
The Roots 2 mod is spawning sprout entities inside my machines.

It seems they despawn when I leave, so it might not cause problems.

**Comment by TimmehTheMeme** [comment]
I also have this issue but mine do not despawn. I come back and there are sometimes 10+ sprouts walking around.

**Comment by urikkiru** [comment]
This might be related to having the compact machine in a chunkloaded chunk. This chunkloads the machine, possibly stopping them from de-spawning.

**Comment by Notlucky101** [comment]
I have to same problem..

**Comment by robotgryphon** [comment]
Needs to be verified on the latest version (b278).

**Comment by SizableShrimp** [comment]
This isn't an issue with the CM3. This tells me that the mod's mob spawning mechanics are working and intact. If you don't want sprouts in your machines, find a way to configure Roots 2 to blacklist the Compact Machines dimension, or disable mob spawning in Compact Machines entirely. I am requesting @robotgryphon close this issue.

**Comment by robotgryphon** [comment]
Per request, going to close this as a crossmod issue until proven that CM3 is at fault for rogue spawning mechanics.
