### ISSUE TITLE
Shulkers teleport out of compact machines

### ISSUE THREAD

**Issue by Yadokingu** [CompactMods/CompactMachines#340]
forge-14.23.4.2707
compactmachines3-1.12.2-3.0.11-b207

Shulkers will teleport out of the compact machine and attach themselves outside. Since they don't despawn and there is no way to get to them, that isn't exactly great. (I'm in a local world, so I just used a kill command, but not everybody can do that)
This could probably be prevented by making the warding aura blocks not be full blocks, since shulkers can't teleport to those.

![2018-06-17_06 21 39](https://user-images.githubusercontent.com/11133215/41504697-bbbfe0d2-71f7-11e8-92e6-b1db7b7a0959.png)

**Comment by Newellis** [comment]
I found this too here is a picture of the inner view of my compact machine
<img width="1680" alt="screen shot 2019-02-10 at 8 31 53 pm" src="https://user-images.githubusercontent.com/8408466/52546662-24e6b100-2d76-11e9-9d93-28b55595d4ba.png">
My version of compact machines 3 is 3.0.13
Forge version: 14.23.52808
