### ISSUE TITLE
MultiblockRecipeWrapper causes flickering leaves when mipmap is enabled

### ISSUE THREAD

**Issue by mezz** [CompactMods/CompactMachines#341]
https://github.com/thraaawn/CompactMachines/blob/68b78073e804dc1651555e8c38662552f9d922c6/src/main/java/org/dave/compactmachines3/jei/MultiblockRecipeWrapper.java#L60

This issue is a bit obscure, but I found a call to `setBlurMipmap` without the corresponding `restoreLastBlurMipmap`. This makes the next call to `setBlurMipmap` overwrite the last stored settings, and so it will never restore to the right settings. When this happens and mipmap is enabled, leaves in the world flicker annoyingly.

Steps to reproduce:
1. Turn on mipmaps to level 4.
2. Look at some distant trees, they should look fine.
3. Open your inventory and view anything in the "Multiblock Miniturization" recipe category in JEI.
4. All distant tree leaves will be flickering, even after closing the gui.

**Comment by davenonymous** [comment]
Thanks for the report. I'll fix it later today!
