### ISSUE TITLE
Miniturization Issue with lots of blocks - "The string is too long for this encoding."

### ISSUE THREAD

**Issue by TheFlash787** [CompactMods/CompactMachines#344]
Error Shown: https://gist.github.com/TheFlash787/6389a5d27ef70c8167a2baa7c95fd030
Compact Machines Version: compactmachines3-1.12.2-3.0.12-b215.jar
Description:

When using a large area that you are trying to create a recipe for, and the structure includes lots of different types of blocks/tiles etc, When running the /compactmachines3 recipe copy-shape command, it says that it has copied the script to the clipboard but doesnt. It throws that error in the logs. Is this an issue that can/will be fixed in a later version of the mod?

Thanks!

**Comment by davenonymous** [comment]
I will look into it and hopefully have it fixed by the next release.

**Comment by Arudarin** [comment]
Has there been a fix yet?

**Comment by TheFlash787** [comment]
@thraaawn Was this fix pushed to a newer version? I'm ready to close if so. I haven't yet retested.
