### ISSUE TITLE
*Request* Ability to rotate miniaturization field projectors after placement.

### ISSUE THREAD

**Issue by NiSiSuinegEht** [CompactMods/CompactMachines#345]
Currently, it is seemingly impossible to place the projectors such that they create a field large enough to make a maximum sized compact machine, while within a maximum sized compact machine.  They always face orthogonally away from where the player is standing when the projector is placed.  Since they need to be 11 blocks apart to form the 5x5x5 field, this is not possible within the machine.  Adding an ability/tool to rotate them, or a shift+place method to make them face the player, would be greatly appreciated.

I wanted to make a base that is contained entirely within a single machine block, with other block based rooms nested within.  The only thing preventing this is the inability to place the field to make more blocks, I have to do that outside.

**Comment by davenonymous** [comment]
I've completely changed how the projectors direction is being determined and added a visual guide for the player. It looks like this now:
![2018-07-14_21 43 01](https://user-images.githubusercontent.com/205210/42727897-f2194980-87ae-11e8-9d07-d3df4394d3d1.png)

This should resolve your issue.

**Comment by tonyvans** [comment]
amazing mod, I just discovered it. the possibilities are endless. this arrow is exactly what I was hoping for, how do you get it to work? playing on FTB revelations 1.12.2-3.0.12-b215. trying to place these inside the large 13x13x13 to get the max they have to be right against the wall. 

Disregard, I found I could whack the top part with a Ender IO "Yeta Wrench" and it will rotate the top part.
