### ISSUE TITLE
Compact Machines 3 IE Diesel Generator CAUSES CRASH

### ISSUE THREAD

**Issue by ghost** [CompactMods/CompactMachines#347]
**Compact Machines version**:3.0.12-b215
**Forge version**:14.23.4.2738
**I am not using Optifine**: Yes i am not using it
**Link to Crashlog**:  https://pastebin.com/ycvzuPxp
**Screenshot (if possible)**: not possible

**Description of the problem including expected versus actual behavior:** I entered 5x5x5 room and build up a IE diesel generator and everything was fine until i right clicked it with an hammer then game crashed. Everytime i try to open world it just crashes.

**Steps to reproduce:** I dont get this is what

**Comment by ghost** [comment]
I just builded diesel generator and metal press in creative in 5x5x5 and 13x13x13 room and nothing happened success but i want to know what caused this to my survival world please take a look at crash report

**Comment by davenonymous** [comment]
Hey, I hope I'll have some time to look into this over the weekend.
I probably won't be able to reproduce this and there won't be much I can do to fix this.

According to the stack trace it also rather looks like a problem of the IndustrialWires mod. Did you build in your survival world include and wires from that mod? Try to update to their latest version, maybe that fixes it?

**Comment by robotgryphon** [comment]
Closing this for being stale and no comments on being able to reproduce effectively. Please reopen if the latest mod versions cause crashes. Thanks.
