### ISSUE TITLE
[feature request] Duplicating machine contents

### ISSUE THREAD

**Issue by SomewhatDamaged** [CompactMods/CompactMachines#351]
**Idea**: A way to take a CM that is already linked and populated with "stuff", put it into some kind of machine/whatever along with a blank CM of the same size, put a chest beside the machine/whatever with all the contents of the populated CM. The machine would delete everything in the chest, link the blank CM, and copy the populated CM's contents (chunk) to the new one.

**Comment by davenonymous** [comment]
It's impossible to detect everything in a block and require it as cost. For example I would have to gather data from all the storage options (chests, barrels, drawers etc). Even worse, you can connect your refined storage network from the outside to the inside of a machine, which would require to track down the controller to see whether it's in the machine itself or outside.
It would require way to much custom logic for all the mods storing anything.

Sorry, not going to happen.
