### ISSUE TITLE
Gregtech:CE+TOP+CompMach3 metadata tunnels issue

### ISSUE THREAD

**Issue by Agrax** [CompactMods/CompactMachines#353]
**Compact Machines version**: compactmachines3-1.12.2-3.0.12-b215
**Forge version**: 14.23.4.2739
**I am not using Optifine**: nope
**Screenshot (if possible)**:
(1) https://cdn.discordapp.com/attachments/439381738636967956/478668213261959174/Zrzut_ekranu_2018-08-13_22.55.34.png
(2) https://cdn.discordapp.com/attachments/439381738636967956/478668215761895425/Zrzut_ekranu_2018-08-13_22.55.33.png
(3) https://cdn.discordapp.com/attachments/439381738636967956/478668406816768000/Zrzut_ekranu_2018-08-13_22.57.06.png
(4) https://cdn.discordapp.com/attachments/439381738636967956/478668410079805441/Zrzut_ekranu_2018-08-13_22.56.57.png
(5) https://cdn.discordapp.com/attachments/439381738636967956/478664457061531648/Zrzut_ekranu_2018-08-13_22.41.06.png
(6) https://www.dropbox.com/s/nmq7amw1kban9o0/Zrzut%20ekranu%202018-08-13%2023.19.42.png?dl=0
(7) https://www.dropbox.com/s/b9qfy6r0srhslis/Zrzut%20ekranu%202018-08-13%2023.24.03.png?dl=0
(8) https://www.dropbox.com/s/2f75kbh6qnwosr2/Zrzut%20ekranu%202018-08-13%2023.19.51.png?dl=0

**Description of the problem including expected versus actual behavior:**

Soo... Thermal dynamics ducts render properly on TOP display. If i plug an opaque fluiduct (5281:1), TOP renders it as an opaque fluiduct. But when using GregTech: Community Edition wires TOP ommits the metavalue of the cable. As a result GTCE 2x aluminium wire (id 6703:1) is shown as 1x aluminium wire (id 6703:0). It seems like CM3 tunnel doesn't care abt GTCE block metadata, whereas it has no problems with rendering TD duct metadata. The expected behavior is: 1x wire renders as 1x wire, 2x wire renders as 2x wire.

I am not sure if it's your mod's issue, but im trying to figure out where is the problem. One of the fellow modpack devs told me that "its possible the CM devs have built in explicit overrides.  Like, if Thermal Dymamics is involved, use meta". So i ask you if your mod usually doesn't care abt metadata, but if a mod from the list is involved, it has to care abt the metadata. If so, could you include said mod into that list?

**Comment by Rongmario** [comment]
https://github.com/thraaawn/CompactMachines/blob/1.12.1/src/main/java/org/dave/compactmachines3/world/data/provider/cofh/ThermalDynamicsGrid.java

**Comment by robotgryphon** [comment]
This needs to be verified against the latest versions of the affected mods; given the linked commit and file, likely to be updated. reopen if still an issue with latest Thermal Dynamics and CM3.

**Comment by SizableShrimp** [comment]
This isn't an issue with Thermal Dynamics, but rather Gregtech: Community Edition. Unfortunately, the most important screenshots here dealing with the broken display of Gregtech: CE tunnels connected on the machine were uploaded to dropbox and have been deleted, whether automatic or manually. Until new screenshots are posted, I cannot work on this. @Agrax, if you still have these screenshots, please reupload them.
