### ISSUE TITLE
Missing Textures for TE blocks with 1.12.2-3.0.12-b215

### ISSUE THREAD

**Issue by maxell45146** [CompactMods/CompactMachines#354]
Not sure what is causing this particular issue now but I do remember playing this not that long ago without trouble. Basically, if I connect to my MP server and go straight into a cube with TE machines the textures will be there. If I preview the cube though the textures will be missing, this also persists if I go into the cube then. All blocks still function  and even show the current upgrade status by the color corners. If I do a force reload on textures they will return but other modded machines will then have server graphic issues (missing pieces, wrong textures). 

I think I may rollback the version of CM to 1.12.2-3.0.11-b207 and see if the issue persists. 

**Compact Machines version**: 1.12.2-3.0.12-b215
**Forge version**: 14.23.4.2745
**I am not using Optifine**: true, I am not using optifine
Currently using the latest TE mods as well. 

![2018-08-13_18 28 33](https://user-images.githubusercontent.com/2869265/44062134-2742dfae-9f29-11e8-8577-18514f8d7508.png)
![2018-08-13_18 30 41](https://user-images.githubusercontent.com/2869265/44062135-2753523a-9f29-11e8-9dee-cf54977ece62.png)

**Comment by maxell45146** [comment]
Downgrading to 1.12.2-3.0.11-b207 had no effect, still missing textures.

**Comment by Keridos** [comment]
Can confirm this.

**Comment by Marcelo-Petrucelli** [comment]
Can also confirm this. it seems to have happened to me only after checking the Preview of the inside of the machine. Beforehand checking that I didn't have that texture problem.

Re-opening the game and not looking at the preview before entering solved the problem.

**Comment by urikkiru** [comment]
This is also happening for me. I keep accidentally previewing the machines before entering them. Is it possible to disable the preview feature entirely? If not, could we get that added as a workaround for this while we wait for a proper fix?

**Comment by urikkiru** [comment]
I made a pull request for this, https://github.com/thraaawn/CompactMachines/pull/375

It adds a configurable option to disable the rendering if desired, until a proper fix can be implemented.

**Comment by davenonymous** [comment]
This should be fixed in 3.0.14.
