### ISSUE TITLE
NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by Charismara** [CompactMods/CompactMachines#356]
**Compact Machines version**: 3.0.12-b215
**Forge version**: 14.23.4.2766
**I am not using Optifine**: Yes
**Link to Crashlog**: [here](https://pastebin.com/dCu0xaXf)

**Description of the problem including expected versus actual behavior:**
Hay,
I play a modpack on a server and when I try to go into a compact machine the server crashes.

**Steps to reproduce:**

1. Join a Server
2. Get a Compact Machine
3. Try to get into a compact machine
4. Server crashes
5. Be Sad 😢

**Comment by davenonymous** [comment]
The crash is happening in Open Terrain Generators code.
They already have an issue open about it: https://github.com/PG85/OpenTerrainGenerator/issues/185
