### ISSUE TITLE
Just Enough IDs: No content preview of the machines

### ISSUE THREAD

**Issue by gjrud** [CompactMods/CompactMachines#357]
**Compact Machines version**: compactmachines3-1.12.2-3.0.12-b230, originally found in compactmachines3-1.12.2-3.0.12-b215 (version the modpack mentioned below comes with)
**Forge version**:forge-14.23.5.2768
**I am not using Optifine**: true
**Link to Crashlog**: not crashing
**Screenshot (if possible)**: [issue in compactmachines3-1.12.2-3.0.12-b215](https://i.imgur.com/xee2DRh.jpg)
[issue in compactmachines3-1.12.2-3.0.12-b230](https://i.imgur.com/X8He1K9.jpg)
**Modpack (not sure if useful)**: StoneBlock version 1.0.20 from Twitch App.

**Description of the problem including expected versus actual behavior:**
When I right click the machine block I do not see a rendered preview of the content in it.

**Steps to reproduce:**
- Create a machine
- Place any block inside of it
- Exit the machine
- Right click the machine with an empty hand

**Additional info:**
I found the the issue while playing the modpack StoneBlock from the Twitch App, I then proceeded to create a new flat world to replicate the problem and post it here.
While posting I downloaded the latest version from the dropbox link in the readme and created a new machine in the same world to test if there were any changes.
The Minecraft instance is installed in the default folder in the Twitch App (%UserProfile%\Documents\Curse\Minecraft\Instances)

I apologize if anything isn't clear, I'm not an Eglish native speaker.

**Comment by jc2xs** [comment]
I've run into this same issue running the Stoneblock mod back.  On version 1.017 of the pack the machines the preview looked correct.  After updating the pack to 1.0.20 the preview is either blank or wrong.  The version of Compact machines in 1.0.20 version of Stoneblock is 3.0.12-b215

**Comment by davenonymous** [comment]
I will look into this. But I doubt I'll be able to reproduce the issue - and I can't investigate the issue if it only occurs when running stoneblock. I'll need the minimum steps required for a vanilla+cm world to start showing this problem.

There is nothing in the logs indicating any problems?

**Comment by gjrud** [comment]
Following @jc2xs hint about version 1.017 I proceeded to download it and start testing, and it worked.
After upgrading the modpack to 1.018 the preview broke again so I started reading the changelog to see what was changed.

I cloned version 1.017 and performed the changes mentioned one by one and luckly for me I found the issue pretty early on: when I added JustEnoughIDs version 1.0.2-26 the preview stopped working.

I then created a new profile using forge 14.23.4.2765 with just CompactMachines, JEI and JEID, the latter turned off at the beginning.
The preview worked fine until I restarted the client and turned JEID on, in [this pastebin](https://pastebin.com/2JqQeeVT) you can find the log from said session, I do not see anything wrong in particular in it but I'm also not sure what to look for.

Since the issue appeared when I turned JEID on is it related to said mod and should I report it to the creator?

**Comment by jc2xs** [comment]
Nice work @gjrud .  That is some of the best detective work I've seen in a long time!

**Comment by davenonymous** [comment]
It is indeed nice work @gjrud.
Not sure what JEID is doing exactly. I'll have a short look into this over the coming weekend, but I don't feel responsible here, to be honest. From what I've heard they are doing some shady stuff and adding mod compatiblity shouldn't be on the other mods end imho.

**Comment by kaiserdj** [comment]
In the latest versions of the StoneBlock pack (1.0.27), keep doing the same, do not show anything.
![image](https://user-images.githubusercontent.com/5487950/48156563-fd430100-e2cd-11e8-87b8-d8723aaf6d3e.png)

**Comment by kaiserdj** [comment]
Update screenshot 
![image](https://user-images.githubusercontent.com/5487950/48438364-20fdbf80-e784-11e8-8952-4d83b8d82dd9.png)

**Comment by davenonymous** [comment]
Phew, just looked into this.
The problem is that CM3 is sort of using the vanilla system to transfer chunk data from server to client.
This is being heavily tweaked by JustEnoughIDs, which is causing conflicts with my copy+pasted methods that would need to be adjusted for JEIDs changes.

Maybe @ZombieHDGaming is interested in fixing this in JEID?

**Comment by ZombieHDGaming** [comment]
@thraaawn Since it looks like your ChunkUtils class is ripped straight from the AnvilChunkLoader (based off your code comment, don't have my IDE open atm), have you changed anything about that/those methods to help CM3 with your situation? If you have, I'll have to figure out something to fix it (could be as simple as just adding a few lines of code into your methods), but if you haven't (which looks like you made a small modification), switching over to use the methods straight for AnvilChunkLoader should be able to fix the issue. I have a few ideas in mind, but I'll wait to hear your response.

**Comment by davenonymous** [comment]
I have some minor modifications in there:
1) Some additional data needed for some mods to render properly on the client side without actually being loaded in a world, for example while writing [here](https://github.com/thraaawn/CompactMachines/blob/c5175b2bcf2a57df18ee880ede5ff42f8e3799a4/src/main/java/org/dave/compactmachines3/utility/ChunkUtils.java#L112-L116) and [here](https://github.com/thraaawn/CompactMachines/blob/c5175b2bcf2a57df18ee880ede5ff42f8e3799a4/src/main/java/org/dave/compactmachines3/utility/ChunkUtils.java#L230-L235) the analog to this for reading.
2) Some other data modifications are done during loading, e.g. [shifting positions](https://github.com/thraaawn/CompactMachines/blob/c5175b2bcf2a57df18ee880ede5ff42f8e3799a4/src/main/java/org/dave/compactmachines3/utility/ChunkUtils.java#L228).
3) Entity data is being added [here](https://github.com/thraaawn/CompactMachines/blob/c5175b2bcf2a57df18ee880ede5ff42f8e3799a4/src/main/java/org/dave/compactmachines3/utility/ChunkUtils.java#L201).

I did not change any biome or ExtendedBlockStorage related stuff though.

**Comment by robotgryphon** [comment]
Going to need to verify this one against the latest versions of JEID. Might not be an issue in finalized 1.12 environments due to Forge changes and ID management.
