### ISSUE TITLE
Does not detect blocks inside

### ISSUE THREAD

**Issue by arkan501** [CompactMods/CompactMachines#361]
**Compact Machines version**: 3-1.12.2-3.0.12-b215
**Forge version**: 1.12.2-14.23.5.2769
**I am not using Optifine**: I am using Optifine
**Link to Crashlog**: N/A
**Screenshot (if possible)**: N/A

**Description of the problem including expected versus actual behavior:**
So I made the 9x9x9 machine and built a 5x5x5 Extreme Reactor. And had it filled with gelid cryotheum as the coolant. Well I thought I was safe going in and out so I left to get my fuel for the reactor, and when I went back in, I was inside the wall of the reactor and couldn't move. So I tried breaking a block to get out but instead was killed by my gelid cryotheum. I had a lot of important things on me both for my reactor and this mod, the personal shrinking device. Tried building a second one and going in but again I was spawned in the wall of the reactor, and killed again. I like the concept of this mod, and I'm not going to bash it for causing the destruction of much hard work that will take me forever to replicate, especially since this mod is still in beta. So I ask that you please work on figuring out how to prevent the player from spawning inside blocks that are in the compact machine dimension. If you can't, then maybe put a disclaimer about the the possibility of spawning inside blocks players have built inside the machine.

**Comment by davenonymous** [comment]
The manual explains the problem and gives a solution:
https://github.com/thraaawn/CompactMachines#spawn-location
