### ISSUE TITLE
Turn off chuckloaded Compact Machines

### ISSUE THREAD

**Issue by Ironstien** [CompactMods/CompactMachines#363]
Hey. Is it possible to unload Compact Machi e world's. I don't have the best PC and had the thought of setting up a few Compact Machines and only use them when I need but they stay loaded. Any ideas?

**Comment by davenonymous** [comment]
Sorry, not possible at the moment. Aim of this mod is not to provide performance improvements.
Maybe when I rework the chunk loading stuff for the 1.13 version of this mod. Sorry :(
