### ISSUE TITLE
Mekanism gasses

### ISSUE THREAD

**Issue by EntityReborn** [CompactMods/CompactMachines#364]
**Compact Machines version**: 3.0.12-b215
**Forge version**: 14.23.4.2760
**I am not using Optifine**: I am using Optifine, however the issue doesn't appear to be related.

I am trying to connect Mekanism gasses to the compact machine (15x15x15 in this case), and while I see Mekanism's Pressurized Tube connect into the overworld block when the tunnel is connected inside to a Pressurized tube, which is then connected to a Mekanism tank, no gas flows. In this case I used Oxygen.

I see that in the commit history there had been such a functionality available, however this appears to not be a thing any more.

**Comment by davenonymous** [comment]
https://github.com/thraaawn/CompactMachines#compatibility
-> Ask the Mekanism devs to switch to Forge Capabilities.
