### ISSUE TITLE
Capability adapter

### ISSUE THREAD

**Issue by zaekeon** [CompactMods/CompactMachines#365]
**Read then remove this section**:
Please read [this](https://vazkii.us/br101/) and follow there instructions in there before creating an issue.
Most importantly, do not create an issue if you have not tried fixing it by using the latest version of the mod!

Also make sure you've read the full readme [here](https://github.com/thraaawn/CompactMachines/blob/1.12.1/README.md) on github.

If you are reporting a bug regarding the interior view of the Machines, the one you get when you right click a machine, do not report it to any other mod author involved in the crash. It is highly likely that its CM3s fault.

**Compact Machines version**: latest
**Forge version**: latest
**I am not using Optifine**:
**Link to Crashlog**: [here](url)
**Screenshot (if possible)**: [here](url)

**Description of the problem including expected versus actual behavior:**

May be a long shot but any chance you’ve talked to this guy about doing a pull request to add his capability adapter code in?
https://minecraft.curseforge.com/projects/capability-adapter

**Steps to reproduce:**

**Comment by davenonymous** [comment]
It should be pulled into Applied Energistics, if at all.
