### ISSUE TITLE
I have a question?

### ISSUE THREAD

**Issue by JBSTheGamer** [CompactMods/CompactMachines#366]
Is the compact machines mod reliable? The reason why i asked this is because im going to put 154 storage drawers in it. Those drawers are filled max with tons of items. Most drawers have up to 396K items in them. Some drawers have up to 13mil of compacted blocks in compacting drawers. If i loose the dim because of a bug happening or corruption ima loose most of my resorces. All those things in those drawers are worth 12 days of game time collecting them. I just want to make sure before i put 12 days worth of game time in items into a compact machine.

**Comment by DemonFiend** [comment]
Ive built my entire base inside of compounded compact blocks before(Each room 13x13), never had any major issues with them, Aside from Farmer Blocks/ Auto farmers (Currently one from Foresty Breaks the unbreakable blocks and gives them to players). Aside from those, no major issues + Love the Mod!
