### ISSUE TITLE
Ender IO, Thermal Dynamics and Refined storage compatibility

### ISSUE THREAD

**Issue by Trellinane** [CompactMods/CompactMachines#370]
Having trouble getting the Ender IO conduits, Thermal Dyanmics Flux Ducts to connect.

Refined Storage cables connect but don't seem to provide network access inside the Compact Machine even when the Controller is chunk loaded.

I have read the compatibility disclaimer but the above cables and network access used to work in prior versions of the mods in 1.12.2 minecraft. (compactmachines3-1.12.2-3.0.12-b215 in particular).

Really, really love how this mod lets me have a cleaner more organized base and hoping something can be done to resolve this.  Thanks.

Compact Machines version: compactmachines3-1.12.2-3.0.13-b236
Forge version: 14.23.5.2784
I am not using Optifine: confirmed
Link to Crashlog: not a crash
Screenshot (if possible): N/A

Description of the problem including expected versus actual behavior:
Ender IO energy conduits, Thermal Dynamics Flux Ducts not connecting to compact machines any more.

Refined storage cables connect but don't seem to provide network access inside the compact machine even when the controller is chunk loaded.

Steps to reproduce:
Place flux ducts or conduit next to compact machine block and they will not connect whether tunnel is present or not.  Inside compact machine tunnel does not see conduit or duct.

**Comment by Ant95** [comment]
Ender IO conduits works well for me (both energy and RS), I can't tell for flux ducts. On which side of the machine are you trying to connect conduits ?

**Comment by davenonymous** [comment]
Please be more precise and include screenshots of the setup that isn't working.
For example: The steps to reproduce obviously won't work since you are not putting anything on the inside of the machine. I also don't know what you mean by "tunnel does not see conduit".
