### ISSUE TITLE
What item pipes can be used?

### ISSUE THREAD

**Issue by DeereJ18** [CompactMods/CompactMachines#371]
Can I have a list of the pipes that i can use to run items in and out of the compact machine? I would like to use the buildcraft pipes, but they pop items out of the compact machine and seem to not be compatible.

**Comment by davenonymous** [comment]
Everything that is using Forge Capabilities is compatible.
Sorry, there is no good possibility to create a list of supported mods unless done manually.
But item routing in particular is often fixable by adding in a buffer chest/hopper at one side of the tunnels.

**Comment by DeereJ18** [comment]
I'll try the buffer chests good idea!
