### ISSUE TITLE
just a question about machines log

### ISSUE THREAD

**Issue by Alfatossa** [CompactMods/CompactMachines#374]
Is it normal that my server is running a unloading chunks if dimension 144 (which is the compact machines dimension) an counting bed spawn machines id and spawn location?
It does that every minute
Screenshot:
![2019-02-14 11_13_43-re_start - viewing server private - patboil](https://user-images.githubusercontent.com/15367208/52800384-a7f35a00-3049-11e9-95c8-05c1da67129b.png)

**Comment by davenonymous** [comment]
Your server should not be loading and unloading the world every minute.
The log lines are the lesser problem in regards to that.
Do you have some sort of auto-unload worlds mod running?

**Comment by Alfatossa** [comment]
running ftbu and force the chunkloaded chunks to be unloaded when team
member is offline but we disabled the chunk claiming in the dimension
