### ISSUE TITLE
Can no longer easily use item frames on machine blocks

### ISSUE THREAD

**Issue by urikkiru** [CompactMods/CompactMachines#378]
**Compact Machines version**:
 compactmachines3-1.12.2-3.0.14-b247.jar
**Forge version**:
14.23.5.2781
**I am not using Optifine**:
No optifine.

**Description of the problem including expected versus actual behavior:**
It used to be possible(in 3.0.13-b236) to use item frames on the front of a given compact machine. You could right click through the item frame and it would allow you to interact with the machine. This no longer functions.

**Steps to reproduce:**
Place an item frame on the front of a compact machine block. Right click on the item frame instead of the block. It will not function as it previously did. You have to target the block itself now.

**Comment by davenonymous** [comment]
Oops. Wrong issue id in commit.

**Comment by davenonymous** [comment]
Sorry, works as intended. You should never have been able to click through item frames.
