### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by KAfable** [CompactMods/CompactMachines#381]
**Compact Machines version**: b249
**Forge version**: 2795
**I am not using Optifine**
**Link to Crashlog**: [https://gist.github.com/Vyraal1/7052f0d51f97a9acffa1edd2a1700a33](url)
**Screenshot (if possible)**: [here](url)

**Steps to reproduce:**
According to the player they setup an item conduit to a tunnel and started to pull from it which prompted the crash.

**Comment by KAfable** [comment]
https://gist.github.com/Vyraal1/7052f0d51f97a9acffa1edd2a1700a33

Trying link again since it was malformed

**Comment by davenonymous** [comment]
I will look into it soon.

**Comment by KAfable** [comment]
Hey, just wondering any update on this?

**Comment by davenonymous** [comment]
I am unable to reproduce this and the crash report does not look like it would be related to item transfer via tunnels. This is really weird. Does this occur regularly or did it happen just once?

**Comment by SnaveSutit** [comment]
I've been having this issue with Mekanism's item transport pipes and logistical sorters.
I can get a crash log later tonight
