### ISSUE TITLE
Crash (StackOverflowException) with 2 tunnels and 2 compact machines directly interacting (Tested with EnderIO)

### ISSUE THREAD

**Issue by HumanGamer** [CompactMods/CompactMachines#382]
**Compact Machines version**: 1.12.2-3.0.15-b249
**Forge version**: forge-14.23.5.2825
**I am not using Optifine**: Optifine is NOT installed
**Link to Crashlog**: I didn't think I'd need this as it's very easy to reproduce and it's partly shown in the video. It got deleted when I deleted the Twitch profile. If needed, I can just cause the crash again and get another one, just ask.
**Screenshot (if possible)**: Not necessary as I included a video.

**Description of the problem:**
Placing a compact machine next to another compact machine, and both compact machines have 2 tunnels in such a way where the 2 machines interact: using EnderIO cables inside both machines will crash the game with a StackOverflow exception while updating neighbor blocks. It is most likely some kind of infinite loop where one compact machines notifies the other and then that one responds by notifying the other over and over until it crashes.

**Expected Behavior:**
The game should continue to run without crashing.

**Actual Behavior:**
The game crashes and the world will crash the game every time you load it. You have to load a backup or use MCEdit to move one of the compact machines somewhere else.

**Steps to reproduce:**
I recorded a video on how to reproduce it. This includes installing the mods on the Twitch Launcher all the way until the crash and shows some of the crashlog. [Video Link](https://www.youtube.com/watch?v=KTuiuGS-C6o)

**Extra Notes:**
This may be a bug with EnderIO but even if it is, there should be some kind of handler for this kind of issue in the Compact Machines for future compatibility. (Such as sending a chat message like "Hey there was an error with Compact Machines! Please make a github issue with the logs/compactmachinescrash.log file" or something like that)

Keep in mind that I've only tested this issue with EnderIO, other mods or even vanilla blocks could potentially have the same issue.

**Comment by davenonymous** [comment]
Thanks for the detailed report! I will look into it soon!

**Comment by HumanGamer** [comment]
Happy to Help :)

**Comment by davenonymous** [comment]
I've adapted your PR a bit, would you mind retesting this with the latest build >= b256 from [here](https://www.dropbox.com/sh/7yyd9dgii1epibu/AADARWLwgjOBu9wU-zZVHp-ra?dl=0).

**Comment by HumanGamer** [comment]
I tried compactmachines3-1.12.2-3.0.15-b256.jar and compactmachines3-1.12.2-3.0.15-b260.jar but the issue still occurs.

Do you have discord btw? It would be easier to communicate.

**Comment by davenonymous** [comment]
I'm unable to reproduce the issue myself using the latest build 262.

**Comment by HumanGamer** [comment]
@thraaawn It no longer crashes for me in 262. Thank you.

I'd still like to speak to you about Minecraft Modding in general on discord, if that's possible. (and yes I know it's offtopic but github doesn't have PMs lol)
