### ISSUE TITLE
Failure of the sponge server 1.12.2

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [CompactMods/CompactMachines#386]
When you press RMB on CM, the server crashes.

Minecraft 1.12.2
Forge 2822
Sponge 2822
CM 263

https://gist.github.com/xxxLEOPARDxxx/6c3115e323045fb1643f57d9bf84cb98

**Comment by davenonymous** [comment]
Same as 387 and fixed in 5dcee83.
