### ISSUE TITLE
Items keep spawning

### ISSUE THREAD

**Issue by realmayus** [CompactMods/CompactMachines#388]
**Compact Machines version**: Not sure, the one that's in the Enigmatica modpack v.1.6.0
**Forge version**: 14.23.5.2796
**I am not using Optifine**: yes
**Screenshot (if possible)**: [here](https://streamable.com/mkeiq)

The video above tells everything, Items keep dropping after crafting. After re-joining the server the dropping stops.

**Comment by davenonymous** [comment]
This was merely a client-server sync issue and will be fixed in the next release.

If you need this fix sooner you can grab a current build from [here](https://www.dropbox.com/sh/7yyd9dgii1epibu/AADARWLwgjOBu9wU-zZVHp-ra?dl=0), but be aware that these are unreleased preview builds.
