### ISSUE TITLE
When there is a 'industrial-foregoing' laser in the space, opening the GUI will crash

### ISSUE THREAD

**Issue by KuroPeach** [CompactMods/CompactMachines#392]
When there is a 'industrial-foregoing' laser in the space, opening the GUI will crash
https://paste.ubuntu.com/p/vNWKNw5wtG/

**Comment by Jetlaw** [comment]
[crash-2019-04-25_18.11.49-client.txt](https://github.com/thraaawn/CompactMachines/files/3118097/crash-2019-04-25_18.11.49-client.txt)
[crash-2019-04-25_18.11.49-server.txt](https://github.com/thraaawn/CompactMachines/files/3118098/crash-2019-04-25_18.11.49-server.txt)

![image](https://user-images.githubusercontent.com/173054/56755669-f4fd5600-6787-11e9-8599-0abc9dc06c06.png)

Same issue. Industrial Foregoing Laser Drill/Base in a Maximum Compact Machine leads to crash when opening the GUI.

Playing in Sky Factory 4 Modpack.

Would hypothesise that it can't render the laser beams that connect the Laser Drills with the Laser Base.
