### ISSUE TITLE
Client disconnect when previewing a machine containing YABBA barrel

### ISSUE THREAD

**Issue by vegeta897** [CompactMods/CompactMachines#395]
**Compact Machines version**: 3.0.17-b267
**Forge version**: 14.23.5.2836
**I am not using Optifine**: Not using Optifine
**Link to Crashlog**: https://gist.github.com/vegeta897/585c3fb991b26b375c7a6f9cf09f4944
**Screenshot**: https://i.imgur.com/mZyY8CF.png

**Description of the problem including expected versus actual behavior:** Attempting to view a compact machine's GUI by right clicking with anything other than the personal shrinking device causes client to drop from the server, when a YABBA item barrel is present inside the machine. Removing the barrel from the inside of the machine allows the GUI with preview to work fine.

**Steps to reproduce:** 
1. Create and place a compact machine block
2. Enter it by right clicking with the personal shrinking device
3. Place a YABBA item barrel anywhere inside
4. Exit with the personal shrinking device
5. Right click the machine with anything but the personal shrinking device

In case it is relevant, I am using YABBA version 1.1.2.50

**Comment by davenonymous** [comment]
I can't imagine that it does not throw any kind of error in the log. Could you have a look please?
Could you try updating to the latest build of the mod and retest this? Downloads are [here](https://www.dropbox.com/sh/7yyd9dgii1epibu/AADARWLwgjOBu9wU-zZVHp-ra?dl=0).

**Comment by vegeta897** [comment]
Sorry about that, I've added the link to the log.

I'll try the latest build and report back.

**Comment by vegeta897** [comment]
I updated both server and client to build 274 and it still crashes in the same way. Log: https://gist.github.com/vegeta897/4850730a412c519f5e69280a820141ff

**Comment by davenonymous** [comment]
Thanks for the additional info.
I'll take a look!

**Comment by davenonymous** [comment]
I can easily reproduce this and the commit should fix it.
Would you be willing to retest this real quick and confirm it works?

Edit: The build with the change included should be ready in a few minutes at the same dropbox location.

**Comment by vegeta897** [comment]
Sure, which build # is it?

**Comment by davenonymous** [comment]
275, it's available now.

Oh, and the only fix was to not render the barrel in the first place, i.e. it should be invisible. But also not crash anymore.

**Comment by vegeta897** [comment]
Yep, that worked. I've already redesigned my system to not need barrels inside anyway, but thanks for all the prompt responses and fix!

**Comment by davenonymous** [comment]
You are welcome. I hope to release a new build over the weekend. Cheers!
