### ISSUE TITLE
Incorrect Blocks Shown in Preview

### ISSUE THREAD

**Issue by votex09** [CompactMods/CompactMachines#396]
**Compact Machines version**: compactmachines3-1.12.2-3.0.18-b278
**Forge version**: 14.23.5.2815
**I am not using Optifine**: true
**Link to Crashlog**: Not Applicable
**Screenshot (if possible)**: [Attachment](https://user-images.githubusercontent.com/10671494/57423560-1aec1700-71da-11e9-9f9a-3c2fa87121d9.png)

**Description of the problem including expected versus actual behavior:**
Machine preview shows the above example.  Added mod to Project Ozone 3, No resource pack in use. Walls should be a different texture and are transparent to allow viewing. Basically all blocks from the mod in preview are incorrectly textured.
**Steps to reproduce:**
View a preview of a machine.

**Comment by davenonymous** [comment]
Hey, jupp, I've seen that in my own playthroughs as well, but can not replicate in my dev environment.
I think it is related to block mappings, which get confused if you add/remove mods.

I'm sure there are people who could instantly tell me whats wrong, but at the moment I'm clueless. Going to look into it again over the coming days.

**Comment by alyti** [comment]
This occurs due to NotEnoughIDs mod, it's doing sketchy shit with block mappings resulting in this kind of stuff. There's not much you can do, unless you want to dig around NEIDs internals.
