### ISSUE TITLE
[Suggestion] Save direction player is facing

### ISSUE THREAD

**Issue by UncleOwen** [CompactMods/CompactMachines#398]
Hi,

when you shift-right-click the Personal Shrinking Device (PSD) while inside a Compact Machine (CM), your current position is saved. When you re-enter the same CM, you are placed in the exact same position.

Would it be possible to also save the direction you are facing?

Let me draw you a mental picture. I have a CM sitting in one of my rooms, on the west wall. Whenever I enter the CM, I am (roughly) facing west. I naturally build my stuff on the western wall of the CM, so that I can easily see and interact with it.

Now I decide to redecorate the room the CM is in. This time I place it on the east wall. I might have to change the tunnels, but that is easy. But every time I enter the CM, I am facing (roughly) east, and have to turn around to interact with my stuff!

**Comment by SashaGelert** [comment]
+1, I would love to see this added for similar reasons.
