### ISSUE TITLE
Suggestion: OP private bypass

### ISSUE THREAD

**Issue by shinyafro** [CompactMods/CompactMachines#399]
Suggestion to allow operators to access private machines.

**Comment by davenonymous** [comment]
Should already be possible via the command:
```/compactmachines3 machines view```

**Comment by shinyafro** [comment]
You cant actually enter, but you can view. Its nice to be able to enter, is all. I did manage to import this into my ide and just add a check to the isAllowedToEnter() Method. Seemed to work just fine when i ran the server.
`        //Allows OPs to enter the machine if it is whitelisted.
        if ( FMLCommonHandler.instance().getMinecraftServerInstance().getPlayerList().getOppedPlayers().getEntry( player.getGameProfile() ) != null ) {
            return true;
        }`
But i'm a scrub when it comes to coding tbh so i have no idea what to do past there. Fortunately it works serverside so i can just drop that in the server jar. 

Oh and yeah the teleport buttons seem to disconnect me from the server when i use them.

**Comment by SizableShrimp** [comment]
This is fixed as of https://github.com/SizableShrimp/CompactMachines/commit/394cef40ad078517d25a19c4b0bcd6ef8e72e7d2 using the exact same approach listed above. However, I haven't yet investigated if this is ever called client-side, which may not work if they are opped and this is called client-side (e.g. in a menu).

**Comment by SizableShrimp** [comment]
I just confirmed by looking at the source code that it is not possible for this to be called on the client. This solution confirmed works.

**Comment by robotgryphon** [comment]
Needs final testing after the merge of #439. Will close after this is confirmed operational.
