### ISSUE TITLE
Suggestion: Allow non-op player to recover their own compact machine

### ISSUE THREAD

**Issue by HerobrineXia** [CompactMods/CompactMachines#401]
Although there is commands for OP to recover the compact machine, it is not convenient for non-op player to ask for helps from OP. Therefore, if possible, I suggest to make players have access to view their own compact machine and recover them by using another unused same type of compact machine.

**Comment by DabbingEevee** [comment]
I agree, ive had wayyyy to many players ask me to recover a machine. A interesting side effect of this would be that there would be a way to get two machines leading into one room. But honestly I think that would lead to some very interesting machines

**Comment by SashaGelert** [comment]
It would be interesting if a player could right-click on open air with the PSD and if they have a correct size, blank/unassigned/new compact machine in their inventory, bind it to any compact machine they personally previously owned. 

@DabbingEevee Compact machines default behavior is if a new link is created to an existing machine, the old link is automatically removed, so there shouldn't be any conflict.  Personally this would be a nice feature to have though, as I tend to use Dimensional Doors to link one machine (my storage room) to several locations, using the ability to copy rifts. The only issue there, and perhaps with any many-to-one system is the way back out is one-to-one, ie: you have to go back to the same point you entered from, not one of the other linked points.  This is one reason I also use RFTools in my machines.

**Comment by robotgryphon** [comment]
Commands to do this now exist in v4.3.0 (`/compactmachines give`) - 4.4.0 will likely be the version I expand this support to entangled machines, where the PSD is a gateway to show all a player's owned rooms.
