### ISSUE TITLE
Tunnel does not crafted in SpongeForge Server

### ISSUE THREAD

**Issue by yaroslav4167** [CompactMods/CompactMachines#403]
**I'm Use:**
**Compact Machines version**:1.12.2-3.0.18-b278
**Forge version**:14.23.5.2838
**I am not using Optifine**:no
**SpongeForge**: 1.12.2-2838-7.1.7-RC3774
**Description of the problem including expected versus actual behavior:**
A tunnel must be created. But, after starting the creation, an invisible block appears.
**Steps to reproduce:**
[Video reproduce](https://youtu.be/uKwVsEaT4gI)
After this procedure, in a hopper position arise invisible block.

**Comment by yaroslav4167** [comment]
I replace in recipes hopper to other block (piston) and craft started work normaly.

**Comment by Hanoverfist** [comment]
Same issue as above. Crafting creates a ghost block in center of area and no tunnels. Works fine in singleplayer.

**Modpack:** Interactions 1.9.1
**Compact Machines:** 3.0.18-b278
**Spongeforge:** 1.12.2-2838-7.1.8-RC3964
**Forge:** 14.23.5.2838

**Comment by robotgryphon** [comment]
Closing this as an issue with SpongeForge since other users have not reported this issue and Forge itself works fine. If someone can get me a server dump or a server setup to reproduce on SF, I can reopen and investigate, but likely to be low priority as CM4 is being worked on.
