### ISSUE TITLE
keeps saying invalid block

### ISSUE THREAD

**Issue by thealmghtyweeb** [CompactMods/CompactMachines#406]
**Compact Machines version**: version 3
**Forge version**:1.12.2
**I am not using Optifine**:no
**Link to Crashlog**: none
**Screenshot (if possible)**: 

**Description of the problem including expected versus actual behavior:** expected: the hologram for the 11x11x11 area is created. :actual nothing happens and when i right click my printers, it just says invalid block and when i clear that area it goes 2 blocks higher

**Steps to reproduce:**make 11x11x11 setup, right click the printers

**Comment by Spongman** [comment]
i see the same thing, it says `Invalid block in field area @x,y,z: Air`

really confused, is it supposed to say that?

**Comment by Luke270601** [comment]
Getting a similar error as well. Though this is that and setup producing an area greater than 3x3 just give a missing block error

**Comment by robotgryphon** [comment]
We're going to need more information to troubleshoot. If this is still happening with the latest build (b278) then please attach logs or a screenshot showing the issue. We can reopen the issue if it's still present.
