### ISSUE TITLE
Exit machine teleported into results in exiting from wrong machine

### ISSUE THREAD

**Issue by Samfucious** [CompactMods/CompactMachines#408]
[This is a fun one. found while playing ATM3-Remix on 1.12.2. I hope this is the right place to report it]

Scenario: Placing a teleporting device (I used Waystones for this) in a compact machine, with other provisions and equipment, and carrying the machine around while exploring to use as a mobile waypoint. (Machine A)

Have another compact machine back at the home base serving another utility function. (Machine B)

Enter, then exit machine B. Teleport into then exit machine A.

Expected result: Player is standing outside of machine A.
Actual result: Player is standing outside of machine B.

Possible fix: Add a list of "exit locations" for the player keyed off the machine id.

Difficulty for fixing: Any fix might conflict with implementing. https://github.com/thraaawn/CompactMachines/issues/148

(Great work on this mod, by the way.)

**Comment by robotgryphon** [comment]
This needs some final testing before it can be formally closed; merging the overhaul PR should include a fix for this.
