### ISSUE TITLE
Compatibility Documentation?

### ISSUE THREAD

**Issue by ghost** [CompactMods/CompactMachines#418]
**Read then remove this section**:
Do not create an issue if you have not tried fixing it by using the latest version of the mod!

Also make sure you've read the full readme [here](https://github.com/thraaawn/CompactMachines/blob/1.12.1/README.md) on github.

If you are reporting a bug regarding the interior view of the Machines, the one you get when you right click a machine, do not report it to any other mod author involved in the crash. It is highly likely that its CM3s fault.

**Compact Machines version**:
**Forge version**:
**I am not using Optifine**:
**Link to Crashlog**: [here](url)
**Screenshot (if possible)**: [here](url)

**Description of the problem including expected versus actual behavior:**

**Steps to reproduce:**

This isn't a 'bug' strictly speaking, but it is an issue I'm having. I looked it up, and it seems like at some point there was an update adding some form of compatibility for Botania, and there is also compatibility for other mods (ie, Mekanism.) However, it is also mentioned that Botania compatibility is disabled by default, and the default config file doesn't fill out whatever line would be needed to enable it, as well as there not being any mention of how this would actually *work*. If this could be clarified, that would be great.

**Comment by davenonymous** [comment]
Botania support was in the 1.7.10 version.

**Comment by ghost** [comment]
Just a note for anybody looking at this and wondering how to get mana into/out of a compact machine: if you have Extra Botany, the Manalinkium can do interdimensional, wireless mana transport with the right multiblock.
