### ISSUE TITLE
Bug when entering or exiting a compact machine

### ISSUE THREAD

**Issue by Rithenar** [CompactMods/CompactMachines#421]
**Compact Machines version**: compactmachines3-1.12.2-3.0.18-b278.jar
**Forge version**: ForgeMultipart-1.12.2-2.6.2.83-universal.jar
**I am not using Optifine**: I am using Optifine
**Link to Crashlog**: No crash
**Screenshot (if possible)**:  https://i.imgur.com/Lv7DaOK.png  &  https://i.imgur.com/OOxmz63.png

**Description of the problem including expected versus actual behavior:**
When I enter or exit a compact machine, I am placed in a void world. The first link shows the Overworld and even though you can see my  base in the mini map, the only thing I can see is the sun/moon. The second screenshot is the compact machine. I see the square in the mini-map, but again I only see void. This happens sometimes when I first enter a compact machine, but it also happens after I have been inside and out the compact machine normally a few times.  The only way to fix this is to restart the client.

**Steps to reproduce:**
1- Place Compact Machine
2- Use Personal Shrinking Device on Compact Machine
3- Sometimes enter the machine, sometimes end up in a Void world

Repeat in reverse for when I exit the machine.

EDIT: I am using the mod in the MC Eternal modpack.

**Comment by MasterEnderman** [comment]
This also happens to players who don't use Optifine. I have the same problem in my pack aswell.

**Comment by robotgryphon** [comment]
Possibly a crossmod interaction with how chunk syncing is interacting with the client. I've seen this a few times with several teleportation mods; will give this a reproduce attempt in a dev environment but it might be tough with the number of mods involved.

**Comment by SizableShrimp** [comment]
I think it would be nice to know whether this was singleplayer or multiplayer for testing purposes. This might just be simple server desync or something larger if on a singleplayer world. I personally don't think this is the fault of CM3 since it happens on both ends.

**Comment by ghost** [comment]
The bug occurs on Forge 2855 server running compactmachines3-1.12.2-3.0.18-b278.jar
A possible workaround is to **be mid-air or moving** while entering and exiting.
