### ISSUE TITLE
1.7.10 Crash

### ISSUE THREAD

**Issue by GhostShot3** [CompactMods/CompactMachines#428]
Compact Machines version:compactmachines-1.7.10-1.21
Forge:1.7.10 - 10.13.4.1614
Optifine:OptiFine 1.7.10 HD U E7
Crashlog:[here](https://pastebin.com/raw/NKM5gV2A)
Screenshot:Not possible.

I play on minecraft 1.7.10 with 200+ Mods, and when i add this mod the game freezes on the loading screen and crash, when i remove the game load normally.

**Comment by robotgryphon** [comment]
> cpw.mods.fml.common.LoaderException: java.lang.RuntimeException: Invalid id 8642 - maximum id range exceeded.
>	at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:239)

Judging by the stack trace, this is an issue with the amount of mods and blocks being registered, not with CM2 itself. Due to the age of CM2 and Forge Support for current versions, going to close this one.
