### ISSUE TITLE
compactmachine＆randomthings error

### ISSUE THREAD

**Issue by mu-mei** [CompactMods/CompactMachines#430]
**Read then remove this section**:
Do not create an issue if you have not tried fixing it by using the latest version of the mod!

Also make sure you've read the full readme [here](https://github.com/thraaawn/CompactMachines/blob/1.12.1/README.md) on github.

If you are reporting a bug regarding the interior view of the Machines, the one you get when you right click a machine, do not report it to any other mod author involved in the crash. It is highly likely that its CM3s fault.

**Compact Machines version**:
1.7.10-1.21
random things version
2.2.4
**Forge version**:
10.13.4.1614
**I am not using Optifine**:
not
**Link to Crashlog**: [here](url)
crashlog=null
**Screenshot (if possible)**: [here](url)
title

**Description of the problem including expected versus actual behavior:**
If you put compactmashines and random things, the title will be displayed, but you can not put it in any world
I'm sorry, gooogle translation

**Steps to reproduce:**
compactmashines and random things
sorry i'm first

**Comment by SizableShrimp** [comment]
Sorry, this doesn't make sense to me. I'm not sure what the issue is.

**Comment by mu-mei** [comment]
If you insert a compact machine and random things at the same time and start Minecraft, you can enter the title screen but not in the world, it will return to the title screen I'm sorry, I don't know what I don't understand I'm sorry, I'm sorry (´ ； ω ； ｀)

**Comment by SizableShrimp** [comment]
Please send your debug.log file so that we might be able to find the issue.

**Comment by mu-mei** [comment]
What is debug.log?

**Comment by robotgryphon** [comment]
If this is still an issue, you will be able to find the debug log file under the `logs` directory in your Minecraft folder. The easiest way to get to that is likely to use the Options screen (main menu) and open the resource/texture pack folder, and navigate up one level.

**Comment by SizableShrimp** [comment]
I just realized this is for CM1 (1.7.10). I personally won't be providing support for this issue.
