### ISSUE TITLE
Preview problem showing fences

### ISSUE THREAD

**Issue by Mathiousse** [CompactMods/CompactMachines#432]
**Compact Machines version**: 
Last available Curseforge version for 1.12.2
**Forge version**:
14.23.5.2847
I am not using optifine

**Screenshot (if possible)**: [here](https://user-images.githubusercontent.com/58639269/100497785-f52cb700-315d-11eb-8858-7b5e356fef31.png)![image]

Preview of the compact machine, when right-clicking it with nothing, is showing a bunch of fences and brings down my pc to its knees, brining it to 2-3 fps
Expected results: a preview without any 'walls' blocking vision / fences at all

**Steps to reproduce:**
Playing on McEternal, right-click without anything in hand on a maximum compact machine

**Comment by robotgryphon** [comment]
This looks like a bad mod interaction; something about the chunk syncing is having a real bad time. Is this single player, or in a multiplayer environment?

**Comment by SizableShrimp** [comment]
I believe I've seen this before, but I don't remember much else outside of that. It could be the data corrupting when being sent to the player over network, when the object is being created, or when the object is being serialized on server or deserialized on client.

**Comment by Mathiousse** [comment]
It's been a long while so i'm not quite sure but i'd say its in both environments 
Modpack being MCEternal if that has to do

**Comment by robotgryphon** [comment]
Do you know if it happened with new worlds, or only on existing worlds that have had work put into them? If it's reproduceable in a brand new world, I might be able to put together a debug version and try to get some more information.

**Comment by SizableShrimp** [comment]
> 
> 
> It's been a long while so i'm not quite sure but i'd say its in both environments
> Modpack being MCEternal if that has to do

Did this happen every time you opened the machine preview or only sometimes? I'd like to get your save file if you still have it and also if you would be willing to try to reproduce it again.

**Comment by Exotik850** [comment]
I am also having this issue but it's instead purpur half slabs? 
![image](https://user-images.githubusercontent.com/60969639/104868428-eca85f80-5908-11eb-8724-9a1f45fed396.png)

**Comment by robotgryphon** [comment]
If anyone has a world download and have a mod list, both of those would be very helpful in debugging this one. I can obviously get a mod list from Eternal, but adding the entire list of mods will take time. Better if it's known how many mods are actively being used in the affected environments.

**Comment by Acru** [comment]
Having the same issue in DD&SS 8.0r1.  If the blocks in the front weren't rendered it would not be as much of an issue.  The AE2 blocks and others inside seem properly rendered, just not the 'Solid Compact Machine Wall' rendering as stairs, the one with the tunnel attached that rendered as a sideways pillar and any regular 'Compact Machine Wall' blocks placed inside.

![Screenshot 2021-07-08 22 27 42](https://user-images.githubusercontent.com/626242/125023681-9658e580-e03c-11eb-83e9-d26fde1f5496.png)

It has always rendered as the same stairs block for me using this pack.

**Comment by Destarianon** [comment]
I have the same issue, on MC Eternal 1.5, which is using Compact Machines version "compactmachines3-1.12.2-3.0.18-b278"
In my case this is occurring in multiplayer on a dedicated server. I can reproduce the issue in single-player, and in a brand new world. No pack customization has been done, so I am working with the native MC Eternal pack.

![image](https://user-images.githubusercontent.com/6621236/161653816-1707a248-ebfa-412d-b46e-9bb5a4018416.png)

In my case, the solid walls appear as what seems to be the bottom half of a door. Solid blocks render fine in actual view. Nested machines also show this preview problem.

Anything I can do to assist with diagnosis? This is a huge deal for the way I play the game, as I use compact machines excessively.

**Comment by Apceniy** [comment]
> Anything I can do to assist with diagnosis? This is a huge deal for the way I play the game, as I use compact machines excessively.

You could try to isolate the problem by removing the mods that don't cause the issue I think
