### ISSUE TITLE
[Mekanism] Universal cables not outputting from machine

### ISSUE THREAD

**Issue by xRebellion** [CompactMods/CompactMachines#433]
**Compact Machines version**: 1.12.2-3.0.18-b278 (3.0.18) (Part of the FTB University Modpack)
**Forge version**: 8.0.99.99
**I am not using Optifine**: I am not using Optifine
**Screenshot (if possible)**:
![image](https://user-images.githubusercontent.com/32483348/100516485-cb53ae80-31b6-11eb-94b0-ce3c126cadfe.png)
![image](https://user-images.githubusercontent.com/32483348/100516467-afe8a380-31b6-11eb-9e73-5951ff12f4a7.png)

**Description of the problem including expected versus actual behavior:**
When using mekanism cables or pipe to try to transport energy/items, it does not work. Though using a form of storage directly works fine. 
And also, a side bug - The One Probe shows wrong mekanism pipe/cube type for CM blocks.
**Steps to reproduce:**
1. Place a mekanism pipe onto a tunnel on the CM dimension (with supplied power)
2. Place another outside.
3. Notice that items / energy does not get transported when both sides have pipes. Pipe-Storage works fine, though.

**Comment by darkelfe14728** [comment]
There is a workaround: use a chest / energy cube / gas tank againt compact machine / tunnel, the items / energy / gas will be accessible.

But fix the source problem will be great.
