### ISSUE TITLE
save schema You do not have the permission to use this command

### ISSUE THREAD

**Issue by BalloS-Twok** [CompactMods/CompactMachines#434]
**Compact Machines version**: 1.12.2-3.0.18-b278
**Forge version**: 

**Description of the problem including expected versus actual behavior**:
If I try to save a schema I get the message that I dont have the persmission to do this,

Im the server op

Other commands like view I can use without problems.

**Comment by robotgryphon** [comment]
Please provide a Forge version (do not use latest, an actual version number) and a debug log file for more information. A screenshot from Minecraft would also be helpful.

**Comment by Thamos** [comment]
I had the same problem when playing the modpack McEternal. The "solution" is probably documented anyway, but since the first google result for the problem is this issue: You have to be op AND be in gamemode creative. 
So a quick  "/gamemode creative" before using the command and it works.
