### ISSUE TITLE
Copy Shape command not working on largest field

### ISSUE THREAD

**Issue by TruePureGold** [CompactMods/CompactMachines#440]
**Compact Machines version**:1.12.2-3.0.18-b278
**Forge version**:1.12.2
**I am not using Optifine**: I am not using optifine
**Link to Crashlog**: Didnt Crash
**Screenshot (if possible)**:
![image](https://user-images.githubusercontent.com/76762588/103328615-3c7fcd80-4aa5-11eb-93b8-1fd40c436cff.png)

**Description of the problem including expected versus actual behavior:** Was unable to to copy the shape with /compactmachines3 recipe copy-shape command on largest size field

**Steps to reproduce:** use /compactmachines3 recipe copy-shape on largest size field

**Comment by SizableShrimp** [comment]
Hi, what are the dimensions on this field? I can investigate the issue.

**Comment by TruePureGold** [comment]
Its the maximum size one which i believe is 13 x 13 x 13 for the bounding box area 
Also sorry for late response

**Comment by SizableShrimp** [comment]
I apologize for my delayed response. Can I have your `debug.logs` file from this session? If you have played after experiencing this bug, you will need to replicate it again and then send this file as it would have been overwritten. A list of mods/the modpack you are using would also help.

**Comment by TruePureGold** [comment]
Hi the zip contains the debug log (i think its the right file) as well as a mod list 
[Requested files.zip](https://github.com/CompactMods/CompactMachines/files/5827769/Requested.files.zip)
I also searched my issue up before i posted and i could only a reddit post about someone having the same issue but there was no comments, would you like me to put a link to that post, it might not be that useful though
edit:
id like to mention that it could be just the modded block im using in the recipe its self, the recipe only contains blocks from avaritia and extended crafting,
also i dont mind if your response it late as you obviously would be busy with other issues and just your life in general, have a nice day btw
