### ISSUE TITLE
Cant access to machines

### ISSUE THREAD

**Issue by frant4nk** [CompactMods/CompactMachines#441]
**Compact Machines version**: compactmachines3-1.12.2-3.0.18-b278.jar
**Forge version**: 1.12.2
**I am not using Optifine**: not using
**Link to Crashlog**: didnt crash
**Screenshot (if possible)**: 

**Description of the problem including expected versus actual behavior:** Our atm3 world just broke itself, so after a roll back players cant access to dim144 even restoring old regions files or creating a new one, also tried to use /compactmachines3 machine view to get a block linked to the machine, but doing that we can access to a few machines, with others we just fail to access on it, tping back to overworld with a nausea effect, also the stuff of that machines is not shown in the gui of the command, just the owner and his coords

**Steps to reproduce:**

**Comment by SizableShrimp** [comment]
Hi, this seems like your `WorldSavedDataMachines.dat` has corrupted. Please go to your world folder then `data` folder and restore `world\data\WorldSavedDataMachines.dat`. This should fix the issue.
