### ISSUE TITLE
[1.16.4] shrinking device not working as manual

### ISSUE THREAD

**Issue by Zygus42** [CompactMods/CompactMachines#442]
**Compact Machines version**:compactmachines-4.0.0-alpha.6
**Forge version**:1.16.4 35.1.29
**I am not using Optifine**: correct

**Description of the problem including expected versus actual behavior:**
Personal Shrinking Device right or left click just doesn't seem to work at all.

**Comment by robotgryphon** [comment]
This is not yet implemented in the 1.16 version due to large rendering changes. Added to the backlog.

**Comment by robotgryphon** [comment]
Partially implemented in commit 95564afb01575a189ed1289a1b38b49301f2b7a8; sections are not fully in but the guide now works as one would expect. Will be resolved in the next mod release.
