### ISSUE TITLE
No machine data loaded; report this (1.16)

### ISSUE THREAD

**Issue by predundant** [CompactMods/CompactMachines#450]
**Compact Machines version**:compactmachines-4.0.0-alpha.6
**Forge version**:36.0.14
**I am not using Optifine**:correct
**Link to Crashlog**: not a crash
**Screenshot (if possible)**: 

![CM Error](https://user-images.githubusercontent.com/32441423/107254284-c738de00-69fc-11eb-884c-af3f048d467f.png)

**Description of the problem including expected versus actual behavior:**  Set up a farm system inside a CM on our test server.  Went to enter the CM the next day and got a "No machine data loaded; report this" message.

**Steps to reproduce:** Tried to reproduce using a new CM.  I was able to enter the new one, and when I went back to the original I was able to enter but it was empty.

**Comment by robotgryphon** [comment]
Just so I have all the information possible:
* Is there a server debug log that you can provide? Pastebin preferred.
* Was the server modified in any way between the two entries? Shut down, mods changed, anything of that sort?

**Comment by predundant** [comment]
Sorry for not providing the information in time.  We'll try the new version and let you know if the issue persists.
