### ISSUE TITLE
[1.16.5] Possible to teleport outside Compact Machines with the Travel Anchors mod

### ISSUE THREAD

**Issue by NielsPilgaard** [CompactMods/CompactMachines#457]
**Compact Machines version**: compactmachines-4.0.0-beta.2
**Forge version**: 1.16.5-36.0.46
**I am not using Optifine**: Correct
**Link to Crashlog**: Not applicable
**Screenshot (if possible)**: [Screenshot](https://user-images.githubusercontent.com/39351347/110522593-ba053100-8119-11eb-8dd0-635961905e27.png)

**Description of the problem including expected versus actual behavior:**
The mod Travel Anchors makes it possible to teleport outside Compact Machines using either the enchant it adds, `Teleporting` or the Staff of Travel.

**Steps to reproduce:**
Go into a Compact Machine
Get a Staff of Travel with energy
Teleport outside by right clicking with the Staff of Travel in-hand (might be shift-right-click, can't remember ^^)

Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/1616

**Comment by robotgryphon** [comment]
Going to keep this one open until I can solve this; it not really a bug so much as unimplemented functionality right now. Goal here is to eventually add a generic entity teleport event to Forge, so I can catch any modded teleporters and disable them from happening.

**Comment by robotgryphon** [comment]
Update: Shrimp has made a new set of events to help this out. Tracking it here:
https://github.com/MinecraftForge/MinecraftForge/pull/7694

**Comment by VenerableTimeWanderer** [comment]
As a thought why not use this to be able to teleport to compact machines on the wall teleporting through or just teleport out.

**Comment by robotgryphon** [comment]
Should now be closed due to teleport handling in commit aef304d7a71cf8e36387ee8ac6a0fa84965e8c32, which blocks all non-tp and non-ender pearl teleports.
