### ISSUE TITLE
1.16.5 server crash

### ISSUE THREAD

**Issue by oguh43** [CompactMods/CompactMachines#458]
**Read then remove this section**:
Do not create an issue if you have not tried fixing it by using the latest version of the mod!

If you are reporting a bug regarding the interior view of the Machines, the one you get when you right click a machine, do not report it to any other mod author involved in the crash. It is highly likely that it is Compact Machines' fault.

**Compact Machines version**:4.0.0-beta.2
**Forge version**:1.16.5-36.0.54
**I am not using Optifine**: I am.
**Link to Crashlog**: [https://pastebin.com/dLZ1hr9x](https://pastebin.com/dLZ1hr9x)

**Description of the problem including expected versus actual behavior:**
Problem: server crashes
Expected: server does not crash
**Steps to reproduce:**
restert server, place dia cube
we think its due to
a) player disconnecting in one of them
b) updating forge

**Comment by oguh43** [comment]
Update, diamond cube is corrupted

**Comment by SizableShrimp** [comment]
Seems like somehow we have some code that is recursively being called. I'll check this out.
