### ISSUE TITLE
1.16

### ISSUE THREAD

**Issue by ghost** [CompactMods/CompactMachines#459]
Please, update for 1.16 fabric <3
Its a very perspective modloader with good optimization and graphics (For example, on forge fps=50, on fabric its 750) (Really) (mostly, cause sodium mod) 
I think, many developers will soon switch to it

P.S sorry for off-top

**Comment by robotgryphon** [comment]
We aren't even fully upgraded to Forge yet. Fabric is certainly not on our radar at this time.

Project opinion aside, I will not be doing this myself. Forge is highly mature and is aiming to be all-inclusive; Fabric, in my opinion, only serves to fragment the modding community, and does not offer an enticing reward for the port.
