### ISSUE TITLE
Support for AE2 cables to connect to a tunnel

### ISSUE THREAD

**Issue by Floweynt** [CompactMods/CompactMachines#461]
How would this be done, and do I need to write my own mod for it?

**Comment by robotgryphon** [comment]
Compact Machines offers a tunnel API for usage in defining a new Tunnel Definition. You can find it here:
https://github.com/CompactMods/CompactMachines/tree/1.16.x/src/main/java/com/robotgryphon/compactmachines/api/tunnels

This is also released to GitHub packages and the releases tab as an API jar.

You most likely want to make an implementation of `ICapableTunnel` to hook into an existing capability network. Once you have the definition, register it by listening to the Forge registry event, and the mod will create the tunnel item and implementation using the new definition.

**Comment by VetLee** [comment]
@robotgryphon It's too bad I gave up on this idea. I miss it so much :(
