### ISSUE TITLE
[1.16.5] Teleporting to a Compact Machine traps the player there

### ISSUE THREAD

**Issue by NielsPilgaard** [CompactMods/CompactMachines#465]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/1953

**Description of the problem including expected versus actual behavior:**
The player who reported this issue used the command `/sethome`  inside his Compact Machine to be able to teleport to it. When he teleported to it and attempted to leave using his Personal Shrinking Device, it wouldn't teleport him out.

I understand that the Personal Shrinking Device has no way of knowing where to teleport you, so I guess this is more of a PSA than a bug report.

Bonus info: `/sethome` is from the mod FTB Essentials

### Mod and Forge Versions
**Mod Version:** 4.0.0 beta 2
**Forge version:** 1.16.5 - 36.1.0

**Steps to reproduce:**
1. Step 1
2. Step 2
3. Step 3

**Comment by robotgryphon** [comment]
I'm conflicted on this. On one hand, I'm wanting to close this as it's definitely not an issue with CM4 itself. On the other hand, I'm tempted to add a config option and make it so if the player is not supposed to be in a machine and they do this, it'll kick the player out and whack them with a bunch of damage.

**Comment by GingerSnap-xx** [comment]
> I'm conflicted on this. On one hand, I'm wanting to close this as it's definitely not an issue with CM4 itself. On the other hand, I'm tempted to add a config option and make it so if the player is not supposed to be in a machine and they do this, it'll kick the player out and whack them with a bunch of damage.

Kick player out to where? 
I like the idea though. Maybe if not set, the default is to just print a message like "How did you even get in here?!"

**Comment by robotgryphon** [comment]
I'd use the safe spawn mechanic that beds and respawn anchors use, if the boot-players-out-of-machines option was on.

**Comment by robotgryphon** [comment]
I'm going to convert this to the Discussions feature, since this is less a bug and more a design conversation.
