### ISSUE TITLE
ATM6 1.16 Commands to recover machine

### ISSUE THREAD

**Issue by Ioncloud9** [CompactMods/CompactMachines#467]
Maybe I'm just missing something, but I cant seem to find any commands for recovering a compact machine the /compactmachines command doesn't seem to be listed anywhere I tried looking through eveything with /help and didnt see anything the resembled a compact machine command...

**Comment by SizableShrimp** [comment]
You are not missing something. There are no commands on 1.16 yet; they are in the works.

**Comment by ZeMilkmann** [comment]
@Ioncloud9 A workaround would be to give yourself the block manually. This worked for me. Replace [ID] with the number of the compact machine.

/give @s compactmachines:machine_maximum{cm:{coords:**[ID]**}}

**Comment by robotgryphon** [comment]
These commands were finalized in 4.3.0 (1.18.2). Closing this issue; see above for a workaround for 1.16 releases.
