### ISSUE TITLE
Redstone Tunnel Out 1.16

### ISSUE THREAD

**Issue by Batman313v** [CompactMods/CompactMachines#470]
I have been messing around with this for a few hours now and I cannot get the redstone tunnel to change to out. I've tried clicking the corner with empty hand, not empty hand, with different blocks. Everything I can think of. I cannot figure out how to get the tunnel to switch. I noticed on curseforge It says the tunnels are half implemented and talks about item tunnels but not Redstone. And in the Project board it says redstone tunnels are done so I'm guessing I missed something. I have the latest 4.0.0-beta.2.jar

Thank you

**Comment by robotgryphon** [comment]
There is no way to convert to a redstone out tunnel. They don't exist yet; I prioritized redstone in for people wanting to shut off automation from outside a machine.

Sorry the project board didn't make this clear; that's my bad. Redstone out will have the rest of its bindings added in the next release; right now, nothing in the machine code will help.

**Comment by Batman313v** [comment]
Ok, Thank you for the clarification. Can't wait for the next release!
