### ISSUE TITLE
Datapack becomes broken and world cannot be loaded after leaving world and re-entering world in singleplayer

### ISSUE THREAD

**Issue by Darkmega18** [CompactMods/CompactMachines#476]
**Description of the problem including expected versus actual behavior:**
The problem is, in my modpack of 200+ mods, when I added compact machines and a couple other new things I found that when I start a world, save it, and then leave and then re-enter the world it comes up with one of these:
https://cdn.discordapp.com/attachments/528429004630523904/846348466196054036/unknown.png

I spent most of my night into early morning restarting my minecraft 10s of times between watching videos to take the edge off taking out different combinations of the later mods I added and it settled on this mod being the culprit, or atleast potentially the catalyst to the real culprit causing the bug to occur. (such was the case with another issue I reported to another mod. :V)

**### Mod and Forge Versions**

**Mod Version:** 4.0.0 beta 2
**Forge version:** 36.1.23

**### Issue Information** (it isn't a crash, per-se)
**Link to Crashlog**: there is no crash. only a lack of existence. and a dump that comes out in the latest.log about biomes:
https://pastebin.com/KWNtQGar

**Steps to reproduce:**
1. load minecraft and create a world.
2. play for a moment then save and exit the world.
3.  Try to start the world again and notice it's broken.

Worlds which have already been broken by the bug remain broken even after removing compact machines as far as one or two tests were able to discern.

**_Other details and observations:_**
upon searching the word "datapack" I chanced upon this issue:
https://github.com/CompactMods/CompactMachines/issues/438

I have reason to believe it might be related to this but further testing with compact but without rocketry didn't return a working world after saving, and I'm not sure I have the energy to do more iterative testing for the 3rd all nighter in a row for another of these world destroying bugs. :V I can probably provide a zip of the modpack in it's current state thought which you can iterate with yourselves and to see any other mods which could be trouble units.

**Comment by SizableShrimp** [comment]
What other mods did you add and can you provide a zip as stated?

**Comment by Darkmega18** [comment]
I will provide it in a sec then. was just having a break. but I'm gonna try some iterative testing right now, but I'll send the pack along once it's compressed.

**Comment by Darkmega18** [comment]
[darkmega's testing pack-0.0.1.zip](https://github.com/CompactMods/CompactMachines/files/6534050/darkmega.s.testing.pack-0.0.1.zip)

here you go. load it into curse or multiMC and take a look also.

**Comment by Darkmega18** [comment]
that didn't take long.
![image](https://user-images.githubusercontent.com/8104689/119389442-fc004500-bd0e-11eb-8963-4d934f8465a3.png)
![image](https://user-images.githubusercontent.com/8104689/119389469-03275300-bd0f-11eb-89cc-6cb1cfcac50b.png)
any guesses? :V it resurfaced with my first group of guesses.

is it caused by too many biomes and other dimensions? when I split up the selection it didn't occur anymore on either group. but that should be most of my mods that add more biomes or other dimensions.

**Comment by Darkmega18** [comment]
this is so weird...
I got the issue with this subset:
![image](https://user-images.githubusercontent.com/8104689/119399689-88fdcb00-bd1c-11eb-9baa-ebc077e66c07.png)

but taking majrusz and library by itself with compact does nothing.
taking towers and waystones by themselves  with compact does nothing.
and taking the "better" stuff by themselves with compact does nothing.

but taking them as a set, explodes the game with compact machines in tow. I play for just enough time to find a way to kill myself in frustration in survival (lol) then save then reload the map and it has the datapack error thing.

edit:

OK, got it down to majruz and library plus towers and waystones with compact = issue...
I'm completely confused how and why it's those instead of all the other biome mods before hand but... welp... :V

https://pastebin.com/vhxUzNpG

theres what the datapack fail bug looks like with just those few mods, incase theres any difference I'm not picking up in my tiredness. :V

**Comment by SizableShrimp** [comment]
Please remove the logs from this comment and extract it to a paste site. It makes the issue unreadable. I've narrowed down the issue to a bug with `majruszs_difficulty`. This needs to be reported to them. The issue is they are not correctly registering their structures to the flat world generation, which Compact Machines utilize for the Machine dimension. This is not an issue with Compact Machines and needs to be reported to them.

Relevant logs with Blame installed: https://gist.github.com/SizableShrimp/2113d067d2bd69210474bf8e9b93cdb5

**Comment by Darkmega18** [comment]
modders and your paste sites... but ok, thank you. odd that it didn't occur when I had only maj and the library together with compact though. I must've stuffed something up on that iteration. :V anyways, I'll just reference them this and hope they fix it soon.

**Comment by SizableShrimp** [comment]
From my short testing, it doesn't crash unless the other 2 mods are present. However, the issue is still on the creators of the `majruszs_difficulty` mod. The logs shown only appear with Blame installed.

**Comment by Darkmega18** [comment]
Ah, intriguing that it'd choose to crash when the towers are also present. do you think the towers have issues with flatlands too?

**Comment by SizableShrimp** [comment]
No, only `majruszs_difficulty`. You can report the issue on their github [here](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues)

**Comment by Darkmega18** [comment]
yep-yep, I'm already there now writing it up. 

*sigh* I wonder if I'll be able to play the video game tomorrow? :V this is like the 3rd elusive super bug I've gotten slapped by in a row.
