### ISSUE TITLE
Leaving CM cause massive lags

### ISSUE THREAD

**Issue by lazystudent3** [CompactMods/CompactMachines#477]
**Description of the problem including expected versus actual behavior:**

_I am using CurseForge and playing on Singleplayer in this case._
Game works just fine until I decide to enter my CM where I have farm (I have 4 CM and it only happens with one). Nothing special happens until I leave it. Then BOOM my whole minecraft world start to get huge lags. It doesnt matter if I just turned game on or if i play from 2/3 hours. When I forget and enter this CM, I can only restart whole modpack because game becomes unplayable. Game have problems to render chunks, tick after F3 is jumping from 20 before to +100 after. I checked without optifine, without texture, with claimed and unclimed chunks. 

Expected behavior : No lags. Don't have to restart game after getting out of CM.

### Mod and Forge Versions

**Mod Version:** compactmachines-4.0.0-beta.2.jar
**Forge version:** 1.16.5 - 36.1.24

### Crash Information
**Link to Crashlog**: game did not crush 
**Screenshot (if possible)**: https://imgur.com/a/JRhX6rS

**Steps to reproduce:**
1. Get into CM
2. Leave CM

PS: My first time posting issue. I apologize for every mistake I made.

**Comment by SizableShrimp** [comment]
Please send the modpack and the world save for testing

**Comment by lazystudent3** [comment]
I play on All The Mods 6 + Time in the bottle mod. Here are mods folder and save of my world.


https://easyupload.io/m/jeenwe
password is  4321

**Comment by bribri69** [comment]
Hello,

Yesterday our server crashed cause of compact machine.
I found in the overworld (same coordinates as the campact machine in its dimension) items that were in the compact machine : https://imgur.com/a/GkqIAix
We do not see it in the screen but I was able to take the seeds that fell in the void...
For information we are playing on ATM6Sky
Maybe it will help you to understand wher is the problem

**Comment by alphamercer** [comment]
Hello.

Have a similar issue on a Enigmatica 6 server. When i place a CM block in a world, there is a huge tps loss, from 20 to 10 and tick time increases 40ms -> 90ms. When I enter CM world or break CM blocks it becomes fine.
