### ISSUE TITLE
Tunnels not crafting, leaving glitch block

### ISSUE THREAD

**Issue by NexusTraigorne** [CompactMods/CompactMachines#479]
I have attempted to crafting the tunnels for this 4 seperate times in 4 seperate locations. I should note first that I am playing SevTech ages on a multiplayer server and have brought this up with my mods aswell.

I am in age 5 and have already crafted the max sized 13x13 compact machine twice and several of the redstone tunnels thinking that was to transfer power (lol) I created a large scale power generation room in the first but must be able to get these tunnels to use them.

So I placed the compact wall down in the 3x3 hologram with the 8 redstone around it, hopper on top and then tossed the redstone in. It shows black smoke particles and poofs the materials away. Leaving nothing behind but a tiny glitched invisible particle that when walking forward, I stand on top of with step assist and stay floating there. You cannot place a block there either and water leaves an air pocket around that block. 

So I've moved my projectors 3 more seperate times in varying sizes all with the same result. This item will not craft for me.

One of the mods suggested that it is sevtechs progression system and that I do not have the compact machines unlocked yet but they let that thought go after showing them my progression tree (lol)

### Mod and Forge Versions
(Playing on GD launcher but powered by forge)

**Mod Version:** CM3-3.0.18-b278
**Forge version:** 1.12.2 - 14.23.5.2854

Has not crashed

**Steps to reproduce:**
1. Step 1 place projectors in any acceptable size
2. Step 2 place ingredients, 1 compact wall, 1 hopper on top and 8 redstone surrounding the wall
3. Step 3 throw 1 redstone into the hologram

**Comment by robotgryphon** [comment]
Going to need a lot more information here to troubleshoot this; given the age of CM3 I highly doubt it's the crafting mechanic itself. Can you provide a server debug log, as well as a mod list or link to the modpack in question?

As for the ghost block - that's the crafting preview, it's what renders the shrinking animation as the craft is happening. So, based on that, the mod IS beginning the craft - my guess is that there's chunk protection or something weird blocking the tile there from registering properly.
