### ISSUE TITLE
Crash due to faulty chunk loading code

### ISSUE THREAD

**Issue by ghost** [CompactMods/CompactMachines#480]
After some playtime at 1.16.5 inside this compact world server started to crash repeatedly after I join the game.
And I was unable to recover anything inside compact worlds which is really sad, forced to remove mod from server.
https://gist.github.com/ternsip/ee0d65b403a92231a13bccf11e9fa083

**Comment by robotgryphon** [comment]
Looks like an issue with the rooms handling chunk loading. There should have been a config option to disable that.

Other than that, I'm not actually seeing CM code at fault here. Looks like an overloaded server or something. Will pass this by the Forge team.

**Comment by ghost** [comment]
After mod removal it started working. The bug was like - server starts ... all ok, Player enter the game (who's already in wrong dimension). Server loop in one thread TPS stops 60 seconds pass -> no reaction -> crash. 
watchdog reported on this mod and logically it should be somewhere there, because after removal it repaired successfully. And it started after I put two compact machines inside other compact machine (docker in docker)  and left the main box
