### ISSUE TITLE
Server freezes when placing compact machine inside compact machine

### ISSUE THREAD

**Issue by Aurif** [CompactMods/CompactMachines#481]
**Description of the problem:**
In some cases, when placing a compact machine inside of a compact machine, then exiting and breaking the outer machine, the server completely freezes. You can still move around, but blocks don't drop items, mobs don't move, and you can't leave the game without killing minecraft. Sometimes the save can also become corrupted, leaving you unable to load it again (it's stuck on the loading screen forever), which makes it really dangerous.

This could be the same issue as #480, but due to the lack of details on that report I'm not closing this one just yet.

### Mod and Forge Versions
**Mod Version:** 4.0.0 beta 2
**Forge version:** 1.16.5 - 36.1.66
*Tested without other mods present, issue still occurs.*

**Steps to reproduce:**
1. Place machine 1 and machine 2 (any sizes will do)
2. Enter, exit, and then brake machine 1
3. Enter machine 2, place machine 1 inside it
4. Exit machine 2, try to break it
5. Everything is frozen

**Comment by robotgryphon** [comment]
Sorry to get back to you late on this, but are there any debug logs from the freezes? It'd at least tell me if there's a loop or deadlock happening on the server.
