### ISSUE TITLE
Crash entering and leaving compact blocks

### ISSUE THREAD

**Issue by Joshernoob** [CompactMods/CompactMachines#483]
Version: compactmachines-4.0.0-beta.2.jar/  compactmachines-4.0.0-alpha.8.jar

4.0.0-beta.2.jar- with this version whenever i try to go in the compact blocks it kicks me out of game, after reload i'm in them (same thing happens trying to leave)

4.0.0-alpha.8.jar- seems this version lets me in the compact world but on outside on top of all the 'solid' blocks meant for it, trying to leave game crashes

Pastbin of current mod loadout: https://pastebin.com/B2ipMQyq

although if I'm to guess only Time is up, Deep Dark Dimension or World Border as there the only one that effect other dimensions

**Comment by robotgryphon** [comment]
Likely related to #480 and #481, where chunkloading is wrong. In the meantime, try turning off chunking in the server configuration. (`saves/world/serverconfig/compactmachines-server.toml`) for now. I'm in the process of improving that code for the next release.

**Comment by Joshernoob** [comment]
> Likely related to #480 and #481, where chunkloading is wrong. In the meantime, try turning off chunking in the server configuration. (`saves/world/serverconfig/compactmachines-server.toml`) for now. I'm in the process of improving that code for the next release.

Id say its like them sadly turning off chunk loading would mess with the Modpack I'm making as this mod the main mod for it and chunk loading will be needed.
although if the next release should fix it ill wait until then
