### ISSUE TITLE
Renaming in Anvil

### ISSUE THREAD

**Issue by varadinn** [CompactMods/CompactMachines#484]
When renaming any size machine in anvil it does do the rename however once you place the machine it no longer has that name. It defaults back to the default name.

**Comment by robotgryphon** [comment]
Added as of commit da83c13aa9f32798c810886a701025043def5ee8, intended to be released in 4.3.1 with some other minor features and bugfixes. Rename a name tag in an anvil and use that on machines connected to owned rooms.
