### ISSUE TITLE
You fumble with the shrinking device, to no avail.

### ISSUE THREAD

**Issue by quasarea** [CompactMods/CompactMachines#486]
### Mod and Forge Versions
**Mod Version:** 4.0.0 beta 2
**Forge version:** 36.2.4

**Description of the problem including expected versus actual behaviour:**
I attempted to do enter machine located inside of other machine but getting "You fumble with the shrinking device, to no avail." message instead.

Is this not implemented yet for 1.16, if so is it on horizon, or I should rather build my base without it?

**Comment by robotgryphon** [comment]
This is part of the nested machines update, which is targeted for beta 3. See #468 for progress tracking.

**Comment by quasarea** [comment]
Didn't know about this.

Placed few machines in single one, seemed to work (not that I could enter, just they were as a blocks one in the other).

After server restarted its no longer starting, 3 consequent crashes with same dump https://pastebin.com/8sqFEvwZ

Guess need to remove its dimensions :/

**Comment by robotgryphon** [comment]
Crashing appears to be the same as #480 as well. That's also on the list for next release - that one seems to be deep in Forge chunk loading code.
