### ISSUE TITLE
Weird Crash

### ISSUE THREAD

**Issue by Demsli** [CompactMods/CompactMachines#489]
Here`s the crashlog: https://pastebin.com/EpD1tycC

Happened after server restart. CM version: compactmachines-4.0.0-beta.2. CC version: compactcrafting-1.0.0-beta.6

I have experienced a crash with compact crafting and waystones before, but fixed it by moving waystones to a different chunk. This looks like a different issue. Would really like an advice how to fix it. Thank you in advance:)

**Comment by robotgryphon** [comment]
Very likely a dupe of https://github.com/CompactMods/CompactCrafting/issues/45 or at least closely related.

**Comment by Demsli** [comment]
The crash was addressed and fixed in version v1.0.0-beta.7 (have not done any testing myself though)
