### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by SEDALLARI** [CompactMods/CompactMachines#490]
when i click install in the curse forge page is said this
![hu - copia](https://user-images.githubusercontent.com/86386149/143084909-0be65018-0efc-4b07-b02d-2e5342bfb6f9.PNG)
s

**Comment by robotgryphon** [comment]
Cannot reproduce, and beta 2 has been out for months now. This is an issue with Curseforge, not the mod. Sorry.

**Comment by SEDALLARI** [comment]
> Cannot reproduce, and beta 2 has been out for months now. This is an issue with Curseforge, not the mod. Sorry.

thanks
