### ISSUE TITLE
Create mod passive belt transport

### ISSUE THREAD

**Issue by lookolookthefox** [CompactMods/CompactMachines#494]
Belts by the Create mod are unable to transport items while the player is not in a machine. All other functions of the mod work fine, but item transport does not work.

**Mod Version:** 4.0.0 beta 2
**Forge version:**  36.2.4

**Steps to reproduce:**
Build a system with a belt that transports items and leave the machine, there is now no more transport.

**Comment by robotgryphon** [comment]
May be an issue with how create handles its ticking and chunkloading; admittedly CM4's chunkloading is fairly basic right now. Have you tried placing a dedicated chunkloader down inside the machine in question?

**Comment by quasarea** [comment]
FTB Teams chunk loading wasn't working for me inside machines, flux plugs / mechanism anchors worked fine then.

**Comment by djmattyg007** [comment]
Is there a way to transport Create mod's rotational stress capacity through a compact machine tunnel?

**Comment by RealMangorage** [comment]
> Is there a way to transfer Create mod's rotational stress capacity through a compact machine tunnel?

No there is not unfortunately.

**Comment by AlphaMode** [comment]
> Is there a way to transfer Create mod's rotational stress capacity through a compact machine tunnel?

Mind if I use this to make a addon seems like a neat idea

**Comment by RealMangorage** [comment]
> > Is there a way to transfer Create mod's rotational stress capacity through a compact machine tunnel?
> 
> Mind if I use this to make a addon seems like a neat idea

The reason why its not possible right now is because Create uses its own System and not Forge's Capability System

**Comment by AlphaMode** [comment]
Well yes I know why I am asking if I can turn it into a addon

**Comment by RealMangorage** [comment]
> Well yes I know why I am asking if I can turn it into a addon

I would assume you can. Best to ask Nano though.

**Comment by robotgryphon** [comment]
Deleting off-topic discussion and cleaning up this issue prior to a 1.16 issue window closure. 

@lookolookthefox Please let me know if this is still an issue with the suggested workaround, if no response is made by 8/15/22 this will be fully closed.
