### ISSUE TITLE
Machines generate new ID when placed

### ISSUE THREAD

**Issue by budd308** [CompactMods/CompactMachines#497]
### I am not using performance mods.

- [X] Confirm

### Description

I placed a maximum level machine, entered it, and built a farm. I picked it up, and when I place it back down it generated a new room. I manually spawned myself the maximum machine with an NBT tag of "machine_id: 1" which was the original machine I made, and tried again with the same result. I then paid attention to the ID before and after I placed, entered, and picked up the machine and have deduced the issue arises when I place the machine down and not when I pick it up.

As an additional note, I am playing on the modpack called All The Mods 7 on curse forge, I reached out on the mod pack Discord page but didn't get a response about my issue.

Edit:
I am playing on a dedicated server with another friend, he has not tried using the compact machines yet.

### Mod Version

4.0.0 beta 3

### Forge Version

1.18.1 Forge 39.0.10

### How to reproduce

1.Place and enter a machine
2.Pick up machine block
3.Place and enter machine

**Comment by robotgryphon** [comment]
Fixed this in beta 4. Root cause was the item NBT was generated with `machine_id`, but the placement data was still looking for that tag in a now-defunct `cm` group.
