### ISSUE TITLE
Blocks Have No Effective Tool

### ISSUE THREAD

**Issue by Klebestreifen** [CompactMods/CompactMachines#498]
### I am not using performance mods.

- [X] Confirm

### Description

See https://github.com/AllTheMods/ATM-7/issues/202

In order to shorten the official channels, I am forwarding the issue here. I have opened the ticket first at ATM7, because I am not clear about mod interactions. However, sooner or later it will end up here anyway.

### Mod Version

4.0.0 beta 3

### Forge Version

Minecraft v1.18.1 - Forge v39.0.10

### How to reproduce

1. Place a CM or a Wall
2. Try to break it (in survival)

**Comment by robotgryphon** [comment]
Please try updating to beta 4; some of the data files were regenerated and have likely fixed the issue.

**Comment by Apceniy** [comment]
I think you can close the issue, the latest version seems to work fine about that
