### ISSUE TITLE
No tunnels or tools..

### ISSUE THREAD

**Issue by PtitCrissGaming** [CompactMods/CompactMachines#505]
### I am not using performance mods.

- [X] Confirm

### Description

There's no tunnel or any way to take blocs from the compact world..

### Mod Version

4.0.0

### Forge Version

39.0.66

### How to reproduce

1.
2.
3.

**Comment by robotgryphon** [comment]
Tunnels are being worked on in 1.18. It's the next item being release, even; for now, use something like flux networks, tesseracts, ender chests, or entangloporters.
