### ISSUE TITLE
Can't enter Compact Machines

### ISSUE THREAD

**Issue by Chucko573** [CompactMods/CompactMachines#506]
### I am not using performance mods.

- [X] Confirm

### Description

I ran into an issue in Enigmatica 8 and the modpack dev asked me to post it here.  

Upon updating Enigmatica 8 from version 1.04 to 1.05 Beta, I could no longer enter any compact machines, nor the the Compact Machine dimension show in TPS reports.  

I tried deleting the Dimensions folder of my world as requested by the modpack dev with no change.

Also, in any NEW world I create, Compact Machines works just fine.

### Mod Version

4.0.0 beta 4

### Forge Version

1.18.1 - 39.0.14

### How to reproduce

1.  Create new world in Enigmatica 8 version 1.04
2.  Place and enter a compact machine
3.  Copy or update world to Enigmatica 8 version 1.05 Beta
4.  Try to enter Compact Machine

**Comment by robotgryphon** [comment]
Good news for you. I've identified a mod or two that can cause this,and have already found a solution. It's currently under test in 1.18.1 so once I can clean up the implementation, it'll be ready to go.

For now, I've found that adding information into the level.dat file with an nbt editor can fix the issue. Will upload some info to the wiki shortly.

**Comment by robotgryphon** [comment]
Please try the following (make a backup of your saved world before doing so!): https://github.com/CompactMods/CompactMachines/wiki/1.18---Reregistering-Dimension

**Comment by Chucko573** [comment]
> Please try the following (make a backup of your saved world before doing so!): https://github.com/CompactMods/CompactMachines/wiki/1.18---Reregistering-Dimension

This fixed it.  Thank you.
