### ISSUE TITLE
Bee's are not loading in a claimed chunk. (Inside Compact Machines Mod) (FTB Chunk Loader)

### ISSUE THREAD

**Issue by Remn1c** [CompactMods/CompactMachines#508]
### I am not using performance mods.

- [X] Confirm

### Description

I have my bees moved to a compacting machine to reduce lag, but the bees only are producing combs when I am in the compact machine. This might be another mod problem, but it appears as if the bees only work if there is an actual person present in the active chunk. Idk if this the right place to put this, but its a start. I just want to be able to get my combs without having to deal with the frame drops.

### Mod Version

39.0.78

### Forge Version

39.0.78

### How to reproduce

1.Enter compact machine
2.Setup bee production with ender chest
3.Leave
4. Bee's not producing product anymore once left

**Comment by robotgryphon** [comment]
Please confirm which mod version you are using (1.16.5 - beta 2 or 1.18+), as well as if you have tried loading the chunk via other mods (FTB Chunks, Weirding Gadget, etc).

**Comment by robotgryphon** [comment]
Closing this as it's been almost 2 months with no reply; if you still need help, please reopen or join the Discord. Thanks!
