### ISSUE TITLE
Mekanism Cables not Transferring Energy 

### ISSUE THREAD

**Issue by Brayden551** [CompactMods/CompactMachines#512]
### I am not using performance mods.

- [X] Confirm

### Description

I placed a mekanism energy cube inside a compact machine and connected it via an energy tunnel and mekanism cables to the outside. The cables connect but there is no energy transfer outside of the cube. I tried attaching cubes directly to the energy tunnels but that did not work either.

The same issue occurred when using mekanism item tubes with an item tunnel. The items were seemingly destroyed after entering the item tunnel.

### Mod Version

4.2.0

### Forge Version

1.18.2 - 40.0.52

### Screenshot (if available)

![image](https://user-images.githubusercontent.com/45325650/164565109-f2bd13ef-6bb8-4ec1-9a15-0927d7c70f12.png)
![image](https://user-images.githubusercontent.com/45325650/164565154-bf85666f-57a4-4bd3-8d2d-9c67b52e93f7.png)
![image](https://user-images.githubusercontent.com/45325650/164565976-583e33a9-8fa4-402b-8469-4ec63cb5c9b3.png)
![image](https://user-images.githubusercontent.com/45325650/164566010-8a93c4dc-21b3-4f0e-a28e-eea400498e75.png)

### How to reproduce

1. Place a mekanism energy cube inside a machine
2. Connect it to an energy tunnel via mekanism cables
3. Connect mekanism cables to the outside of the machine

**Comment by lyratcm** [comment]
Just ran into almost the same issue, the universal cable can transfer power into machine but a universal cable on the inside doesn't receive the power it seems using  something like integrated dynamic can revice that power perfectly well

**Comment by robotgryphon** [comment]
Have you tried setting the insertion/extract modes on the cables? The tunnels act like storage, mek won't pull from it automatically.

**Comment by Drausk2** [comment]
> Have you tried setting the insertion/extract modes on the cables? The tunnels act like storage, mek won't pull from it automatically.

i have the same problem, just tried it but doesen´t work ether.

**Comment by Shantarr** [comment]
Hello! Same issue, cannot get power or items in or out using universal cables or LV cables with tunnels in ATM7, v4.17

Also attempted energy cubes on internal and external face.

Also tried hoppers and chests.

Really love the idea of this mod and an super excited to use it!

**Comment by BigWiggles** [comment]
Having the same issue. Have tried changing the pipe to "pull" and still no luck. 

Using All The Mods 7 -  Can't receive power inside the machine using Mekanism, Powah, Pipez or Immersive Engineering.

**Comment by robotgryphon** [comment]
Merging this into #524 to ease triage, this requires a re-test after recent version releases
