### ISSUE TITLE
Entering cubes of the same type do not always create a new dimension

### ISSUE THREAD

**Issue by ghost** [CompactMods/CompactMachines#515]
### I am not using performance mods.

- [X] Confirm

### Description

Tested on All the Mods 7 using Compact Machine (Large) [Internal size 9x9x9]

Creating 16x Large cubes, placing them all down, and entering one after another does not create a new dimension each time, but duplicates an existing block, 50% of the time.

Blocks started with creating Machine #4 (first placed block), enter the next cube created #5, enter the next 2 cubes duplicated into #5.
Entering the next block created #6, and duplicated #6 two more times.

Entering the next several blocks, no issue up to Machine #12

Went back to craft more Large cubes, placing them all down and entering each one, duplicated #11 four times in a row.

### Mod Version

4.2.0

### Forge Version

40.1.0

### How to reproduce

1. Create and place down multiple types of one cube
2. Enter each cube separately or consecutively
3. Cube is duplicated into previously made cubes 50% of the time

**Comment by derrickmehaffy** [comment]
I have been able to confirm this, all new maximum machines will only link to id 7 machine

**Comment by ghost** [comment]
To add to this, when entering a new Cube and it does decide to duplicate an existing one, it will destroy all blocks inside as if a new one was made. Entering any of the duplicates will show all as being empty.

**Comment by robotgryphon** [comment]
Going to close and merge this into #513 since it seems closely related. For those following here, v4.2.0.11 (nightly build) has code that should significantly help this issue. Aiming to fix by v4.3.0.
