### ISSUE TITLE
Different machines keep taking me to the same spot

### ISSUE THREAD

**Issue by PrincessNorthern** [CompactMods/CompactMachines#518]
### I am not using performance mods.

- [X] Confirm

### Description

I have a large compact machine placed, and built a radioactive bee farm inside of it pumping into the overworld. This was working for 5 hours with no issues. I placed a small compact machine about 5 blocks away in the overworld, with the intent of building an emerald farm. When I tried to enter the small compact machine, it took me to the large machine (radioactive bee farm). I placed another small machine, to test again, and now somehow my large machine takes me to the small machine I intended as an emerald farm. I have no way to get back to my radioactive farm now, and am not getting any items from it. All of my machines say "Machine 3" now

### Mod Version

4.2.0

### Forge Version

1.18.2 - 40.1.19

### How to reproduce

1. Place one machine
2. Enter machine, mark/name with waypoint
3. Place a second machine
4. Enter it.
5. Takes you to the first machine.

**Comment by robotgryphon** [comment]
Please update to version 4.3.0, as it addresses this issue along with adding commands for rebinding machines.
https://www.curseforge.com/minecraft/mc-mods/compact-machines/files/3807656
