### ISSUE TITLE
Cant put compact machines in compact machines

### ISSUE THREAD

**Issue by Hotice03** [CompactMods/CompactMachines#519]
### I am not using performance mods.

- [X] Confirm

### Description

I am currently playing on seopolis the sea pack, and i just made compact machines, and whenever i place one inside another and use it it says "you fumble with the shrinking device to no avail it refuses to work" i am on a multiplayer server that i run, i have also tried it in single player. 

### Mod Version

4.0.0 beta 2

### Forge Version

1.16.5

### Screenshot (if available)

![unknown](https://user-images.githubusercontent.com/34260075/171078219-6282b7c3-d185-47f4-b5a7-7340a79478fd.png)

### How to reproduce

1. Make 2 compact machines
2. Place one down and go inside
3. Place the second one down while inside the first one and try to go inside

**Comment by robotgryphon** [comment]
This is expected behavior for 1.16. There were some hefty data changes involved with getting tunnels and nested machines working, and by the time it was sorted 1.18 was maturing.

**Comment by Hotice03** [comment]
so will it ever be updated to allow them in each other?

**Comment by robotgryphon** [comment]
At this time, no. As I said, the changes break world compatibility and 1.16 is currently winding down support in prep for 1.19's release by Forge. Sorry.
