### ISSUE TITLE
Cant connect mekanism/pipez energy to a compact machine

### ISSUE THREAD

**Issue by Hotice03** [CompactMods/CompactMachines#520]
### I am not using performance mods.

- [X] Confirm

### Description

So i am setting up compact machines within seopolis, and i have one that i have put a reactor inside so it took up less room in my base, and upon trying to get the energy out of the machine the cables will not connect i tried both item tunnels and redstone tunnels incase the update swapped their roles. 

### Mod Version

4.0.0 beta 2

### Forge Version

1.16.5

### Screenshot (if available)

![fdfasdfdsafsdafa](https://user-images.githubusercontent.com/34260075/171280617-abe72c4a-6126-4acc-97cb-8c1965e23b78.png)
![dsafdsafdsafsdaf](https://user-images.githubusercontent.com/34260075/171280620-fe598047-b228-46f8-ad5d-d4b0279f3087.png)
![fdafdsafadsf](https://user-images.githubusercontent.com/34260075/171280622-0503a21a-bf17-46ee-9754-978a7bdc9b0a.png)
![afdsafsd](https://user-images.githubusercontent.com/34260075/171280623-e00ed7f1-db65-484d-a4d8-650b8436fa85.png)

### How to reproduce

1. place power inside a compact machine
2. hook up a tunnel to it with a pipe
3. attach the pipes outside to get the energy

**Comment by robotgryphon** [comment]
Tunnels were not fully implemented in 1.16. They only worked with items and required a buffer to get any kind of compatibility with most pipes. It's recommended to use other mods for the 1.16 version, such as Flux Networks or Ender Chests.

**Comment by Hotice03** [comment]
we are playing on a modpack so it isnt that easy to do that.. so theres NO way to transfer energy?

**Comment by robotgryphon** [comment]
Not with Compact Machines itself; by the time I had a platform to finish this work, 1.18 was maturing and there were too many data changes to make it work smoothly for existing worlds.
