### ISSUE TITLE
Mekanism pipes (all types) not connecting to tunnels or machines

### ISSUE THREAD

**Issue by AgentKlunk2** [CompactMods/CompactMachines#522]
### I am not using performance mods.

- [X] Confirm

### Description

I am playing the modpack enigmatica 6 and have been unable to connect any mekanism pipes to the tunnels on the inside of machines, nor the outside of the machine
**edit:** I have found that none of the pipes from any of the other mods in the pack are working either.

### Mod Version

4.0.0-beta.2

### Forge Version

1.16.5 Forge 36.2.34

### Screenshot (if available)

![2022-06-04_00 42 06](https://user-images.githubusercontent.com/62008031/171983573-fec8283d-fe9e-4156-a380-b89f8b45bad3.png)
![2022-06-04_00 46 53](https://user-images.githubusercontent.com/62008031/171983574-c6af89a6-1d5c-49e3-9a73-80f18d7a2f8f.png)

**Comment by robotgryphon** [comment]
1. Wrong resource, there's a reason there's no recipe and it's called **Item** Tunnel
2. Tunnels were not finished in 1.16. Upgrade to 1.18.2.

**Comment by AgentKlunk2** [comment]
Can't upgrade it to 1.18.2, as I mentioned I am playing a modpack, and I am using an Item tunnel.

**Comment by NokiFux** [comment]
is there any way to get it working on 1.16 ?
