### ISSUE TITLE
No registry key for compactmachines:compact_world 

### ISSUE THREAD

**Issue by DwemerEngineer** [CompactMods/CompactMachines#523]
### I am not using performance mods.

- [X] Confirm

### Description

When using a server with only Compact Machines and SpongeForge, the server crashes with the error message while loading the world,
"Failed to find a registry key for the world type specified for world 'compactmachines:compact_world'! This is a serious issue as a mod or plugin has not registered it at the appropriate point beforehand, Aborting..."

### Mod Version

4.0 beta 2

### Forge Version

1.16.5 - 36.2.2.35

### Link to Crashlog

https://gist.github.com/attitus3/cafd4c753e74afc6c3f5d5b653e5b0b0

### How to reproduce

1. Launch a server with SpongeForge and Compact Machines

**Comment by robotgryphon** [comment]
Per Sponge's discord, this may be an issue on their side. They've asked anyone affected by dimension issues to upgrade Sponge for additional logging around the issue. 

To expedite, here's a Discord link for Sponge: https://discord.gg/sponge

**Comment by DwemerEngineer** [comment]
Since this was fixed on Sponge's end I'm going to close this issue
