### ISSUE TITLE
Mek cables nor Pipez engery pipes work with new version updated in Direwolf20s new pack

### ISSUE THREAD

**Issue by robertm1771** [CompactMods/CompactMachines#524]
### I am not using performance mods.

- [X] Confirm

### Description

Seems to be an issue on player side of world with tunnels as they seem to connect "inside the machine" In last version Energy pipes from pipez mod where working. 

### Mod Version

4.3.o

### Forge Version

1.18.2 

### Screenshot (if available)

![2022-06-07_13 09 57](https://user-images.githubusercontent.com/6488750/172443106-333649a9-ae79-499f-b78f-5bc0060d823c.png)
![2022-06-07_13 15 44](https://user-images.githubusercontent.com/6488750/172443315-7e1b9a39-f7e9-4249-824b-1d2353e7ca12.png)

### How to reproduce

1.
2.
3.

**Comment by Crimix** [comment]
I can also verify the bug on my server running the DW20 pack

When ever the server is restarted, the outside cable is not connected and will not connet until the tunnel inside has been removed from the wall and placed back again.

**Comment by IndianderJones** [comment]
How do you remove the tunnel. In my singleplayer world i can't. I'm playing ATM7.

**Comment by theizzer** [comment]
We are playing direwolf20's pack 1.18.2 with Compact Machines v4.3.0.

I don't know about the "server restart -> outside cable not connected" issue that Crimix mentioned, but it might be connected to this: When I place the cable (energy for example) outside without there being tunnel inside of the machine, it's not connected to the block - obviously, but it does not update after the tunnel is actually placed inside - so you have to replace the cable after that, too.

My other issue is that it seems that there is no chunk loading inside the compact machines dimension it seems like. I had to chunk load both the machine and the block inside overworld using the FTB Chunks mod. (My mini factories work like that, I will run out of force loaded chunks, tho!)

With this in mind - would it be possible that in case of server restart - the cables "update", but find out that there is no connection point, cause the machine is not chunk loaded, and therefore disconnect? 😄

**Comment by robotgryphon** [comment]
Several fixes are implemented in the current dev space for v4.4.0; of note is a fix for tunnels disconnecting, as well as adding in a chunkloader upgrade. Follow #general in [the Discord](https://discord.gg/abca3pDPvu) for better updates.

**Comment by robotgryphon** [comment]
Please verify this is still an issue in v4.4/v5 of the mod. Thanks!

**Comment by oliverrook** [comment]
Still an issue for me.
Using 4.4
Notably trying to use FTB Contraptions and powah cables do not work. haven't tried the mekanism ones yet.

It seems to work with the mekanism cables, but ONLY if you set it to push and pull on the outside. Automatic/Both will not work.
