### ISSUE TITLE
Mixins crash

### ISSUE THREAD

**Issue by iglee42** [CompactMods/CompactMachines#528]
### I am not using performance mods.

- [X] Confirm

### Description

I tried to launch my modpack with Compact Machine 4.30 but it crashed.

### Mod Version

4.3.0

### Forge Version

1.18.2-40.1.52

### Link to Crashlog

https://pastebin.com/V1zxJWF4

### How to reproduce

1.Launch Forge 1.18.2-40.1.52 with Compact Machine 4.30

**Comment by robotgryphon** [comment]
I cannot reproduce this with current versions of CM4; please retry with a newer Forge or the upcoming version 4.4, due for release tomorrow morning.
