### ISSUE TITLE
creative inventory "Chunkloader Upgrade" in "Destroy Item" slot

### ISSUE THREAD

**Issue by Vritra22189** [CompactMods/CompactMachines#536]
### I am not using performance mods.

- [X] Confirm

### Description

in creative mode inventory, 
there is a "Chunkloader Upgrade" in the "Destroy Item" slot.
survival mode is fine.

expect:
"Destroy Item" is vanilla, 
so I suppose "Chunkloader Upgrade" shouldn't appear in there?

### Mod Version

4.4.0

### Forge Version

1.18.2 - 40.1.0

### Screenshot (if available)

overlapped text and image
![1](https://user-images.githubusercontent.com/9210589/181199682-e357fd88-87a3-4e03-8daa-b47beb6ca0c7.PNG)

vanilla clear inventory still usable
![2](https://user-images.githubusercontent.com/9210589/181199695-7db34d65-42d5-406d-b14e-fbfc00b5d2d3.PNG)
![3](https://user-images.githubusercontent.com/9210589/181199701-3d4b51b0-fc0d-4e25-b584-94c03c739bce.PNG)

survival inventory is fine
![4](https://user-images.githubusercontent.com/9210589/181199707-3c236328-9b8b-4fd3-a209-b42c8f7b0a62.PNG)

### How to reproduce

1. using CurseForge client
2. fresh new custom profile, install compact machine only
3. new world and enter creative inventory

**Comment by RealMangorage** [comment]
This has been fixed, the fix will be in the next updated version.

**Comment by robotgryphon** [comment]
Closed with release of 4.5.0: https://www.curseforge.com/minecraft/mc-mods/compact-machines/files/3905502
