### ISSUE TITLE
Server can't be connected to by op's

### ISSUE THREAD

**Issue by TaeoG** [CompactMods/CompactMachines#537]
### I am not using performance mods.

- [X] Confirm

### Description

With the newest update of compact machines (4.4.0), trying to log into a server will boot you out with an internal exception, that doesn't show up in any of the logs on the server or client. This only happens if you're an OP. If you're already an operator you can't log in, if you're made an operator while logged in you'll get booted off, with a similar error.

### Mod Version

4.4.0

### Forge Version

1.18.2 - 40.1.54

### Screenshot (if available)

![compact](https://user-images.githubusercontent.com/641633/181393846-13e520bd-948d-400a-bc9f-6531cec749e8.PNG)

### How to reproduce

1. create a server, either remotely or locally, with just compact machines and forge
2. connect to it

**Comment by Merith-TK** [comment]
does your server utilize Luckperms or simular?

**Comment by TaeoG** [comment]
no, and this is reproducible on a fresh forge server with only compact machines on it

**Comment by Merith-TK** [comment]
Can you send the logs of both server and client, 

this means `latest.log`, honestly surprised this template doesn't ask for that...

**Comment by TaeoG** [comment]
are you unable to reproduce it?

**Comment by Merith-TK** [comment]
I am an fabric person, not an forge person, nor am I even an dev/contributor of this mod

The fabric port had an simular error except the client showed signs akin to an Chunk/Book ban, when infact according to server logs, an command registry had issues where it conflicted with Fabrics/Luckperms permission management.

Latest.Log allows for more insight for the developer to figure out exactly what the hell broke in your particular instance rather than relying on *assuming* the logs they get if they are capable of recreating this issue, are the same as yours,

**Comment by drakosoldier298** [comment]
No one can help without more details, please submit latest.log

**Comment by TaeoG** [comment]
the screenshot is all the details I can provide at this time, and unfortunately I've moved on to other debugging tasks after identifying compact machines as the source of this issue. If the issue proves to be unreproducible then that changes things

**Comment by AgentAny** [comment]
Same problem... This is in my Console.
With forge 1.18.2 - 40.1.68
[11:18:42] [Netty Epoll Server IO #9/ERROR] [minecraft/ArgumentTypes]: Could not serialize dev.compactmods.machines.upgrade.command.RoomUpgradeArgument@2919ef39 (class dev.compactmods.machines.upgrade.command.RoomUpgradeArgument) - will not be sent to client!
[11:18:42] [Netty Epoll Server IO #9/ERROR] [minecraft/ArgumentTypes]: Could not serialize dev.compactmods.machines.upgrade.command.RoomUpgradeArgument@68cd85c4 (class dev.compactmods.machines.upgrade.command.RoomUpgradeArgument) - will not be sent to client!

**Comment by Merith-TK** [comment]
that... is litterally the exact same error as on the fabric version when used with LuckPerms...

**Comment by Flatgub** [comment]
Also having this issue.
Seems to sometimes take the form of `io.netty.handler.codec.DecoderException: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: <garbage string>` and other times take the form of `io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(43756) + length(1) exceeds writerIndex(43756): UnpooledHeapByteBuf(ridx: 43756, widx: 43756, cap: 43756/43756)`

Log from the client side:
https://gist.github.com/Flatgub/7c84076bced06474dfd6cb81a6ab071f

Log from the server side
https://gist.github.com/Flatgub/2fec5043b6a98b09156fe922f28b313f

My modlist is literally just compactmachines-4.4.0.jar and nothing else

**Comment by Merith-TK** [comment]
yeah, exact same issue fabric had with luckperms... meaning forge is doing something to the Permissions API system

**Comment by Xplodin** [comment]
Getting this on forge as well. This bugged me for DAYS as I couldnt figure out what the cause was

**Comment by robotgryphon** [comment]
Closed with release 4.5.0: https://www.curseforge.com/minecraft/mc-mods/compact-machines/files/3905502
