### ISSUE TITLE
Crash when open room preview with prettypipe inside the room

### ISSUE THREAD

**Issue by PhamKun** [CompactMods/CompactMachines#540]
### I am not using performance mods.

- [X] Confirm

### Description

I attempted to right click on compact machine, which has pretty pipe form Pretty Pipe mod inside, without the personal shrinking device, it crashed the game (but not the server that im playing on). However, if i right click it with Personal Shrinking Device to enter the room, there is no problem.

I already asked/checked on Ell's Git/Discord (The author of pretty pipe), he asked for more input from you

### Mod Version

5.1.0

### Forge Version

1.19.1

### Link to Crashlog

https://pastebin.com/8WeDNqGa

### How to reproduce

1. start the game with PrettyPipe and Compact Machine
2. go in to any compact machine, place down pretty pipe in it and exit the room
3. open room review by right click on it without an Personal Shrinking Device in ur hand

**Comment by robotgryphon** [comment]
Looking into this more, this looks like it's more an issue on both sides. While I can add the capability support on my rendering world, Pretty Pipes should be null-handling itself as well. Please report this to them as well!
