### ISSUE TITLE
[Suggestion] PSD as a curio

### ISSUE THREAD

**Issue by gman4161** [CompactMods/CompactMachines#543]
### I am not using performance mods.

- [X] Confirm

### Description

It's annoying having to keep the PSD in my hotbar when working with machines. It would be nice if it were a curio. I imagine right clicking would open the GUI, then you could go into the machine with the button. Then shift right clicking with empty hand on CM wall could transport out.

### Mod Version

any

### Forge Version

any

### How to reproduce

1.put in curio slot
2.right click CM block
3.press the enter button in GUI
4.shift right click CM wall to exit

**Comment by Quezler** [comment]
bumping to avoid it going stale

**Comment by robotgryphon** [comment]
Added curio support and a keybind in the dev build. Will release with 5.2.0.

![Image](https://github.com/CompactMods/CompactMachines/assets/8529636/a7c07a20-b889-460d-97c7-4df57c102cb4)
