### ISSUE TITLE
Mekanism tunnel connection

### ISSUE THREAD

**Issue by BrynBerkeley** [CompactMods/CompactMachines#545]
### I am not using performance mods.

- [X] Confirm

### Description

Mekanism universal cables are not transferring power into compact machines. If I understand correctly, the tunnel wall acts as a buffer of 10k FE. Connecting powered Mekanism cables will fill up the buffer once but once the buffer is drained it isn't refilled.

I've tried:
- Setting the cables on either side of the machine to push/pull
- Adding the chunk loader upgrade to the machine
- Chunk loading the machine in the overworld

If you update the cable i.e. with the Mekanism configurator, the buffer will be refilled once.

### Mod Version

4.5.0

### Forge Version

1.18.2 - 40.1.74

### Screenshot (if available)

![2022-09-03_11 37 48](https://user-images.githubusercontent.com/1958579/188266799-d6be510c-a217-4ead-8b35-5c5309c9f048.png)
![2022-09-03_11 39 14](https://user-images.githubusercontent.com/1958579/188266800-ad91c758-cba6-4b37-bb3c-4308332261cb.png)

### How to reproduce

1. Place down a power source i.e. Mekanism wind generator
2. Run universal cables to the side of the machine
3. Enter the machine
4. Place an energy tunnel inside the machine and configure it to match the side adjacent to the cable in the overworld
5. Run cables inside the machine to something that can pull power i.e. Mekanism energy cube
6. Configure cable on the inside to pull
7. Configure the cable on the outside to push

**Comment by XxArxAngelxX** [comment]
As a workaround, use a cable from Powah mod as the cable that hooks up to the compact machine. Unfortunately, I still couldn't get it to work while outside the machine. I have an automated process inside the machine, but it only exports while outside. Can't get Powah cables to pull power from the buffer from the inside, and I think Mekanism cables break when you're not inside, so I can't find a way to get anything to automatically work that uses power. 

EDIT: Seems Mekanism pipes and wires are just broken whenever you're not in there. My best guess is the way they're programmed to connect together, as when you preview the inside you can see the cables are broken. Tested with a energy cube and powah cables; the machines kept running it seems. Still doesn't fix the issue of getting power from tunnel to powah cables, unless you want to keep charging your energy cube every once in awhile and manually replacing it...

**Comment by Legegends** [comment]
Another workaround for this is to chunkload the chunks I am using ftb maps to do that and chunkloading inside the machine makes it work fine.

**Comment by traffens** [comment]
I can confirm I have this issue.

**Comment by Noobly-Walker** [comment]
I, too, seem to have this issue. I'm running ATM8, and the consensus with ATM8's community is that the energy tunnel does not work, and that wireless interdimensional power must be used instead. I have chunkloaded the inside and the outside of the machine. I have tried thermal fluxduct and powah energy cable, but neither wants to physically connect to either end of the tunnel.
