### ISSUE TITLE
Tunnels placed on bottom of compact machine cannot output to bottom of exterior block.

### ISSUE THREAD

**Issue by Divineaspect** [CompactMods/CompactMachines#549]
### I am not using performance mods.

- [X] Confirm

### Description

Expected to be able to output items to matching sides.

### Mod Version

4.5.0

### Forge Version

1.18.2 - 40.1.68

### How to reproduce

1. Place Large compact machine
2. go inside and place tunnel
3. don't have the ability to select the side which represents the room being the interior and the tunnel being a hole out.

**Comment by Divineaspect** [comment]
poke

**Comment by robotgryphon** [comment]
Cannot reproduce this issue. I tried with both the initial UP direction and the DOWN target. Both stored power and were able to be output without issues.

![Image](https://user-images.githubusercontent.com/8529636/215005240-b08722c8-95ab-4322-a8d7-dc2f63060337.png)
![Image](https://user-images.githubusercontent.com/8529636/215005239-17d55831-637d-4cae-bce4-a21531d42e45.png)

**Comment by Divineaspect** [comment]
initial problem is with using hoppers, hence Items
