### ISSUE TITLE
Refined storage cable issue

### ISSUE THREAD

**Issue by traffens** [CompactMods/CompactMachines#552]
### I am not using performance mods.

- [X] Confirm

### Description

Tried to pipe refined storage cable into a compact machine with no success. I tried with item and power tunnels. This worked fine in 1.12.2 but not here in 1.18.

This was done in Direwolf20's 1.19 FTB modpack.

### Mod Version

4.3.0

### Forge Version

1.18.2-40.1.69

### Screenshot (if available)

![ref](https://user-images.githubusercontent.com/30158124/200973487-43c0dcd3-959e-4a3d-97d9-b1fb154909ba.png)

### How to reproduce

1. connect active refined storage system into compact machine
2. add cable + wireless transmitter
3. failure

**Comment by robotgryphon** [comment]
Refined Storage/AE are not yet supported in 1.18, as evidenced by the lack of specific tunnel items. Your request has been noted for future development, but I will be closing this as not planned.
