### ISSUE TITLE
Crashing when Right-Clicking compact machine

### ISSUE THREAD

**Issue by xXxRonaldxXx** [CompactMods/CompactMachines#554]
### I am not using performance mods.

- [X] Confirm

### Description

I wanted to Right click a Compact machine to see whats in there, but it just crashes the game.
Figered out it crashes when rendering the chickenchunks chunkloader.
[crash-2022-12-03_13.26.43-client.txt](https://github.com/CompactMods/CompactMachines/files/10146356/crash-2022-12-03_13.26.43-client.txt)

### Mod Version

4.3.0

### Forge Version

1.18.2 - 40.1.0

### How to reproduce

1.place chickenchunks chunkloader in CM
2. leave  CM
3. Right click CM

**Comment by jc2xs** [comment]
I'm having crashes as well.  It is related to trying to render the preview when you right click on the compact machine.  It is a render issue and in my case it has something to do with rendering the pretty pipe mod.  My first crash was just a vanilla chest a block of dirt and a pretty pipe connected between the chest and the wall.  I was testing exporting items out of the compact machine.  Removing the chest and the pipe, then I have no issues with the right click of the compact machine and seeing the preview with a single block of dirt in it.

Here is the crash report:  https://pastebin.com/y6J2CXYd

I'm playing Stoneblock 3 from TFP.

Versions:
- Forge:  1.18.2-40.1.92
- Compact Machines:  4.5.0
- Pretty Pipe: 1.12.8
- Java 17

**Comment by jc2xs** [comment]
Out of curiosity, is there a way to disable the preview mode so I can at least prevent the client crashes?

**Comment by robotgryphon** [comment]
This has been identified and fixed for 1.18.2, and will be released with the next version of the mod.

![Image](https://user-images.githubusercontent.com/8529636/215317054-437193f8-9fac-47c7-8025-08b622be3195.png)
