### ISSUE TITLE
[Compatibility] Ars Nouveau- Summon Wilden

### ISSUE THREAD

**Issue by Jophire** [CompactMods/CompactMachines#555]
### I am not using performance mods.

- [ ] Confirm

### Description

Versions:
Ars: ars_nouveau-1.19.2-3.4.6.jar
Compact: compactmachines-5.1.0.jar

Current behavior: When using the Summon Wilden ritual inside of a Compact Machine, the ritual will remove the Solid Walls.

Solid walls should not be destructible.
![2022-12-03_14 40 28](https://user-images.githubusercontent.com/36978900/205459215-1a5b691e-316e-4673-a1e3-5a1343467022.png)

When looking at Solid Wall's tags with F3-H, it does not appear to have any, which may be part of the problem.
Recommend adding:
minecraft:wither_immune
minecraft:dragon_immune
minecraft:features_cannot_replace

### Mod Version

5.1.0

### Forge Version

43.1.55

### How to reproduce

1. Enter a Large or smaller compact machine.
2. Place ritual brazier.
3. Summon Wilden Chimera.

**Comment by Taikira** [comment]
I can confirm from testing that this is reproducible. The blocks in a 4 or 5 block radius are completely removed when the Wilden Chimera is summoned, identical to the image posted.
