### ISSUE TITLE
Issues with chunkloading and tunnels

### ISSUE THREAD

**Issue by ben5446** [CompactMods/CompactMachines#556]
### I am not using performance mods.

- [X] Confirm

### Description

So if i put a hopper into a item funnel to let items out (once i find which way to get it to go out idk how to tell) after a while the outside hopper will stop receiving items so i go back in and go back out and it gets some more but then stops again

Short
Cant keep the chuck loaded for hoppers to bring out items

(you cant light nether portals inside of them so you cant build a chunkloaded and idk what chunkloader update tool does ive used it and it says upgrade applied but nothing happens)

### Mod Version

5.10

### Forge Version

1.19.2 - forge  43.1.52

### How to reproduce

1.make a maxuim machine
2.go inside place a hopper to a item tunnel and figure out how to make it go out (please make it easier to tell)
3.fill with items and go back outside and wait after a little it will stop makin item come out even tho the hopper inside still has items in it

**Comment by ben5446** [comment]
The reason i made this is incase you want to make a small farm in it  but with this problem that wont work

**Comment by DoppelC4ncer0** [comment]
Same issue here, I'm playing right now a modpack called Astropolis, which features also Compact Machines. The Modpack runs on the Minecraft version 1.19.2 and I'm finding the same issue as you. When I try to output anything out of a Compact Machine (i.e. some items or even energy), for a moment items are outputted from the Compact Machine, but then it stop working entirely. I've been trying to set up an FE-Producing farm inside a small compact machine, but no energy comes out even if I upgrade the Compact Machine with the "Chunkloader Upgrade". The mod's file name is compactmachines-5.1.0.jar.

**Comment by Rems19** [comment]
Can confirm, I'm having the same bug, using the mod in the astropolis modpack, just as DoppelC4ncer0.

**Comment by MarcelWind** [comment]
Same issue with 1.19.2 in the Astropolis pack, regardless of machine size. There seems to be a general compatibility problem with Pipez and Mekanism cables that is new to this version. Cables used to connect to faces on the outside, in this version they don't. 
As a result, this mod is practically non-functional.

Also, Tunnels used to show their direction in previous versions of CM, please add this info back in. It's very tedious to guess which tunnel image corresponds to which face.

**Comment by TrashCasterMage** [comment]
RE: The Chunkloader Upgrade

I've found that leaving the world and coming back (in single player) causes the Chunkloader Upgrade to function properly. I assume restarting the server if you're playing on a server will have the same effect.

Obviously this is not intended behavior, but might be a useful workaround until this issue is resolved.

**Comment by MsVoxxie** [comment]
> 

RE

On multiplayer dedicated servers this does not appear to be a solution. A Fix asap would be amazing :)
