### ISSUE TITLE
Simple Storage Networks Compatability

### ISSUE THREAD

**Issue by Lonely-Android** [CompactMods/CompactMachines#557]
### I am not using performance mods.

- [X] Confirm

### Description

When using the wireless remote from Simple Storage Networks on a linked Network Root with inventory in any compact machine, it works in the machine dimension but when returning to the overworld it ceases to work. This shouldn't be an issue as SSN can work in both the End and Nether in my experience, as well as other modded dimensions in previous versions.

### Mod Version

5.1.0

### Forge Version

1.19.2, 43.1.57

### How to reproduce

To Recreate:
- Enter any compact machine block
- Set up a SSN with any chest, a link cable, and a Network Root
- Assure it works by placing an item in the chest and shift right clicking a crafting remote or a storage remote on the root to link the remote, then right click anywhere to see your item in the network
- Leave the compact machine and observe that when right clicking it does not bring up the UI

For any further info, please ask!

Thanks in advance,
Android

**Comment by robotgryphon** [comment]
Is the chunk inside the machine loaded? Since 1.16, the rooms do not load themselves.

**Comment by Lonely-Android** [comment]
Using either the chunk loader upgrade or a chunkloader from a create addon mod (the only chunkloader in my modpack atm) the storage network is still inaccessible. Though I appreciate you reminding me that those are a thing and I didn't think to check with that first.

**Comment by Lonely-Android** [comment]
An interesting thing to note as well, I can access the SSN from in the CM dimension when the network is in the overworld. Just thought I'd put that out there as well.

**Comment by RealMangorage** [comment]
Do you have FTB Chunks?

**Comment by gardenappl** [comment]
> Using either the chunk loader upgrade or a chunkloader from a create addon mod (the only chunkloader in my modpack atm) the storage network is still inaccessible. Though I appreciate you reminding me that those are a thing and I didn't think to check with that first.

Just FYI if the create addon is what I think it is, then that chunkloader doesn't work when it's just placed in the world, it only works when it's on a moving contraption. And the chunkloader upgrade from compact machines does not work if the machine itself is not loaded from the outside (though I could be wrong about that last part)

**Comment by robotgryphon** [comment]
Please comment or close if this issue can be solved with another chunkloading mod - I will be looking at the chunkloader for 5.2.0, but cannot guarantee it will solve the SSN-specific issues.
