### ISSUE TITLE
Chunkloader upgrade does not work as expected

### ISSUE THREAD

**Issue by ghost** [CompactMods/CompactMachines#563]
### I am not using performance mods.

- [x] Confirm

### Description

I attempted to make a basic chicken farm inside of a compact machine block. The chicken farm (Available at this link: https://www.youtube.com/watch?v=vFB9rvmJhVM) is fully functional while I'm inside the machine, and it drains the items into the external item container when I leave. So far, so good...

When I'm outside of the machine, the farm does not function. I've also tried applying the chunkloader upgrade, and that doesn't modify the outcome in any way.

### Mod Version

5.1.0

### Forge Version

1.19.2 - 43.2.0

### Link to Crashlog

N/A

### How to reproduce

1. Create any size of machine at least 5x5x5
2. Place and Enter the machine
3. Create your chicken farm in here (If the lava is active but toggles off when an egg is laid, toggle the comparator once)
4. Use the chicken spawn item to spawn some adult chickens into the kill basin (but also make sure that the laying basin is full as they're required to trigger the lava on and back off)
5. Leave the machine (before the adults in the kill basin get slaughtered)
6. Wait 5-10 **minutes**, observe the lack of production
7. Go back into the machine
8. Wait 5-10 **seconds**, observe the production...

**Comment by hgiabao** [comment]
Having similar problem on ATM8. The compact machine chunks doesn't get loaded even if the compact machine block is in a loaded chunk.

**Comment by P3rf3ctXZer0** [comment]
I tried loading with other loaders too its like it just vanishes off the grid once you leave but it does interact the first time you connect a pipe but then nothing after that.

**Comment by zakini** [comment]
I'm having a similar issue with Immersive Engineering thermoelectric generators in a compact machine, using Pipez energy pipes and an energy tunnel to extract the energy. When I'm inside the machine, the generators work and power everything outside; when I'm outside, no energy comes out of the compact machine, even with the chunkloader upgrade applied. It _does_ work if I use FTB Chunks to force load the compact machine chunk though

**Comment by zakini** [comment]
Ah ha! I figured out why it wasn't working for me.

So FTB Chunks has a `fake_players` setting that defaults to "check". I've got no idea what "check" actually means, but changing that to "allow" means that the Compact Machines chunkloader upgrade _actually_ keeps the chunk inside the machine loaded

**Comment by P3rf3ctXZer0** [comment]
Oh yeah I figured out why mine was not working Remove Someaddons "Limited Chunk Loading"
