### ISSUE TITLE
Entities Disappearing

### ISSUE THREAD

**Issue by ghost** [CompactMods/CompactMachines#564]
### I am not using performance mods.

- [X] Confirm

### Description

At random, when you go out then back in, entities (chickens, in my case) will become invisible. They're still there, the sounds are still being played, they're still doin the things they should be, they're just not visible. This doesn't always happen, but does happen regardless of the presence of other mods. Sometimes they will reappear next time you re-enter the machine, but that doesn't seem to be consistent either.

The frequency of this random event seems to increase once the upgrade is applied to the given machine. 

### Mod Version

5.1.0

### Forge Version

1.19.2 - 43.2.0

### Screenshot (if available)

https://prnt.sc/JWKfs-nWy3BE

### How to reproduce

1. Place animals (chickens)
2. Leave compact machine
3. Enter compact machine

**Comment by Apceniy** [comment]
This usually happens to people who are using OptiFine. Are you sure you're not using performance mods as promised?

**Comment by RealMangorage** [comment]
please send us your Modlist so we can check if it is Compact Machines.

**Comment by ghost** [comment]
> This usually happens to people who are using OptiFine. Are you sure you're not using performance mods as promised?

I'm not. As far as I know, Optifine is not compatible with AMD devices, and I'm running an AMD RX580 Series.


> please send us your Modlist so we can check if it is Compact Machines.

Is there some way to export the modlist as text or markup? I've never been asked to do this before, so.

**Comment by RealMangorage** [comment]
upload the debug.log

**Comment by RealMangorage** [comment]
The logs/debug.log file

**Comment by ghost** [comment]
> The logs/debug.log file

That file doesn't exist. Anyway.... Mods folder content is as follows;

> AdLods-1.19.2-7.0.8.0-build.0785.jar
> AE2-Things-1.1.1.jar
> AE2WTLib-12.8.5.jar
> AEInfinityBooster-1.19.2-1.2.0+11.jar
> AllTheCompressed-1.19.2-2.0.0.jar
> alltheores-2.0.2-1.19.2-43.1.3.jar
> almostunified-forge-1.19.2-0.3.7.jar
> appliedenergistics2-forge-12.9.2.jar
> architectury-6.5.77-forge.jar
> BetterAdvancements-1.19.2-0.2.2.142.jar
> BetterF3-4.0.0-Forge-1.19.2.jar
> cloth-config-8.2.88-forge.jar
> Clumps-forge-1.19.2-9.0.0+14.jar
> CommonCapabilities-1.19.2-2.9.0.jar
> compactmachines-5.1.0.jar
> configured-2.1.1-1.19.2.jar
> create-1.19.2-0.5.0.i.jar
> create-stuff-additions1.19.2_v2.0.2b.jar
> createaddition-1.19.2-20230404a.jar
> create_misc_and_things_1.19.2_2.0.jar
> curios-forge-1.19.2-5.1.3.0.jar
> CyclopsCore-1.19.2-1.18.2.jar
> DarkModeEverywhere-1.19.1-1.0.3.jar
> EdivadLib-1.19.2-1.2.0.jar
> FastLeafDecay-30.jar
> ForgeEndertech-1.19.2-10.0.5.2-build.0735.jar
> immersive-portals-2.3.4-mc1.19.2-forge.jar
> ImmersiveEngineering-1.19.2-9.2.0-162.jar
> ImmersivePosts-1.19.2-4.3.0-6.jar
> immersive_aircraft-0.3.1+1.19.2-forge.jar
> industrial-foregoing-1.19.2-3.3.2.3-5.jar
> IntegratedCrafting-1.19.2-1.1.1.jar
> IntegratedDynamics-1.19.2-1.16.2.jar
> IntegratedTerminals-1.19.2-1.4.5.jar
> IntegratedTunnels-1.19.2-1.8.18.jar
> Jade-1.19.1-forge-8.8.1.jar
> jei-1.19.2-forge-11.6.0.1013.jar
> jeimultiblocks-1.19.2-0.0.3.jar
> journeymap-1.19.2-5.9.5-forge.jar
> JustEnoughResources-1.19.2-1.2.2.200.jar
> kubejs-create-forge-1902.1.1-build.32.jar
> kubejs-forge-1902.6.0-build.142.jar
> mcjtylib-1.19-7.2.2.jar
> megacells-forge-1.5.3-1.19.2.jar
> Mekanism-1.19.2-10.3.8.477.jar
> MouseTweaks-forge-mc1.19-2.23.jar
> Patchouli-1.19.2-77.jar
> pipez-1.19.2-1.0.1.jar
> rftoolsbase-1.19-4.1.7.jar
> rftoolsbuilder-1.19-5.2.5.jar
> rftoolspower-1.19-5.1.2.jar
> rftoolsstorage-1.19-4.1.2.jar
> rftoolsutility-1.19-5.1.6.jar
> rhino-forge-1902.2.2-build.268.jar
> simplegrinder-19.1.2.jar
> slabstoblocks-1.19.2-0-forge.jar
> smeltingsand-1.19.2-11-forge.jar
> SolarGeneration-1.19.2-5.2.1.jar
> TheWool_1.19.2_forge_v5.2.0.jar
> Tiny-Coal-Forge-1.19.2-1.0.1.jar
> titanium-1.19.2-3.7.2-26.jar
> trainPortal0_1_73.jar


As stated in the report though, this "does happen regardless of the presence of other mods." (I'd gone in and disabled everything except the compact machines and PrettyF3 mods prior to making the report)

**Comment by robotgryphon** [comment]
Currently triaging this for 5.2; is this happening on singleplayer, multiplayer, or both?

**Comment by P3rf3ctXZer0** [comment]
Everything I break vanishes plus entities vanish.

**Comment by robotgryphon** [comment]
Closing for lack of response on environment
