### ISSUE TITLE
Crash server when entering in any compact machine.

### ISSUE THREAD

**Issue by Othoiko974** [CompactMods/CompactMachines#566]
### I am not using performance mods.

- [X] Confirm

### Description

Hi,
On my ATM8 (Version 1.0.15) modpack server, when I'm trying to enter a compact machine by right clicking it crashes the server.

Note : 
- I tried it when removing any performance mod (radon, rubidium, occulus, etc.), it's the same.
- On singleplayer it doesn't crash.

Have a nice a day!

### Mod Version

5.1.0

### Forge Version

43.2.6

### Link to Crashlog

https://pastebin.com/rDqWuVXi

### Screenshot (if available)

Same reported here on the [ATM8 Github](https://github.com/AllTheMods/ATM-8/issues/1000) but label as "Mod Issue"

Same situation as the media provided: [YT link](https://www.youtube.com/watch?v=b_joVt4mmsU)

### How to reproduce

1. Enter an ATM8 modpack server. 
2. try entering a compact machine, any size, using the personal device thingy.

**Comment by robotgryphon** [comment]
I'm going to need more information on this to troubleshoot. From the logs, it's hanging trying to get chunk information from the server. Unfortunately there's far too many mods at play here (and mixins as well) to narrow down any culprits.

In addition, what kinds of rooms are you trying to create? Max size rooms, existing rooms?
