### ISSUE TITLE
Mekanism cables not working with tunnels

### ISSUE THREAD

**Issue by izakfab** [CompactMods/CompactMachines#567]
### I am not using performance mods.

- [x] Confirm

### Description

I attempted connecting mekanism energy cube that's outside the machine with the inside of the machine using energy tunnel. Visually cables get connected both outside to the machine and on the inside to the tunnel but the energy isn't passing through.
![2023-04-19_21 38 23](https://user-images.githubusercontent.com/92325936/233194710-32511750-7a17-4c6b-8087-bf45ec550295.png)
![2023-04-19_21 38 36](https://user-images.githubusercontent.com/92325936/233194719-9b733cc2-caec-4b02-a1c2-5e4e956efd0c.png)
![2023-04-19_21 38 38](https://user-images.githubusercontent.com/92325936/233194721-01a66fcd-f788-4c10-aa0d-39485f85078e.png)

### Mod Version

5.1.0

### Forge Version

1.19.2 - 43.2.3

### How to reproduce

1. Place an energy tunnel on the inside of the machine
2. Configure it to the side of the machine where the energy is coming from on the outside through mekanism cable
3. Put the mekanism cable on the inside next to the energy tunnel

**Comment by Apceniy** [comment]
The tunnels are essentially the buffers; you're supposed to both put the energy into the tunnel and pull out of it. It won't output automatically. Also, make sure that chunks on the both sides are loaded, they're not loaded automatically unless using the chunkloader upgrade (but even then it can get pretty buggy).

**Comment by izakfab** [comment]
> The tunnels are essentially the buffers; you're supposed to both put the energy into the tunnel and pull out of it. It won't output automatically. Also, make sure that chunks on the both sides are loaded, they're not loaded automatically unless using the chunkloader upgrade (but even then it can get pretty buggy).

So I did try putting the mekanism's metallurgic infuser inside the machine, I put the chunkloader upgrade on and used FTB chunk's force load option on the chunks on the outside but it still doesn't work.

**Comment by Apceniy** [comment]
Did you also configure the cable inside of the machine to actively pull out a tunnel instead of passively receiving it?

**Comment by izakfab** [comment]
> Did you also configure the cable inside of the machine to actively pull out a tunnel instead of passively receiving it?

This worked thank you. I didn't have much experience with mekanism and didn't know there was an option to do that.
