### ISSUE TITLE
Issue drawing power from Compact Machine with Mekanism cables

### ISSUE THREAD

**Issue by ThtGuyMichael** [CompactMods/CompactMachines#568]
### I am not using performance mods.

- [X] Confirm

### Description

I attempted to create a Mekanism Gas-Burning generator set up inside a large Compact Machine and use energy tunnels to transport the energy. Although the Mekanism cable connects to the outside, it isn't receiving power throughput. I've tried using storage devices in lieu of cables, I've tried manually setting push/pull status to no avail.

![2023-05-01_21 52 31](https://user-images.githubusercontent.com/21272951/235582509-dfb99c45-7999-4425-a317-a257cc0e7420.png)
![2023-05-01_21 52 44](https://user-images.githubusercontent.com/21272951/235582514-8692bd13-80cd-4a13-8771-aed5b526ea8b.png)

### Mod Version

5.1.0

### Forge Version

1.19.2 - 43.2.8

### How to reproduce

1. Place Compact Machine
2. Place an energy tunnel inside and send power to the tunnel.
3. Place the receiver cable on the outside of the Compact Machine.

**Comment by Apceniy** [comment]
Are you sure both of the sides are chunkloaded?

**Comment by ThtGuyMichael** [comment]
My understanding is the FTB Skies loads the compact machine chunk as long as the block is loaded in the overworld.

![2023-05-02_11 18 37](https://user-images.githubusercontent.com/21272951/235751984-9c98aab5-b2f0-4d70-be1a-8498a70bbf40.png)

**Comment by Apceniy** [comment]
It used to be a thing in 1.12.2, but now you need either a chunkloader upgrade or load the chunk through your own means. The mod on 1.19.2 won't load anything automatically.

**Comment by ThtGuyMichael** [comment]
Thank you for the info! The chunk loader upgrade seems to be locked/unavaialble in this pack. I'll have to try another method.

**Comment by Noobly-Walker** [comment]
Even when chunkloaded both inside and out, wires will not connect to the tunnel. The ATM community swears up and down that the energy tunnel is borked, and wireless interdimensional power solutions are the only means of getting power in or out.

**Comment by MuteTiefling** [comment]
Having a slightly different experience here, but similar enough I think it should just be added here. 

I can send power into the compact machine's tunnel from the outside, and The One Probe shows that power in the block on the inside. 

However, these tunnels do not appear to push power. So far my testing for pulling that power on the inside goes as follows:

Immersive Engineering: Cannot pull from the block
Modular Routers: Cannot pull from the block
Mekanism's Universal Cables: CAN pull, but must be set to pull mode.
Powah: Cannot pull from the block 
xNet: Cannot pull from the block
Thermal Flux Cell: CAN pull from the block, if the side facing it is set to pull mode.

I believe the issue here is that all the ones that aren't working are expecting power to be pushed into them, and therefore are not attempting to pull on their own. 


Mod Version: compactmachines-5.1.0

**Comment by Shados** [comment]
I'm playing with 5.1.0 on MC 1.19.2, and Mekanism's universal cables don't appear to be able to put power through the energy tunnels. I have the universal cables explicitly set to Push into the tunnel on the inside and Pull on the outside, but I don't get any energy output on the outside. Both sides are chunkloaded.

**Comment by HeatherComputer** [comment]
From some discussion, I put forward this two-step solution:

- Make the buffer for these tunnels configurable, and let them auto-push.
    - This would mean the bound CM BE would need to tick. That's.. not ideal, as it adds extra overhead, but it does resolve the push/pull issue.
  - Having the buffer too high would lead to the tunnel potentially draining the whole supply, hence the config.
  - The mod [More Energy Tunnels](https://www.curseforge.com/minecraft/mc-mods/more-energy-tunnels) adds a few "tiers" with different buffers. They're still not configurable though, and still don't push.
  
  
   
   
 - Make a tunnel that just forwards the capability.
     - This was the strategy in 1.12!
   - It would solve both of these issues here.
   - However, it would break a few things:
       - Some cables do not allow you to pull from them. This is true for mekanism cables with a *recognised connection* for example, or conduits (which aren't in 1.19 in all fairness)
    - It'd also allow for some new situations:
        - The [ME Capability Adapter](https://www.curseforge.com/minecraft/mc-mods/capability-adapter) mod is impossible without this feature.
      - Gases in Mekanism have a proper capability implementation. This is not supported with current tunnels, but would work with this tunnel.
      - Anything else could add a capability and use it with this tunnel.
      
      
 I think having both of these would be the best solution, though either one would work as a partial-fix.

**Comment by HeatherComputer** [comment]
Chunkloading wasn't the issue here - could I request that this gets re-opened? I was planing to look into a pr once I've got some other stuff out of the way, though that's taking longer than I expected.

**Comment by HeatherComputer** [comment]
In regards to this - suppose someone makes a pr that a) adds a capability forwarding tunnel and b) adds configs for the buffers for the existing tunnels, how will the difference between the two be explained to the end user?

**Comment by MuteTiefling** [comment]
Seems to me that it would make the most sense to drop the current ones entirely and have them all act the same.

Given they're all the same item anyway, this would be seemless in current worlds.

**Comment by HeatherComputer** [comment]
If we did that, which of my suggested strategies do you think would be best? (or do you have a third option in mind?)

**Comment by MuteTiefling** [comment]
Option a, forward capabilities.

**Comment by robotgryphon** [comment]
The entire design goal of tunnels in the modern versions is not to have a one-size-fits-all tunnel that forwards caps. That proved to be very hit-or-miss even in 1,12, and with Forge's changes to capabilities in 1.19 it's even HARDER to get it right.

The main reason for this is for stuff like EnderIO or LaserIO - things that push multiple resources in through one block. With the new system you can separate concerns inside the room, and handle things exactly the way you want to. If you need a combined tunnel, it's not too difficult to implement one.

All of this is going to be overhauled again in 1.20/1.21 with plans I have.

**Comment by robotgryphon** [comment]
As for the point in energy tunnels -- no, I will not be increasing the limit. Go yell at other mods for using absurd values like 20,000 FE to make a piece of cobblestone. The energy meta has gotten far too out of reach and I refuse to be a part of it. 10k is fine for built-in.

**Comment by MuteTiefling** [comment]
I agree 10k would be mostly sufficient in many cases. But setting a reasonable default and letting pack makers tweak it according to their own balance design would be appreciated.

It's currently non functional, however, since it doesn't push as FE sources are meant to.

**Comment by MuteTiefling** [comment]
Also, re capabilities, I get your point there but you're also locking yourself out of compatibility with many mods. Pneumaticcraft heat and air both use capabilities, but because you don't support them, those mods can't function with compact machine tunnels.

Seems that the solution would be to allow multiple ports on the inside that all link to the same side outside.

**Comment by robotgryphon** [comment]
Mute, this is something I'm considering for a larger tunnel/resource overhaul. I plan to make machines as a whole more useful to modpack makers, but there's some preliminary work that needs done first. Once I get 1.20 starting to move along, I'm going to be writing up a more formal document on those plans.

**Comment by robotgryphon** [comment]
For now, 1.19.2 is in a bugfix/wind-down state. Most modpacks are stabilizing or finished by now. Not going to compromise those in search of getting tunnels perfect.
