### ISSUE TITLE
No Recipe for Chunk Loader

### ISSUE THREAD

**Issue by Cleardragonf** [CompactMods/CompactMachines#574]
### I am not using performance mods.

- [X] Confirm

### Description

There isn't a recipe by JEI that displays The Chunkloaders recipes...why?

### Mod Version

4.5.0

### Forge Version

1.18.2-40.1

### How to reproduce

1.play with JEI installed
2.
3.

**Comment by robotgryphon** [comment]
This was intentional, as the chunk loading functionality was experimental and not yet stable.
