### ISSUE TITLE
Powah! cables not connecting and not able to send or draw power

### ISSUE THREAD

**Issue by Meteoblastdragon** [CompactMods/CompactMachines#587]
### I am not using performance mods.

- [X] Confirm

### Description

Playing ATM8 modpack. Can't connect Powah! cables to the compact machines. Testing it in the creative world here. Yes, I made sure to use the right tunnels cause as soon as I switch to Pipez it works as intended.

### Mod Version

5.1.0

### Forge Version

1.19.2 - 43.2.14

### Screenshot (if available)

![image](https://github.com/CompactMods/CompactMachines/assets/118288901/57b5fdea-1afd-48ef-ab34-15736efcab90)
![image](https://github.com/CompactMods/CompactMachines/assets/118288901/1da5cc3b-4f57-4156-869c-b02c3c55772f)

### How to reproduce

1. Setup any compact machine with energy tunnels
2. Try to connect powah cables with some power source and power receiver
3. Nothing works

**Comment by jpeaglesandkatz** [comment]
Yeh I have no clue on how to connect anything from inside to out or vice versa... Would be useful as well if the version 7 of this mod would have some sort of documentation on the changes
