### ISSUE TITLE
Using carry-on mod disconnects machine from room

### ISSUE THREAD

**Issue by delavanty** [CompactMods/CompactMachines#589]
### I am not using performance mods.

- [X] Confirm

### Description

adding the carry on mod by Tschipp the mod stops letting u into compact machines once removed its back to normal i dont know if i should  be reporting this to u but its a incompatibilty between the two 

### Mod Version

5.1.0

### Forge Version

1.19.2

### How to reproduce

1.install carry on
2. step two click on compact machines with right click

**Comment by robotgryphon** [comment]
For now, please blacklist Compact Machine blocks via their configuration:

https://github.com/Tschipp/CarryOn/wiki/Black---and-Whitelist-Config

In the future, bound Compact Machines are tagged and support the common RELOCATION_NOT_SUPPORTED tags.
