### ISSUE TITLE
Crash when viewing preview of Compact Machine containing ChickenChunks chunk/spot loaders

### ISSUE THREAD

**Issue by etmoonshade** [CompactMods/CompactMachines#596]
### I am not using performance mods.

- [x] Confirm

### Description

Right-clicked the machine with an empty hand, got a hang and crash. Pretty simple. Lots of mods, unfortunately. See screenshot below for where it hangs.

(Added: Pretty clearly traced it to an interaction with ChickenChunks - see reproduction steps)

Obviously, I'd expect to see the machine preview instead of getting a crash.

### Mod Version

6.0.1.0

### Forge Version

1.20.1 - 47.3.0

### Link to Crash Log

https://www.dropbox.com/scl/fi/d6rjq3s2s21uau4a7kyo1/latest20241122-etmoonshade.log?rlkey=mgnz3b1dh4sqlli0dfw0dy7rp&dl=0

### Screenshot (if available)

![Image](https://github.com/user-attachments/assets/433fd513-bbba-49fd-83d7-5f11d88b9cd1)

### How to reproduce

I did a bit of testing while chatting with Nano, and it looks like the ChickenChunks chunkloader and spotloader both cause the game to crash when it tries rendering it. The above log example was specifically with the spotloader, but I got the same results when I replaced it with a full chunkloader.

1. Create a compact machine. My example is a huge one, didn't check others.
2. Enter machine and add a ChickenChunks chunk loader or spot loader.
3. Exit machine and right click to get the preview. You should see a crash.

**Comment by robotgryphon** [comment]
Fixed in version 6.0.2.

![Image](https://github.com/user-attachments/assets/f92c9da6-5e34-4955-b5c6-3be4d8cffa4b)
