### ISSUE TITLE
[21.1] Most of the CM blocks don't show in game

### ISSUE THREAD

**Issue by jpeaglesandkatz** [CompactMods/CompactMachines#598]
### I am not using performance mods.

- [x] Confirm

### Description

Clean instance of 1.21.1 + neoforge 21.1.80

Only the blocks shown in the screenshot are ingame...

I was trying to add the CM mod to ATM10 and the same happened. That is why I tried it with a clean instance with only neoforge and CM.[latest.log](https://github.com/user-attachments/files/17935532/latest.log)

![Image](https://github.com/user-attachments/assets/a3ba4115-204d-4ef2-9720-ba53ce7a3d29)

### Mod Version

7.0.14

### Forge Version

21.1.80

**Comment by robotgryphon** [comment]
This is intentional; modpack authors are encouraged to use something like KubeJS or a global datapack to add toom templates. 

If you are playing in singleplayer, you can add the basic templates by either using the `/datapack` command, or enabling the room templates datapack during world creation.

**Comment by robotgryphon** [comment]
Guide: https://github.com/CompactMods/CompactMachines/wiki/CM7-%E2%80%90-Enabling-Basic-Room-Templates
