### ISSUE TITLE
version 6.0.2 is missing what Minecraft version the update belongs to

### ISSUE THREAD

**Issue by ModernGamingWorld** [CompactMods/CompactMachines#600]
### I am not using performance mods.

- [x] Confirm

### Description

Went on Curseforge to check out the new update and all it shows is Game version Forge and Java 17, but no actually mc version

### Mod Version

6.0.2

### Forge Version

1.20.1

### How to reproduce

1. Check Curseforge see no mc versions
2.
3.

**Comment by robotgryphon** [comment]
Fixed
