### ISSUE TITLE
Compact Machine Wall (Can't break)

### ISSUE THREAD

**Issue by jburrows82** [CompactMods/CompactMachines#9]
Heh obviously the smart thing is to not place a Machine Wall block in creative mode, but by the chance of an accident, could you make it possible to break/remove somehow?

**Comment by WeegeeTheGenie** [comment]
You can use the fill command.

**Comment by Stinkyboys** [comment]
hi i also placed a wall and i cant break it is there a way to?

**Comment by SizableShrimp** [comment]
You break it by holding a Personal Shrinking Device in your inventory and being in creative and left clicking it.
